/**
 * auth feature text (verbatim from the classic UI: root constants.js UI +
 * static auth labels in index.html).
 */
export const TEXT = {
  "AUTH_LOGIN_TITLE": "欢迎回到经途·伴学",
  "AUTH_LOGIN_SUB": "登录后继续管理需求、会话与合同",
  "AUTH_LOGIN_TITLE_GUEST": "登录后继续刚才的操作",
  "AUTH_LOGIN_SUB_GUEST": "登录成功后会自动返回你刚才所在的页面",
  "AUTH_LOGIN_TITLE_TEACHER": "登录教师账户",
  "AUTH_LOGIN_SUB_TEACHER": "教师端可浏览学生需求、提交试课意向和管理合同",
  "AUTH_LOGIN_TITLE_STUDENT": "登录学生账户",
  "AUTH_LOGIN_SUB_STUDENT": "学生端可发布需求、联系老师和管理签约",
  "BTN_LOGIN": "登录",
  "BTN_REGISTER": "注册",
  "BTN_CANCEL": "取消",
  "BTN_BACK_LANDING": "返回首页",
  "BTN_NEXT_STEP": "下一步",
  "BTN_PREV_STEP": "上一步",
  "BTN_BIND": "绑定",
  "LOGIN_IDENTIFIER_PLACEHOLDER": "请输入用户名/手机号/邮箱",
  "LOGIN_PASSWORD_REQUIRED": "请输入登录密码",
  "LOGIN_SWITCH_CODE": "验证码登录",
  "LOGIN_SWITCH_PASSWORD": "密码登录",
  "LOGIN_ACCOUNT_MISSING": "没有找到这个用户名、手机号或邮箱。请检查输入；还没有账号的话，可以先注册。",
  "HINT_ROLE_STUDENT": "学生账户",
  "HINT_ROLE_TEACHER": "教师账户",
  "HINT_ROLE_ADMIN": "管理员账户",
  "USERNAME_USE_PASSWORD": "用户名账户请使用密码登录",
  "LOADING_LOGIN": "登录中...",
  "LOADING_REGISTER": "注册中...",
  "LOADING_VERIFY": "核验中…",
  "CODE_LABEL": "验证码",
  "CODE_PLACEHOLDER": "输入验证码",
  "CODE_SEND": "发送验证码",
  "CODE_SEND_AGAIN": "{time}后重发",
  "CODE_SENT": "验证码已发送",
  "OTP_PHONE_LABEL": "手机验证码",
  "OTP_EMAIL_LABEL": "邮箱验证码",
  "OTP_SCENE_BIND": "绑定验证",
  "OTP_SCENE_LOGIN": "登录验证",
  "OTP_SCENE_REGISTER": "注册验证",
  "OTP_BIND_DONE": "绑定成功",
  "BIND_PHONE_TITLE": "绑定手机号",
  "BIND_EMAIL_TITLE": "绑定邮箱",
  "PHONE_LABEL": "手机号",
  "PHONE_PLACEHOLDER": "请输入中国大陆手机号",
  "EMAIL_LABEL": "邮箱",
  "EMAIL_PLACEHOLDER": "请输入邮箱",
  "CRED_IDENT_INVALID": "请输入有效的手机号或邮箱",
  "CRED_FORMAT_PHONE": "手机号格式不正确",
  "CRED_FORMAT_EMAIL": "邮箱格式不正确",
  "REG_WIZARD_STEPS": ["验证邀请码","填写账号信息","验证手机或邮箱"],
  "REG_INVITE_LABEL": "邀请码",
  "REG_INVITE_PLACEHOLDER": "请输入管理员提供的邀请码",
  "REG_INVITE_HINT": "邀请码由管理员发放，一枚邀请码仅限一人使用。没有邀请码请联系平台负责人。",
  "SUCCESS_INVITE_CONFIRMED": "邀请码已确认，请填写注册信息",
  "REG_USERNAME_LABEL": "用户名",
  "REG_USERNAME_PLACEHOLDER": "3-30 个字符",
  "REG_PASSWORD_LABEL": "密码",
  "REG_PASSWORD_PLACEHOLDER": "至少 6 个字符",
  "REG_PASSWORD2_LABEL": "确认密码",
  "REG_PASSWORD2_PLACEHOLDER": "再输入一次密码",
  "REG_CONTACT_LABEL": "手机号或邮箱",
  "REG_CONTACT_PLACEHOLDER": "请输入手机号或邮箱",
  "REG_CONTACT_HINT": "绑定手机或邮箱用于登录和找回账号，任选一种即可，需通过验证码验证。",
  "REGISTER_CONTACT_REQUIRED": "请填写手机号或邮箱并输入验证码",
  "VALIDATE_INVITE_FIRST": "请先验证邀请码",
  "VALIDATE_INVITE_REQUIRED": "请输入邀请码",
  "VALIDATE_PASSWORD": "密码至少 6 个字符",
  "VALIDATE_PASSWORD_MISMATCH": "两次密码不一致",
  "USERNAME_LENGTH_ERR": "用户名长度需在 3-30 个字符之间",
  "AGREE_PREFIX": "我已阅读并同意",
  "AGREE_LINK_AGREEMENT": "用户协议",
  "AGREE_LINK_PRIVACY": "隐私政策",
  "AGREE_REQUIRED": "请先勾选同意用户协议与隐私政策",
  "LOGIN_IDENTIFIER_LABEL": "用户名 / 手机号 / 邮箱",
  "LOGIN_PASSWORD_LABEL": "登录密码",
  "LOGIN_REMEMBER": "在这台设备上保持登录，下次免输密码",
  "LOGIN_CODE_HINT": "验证码将发送到该账户绑定的手机或邮箱，5 分钟内有效，每天最多发送 10 次",
  "BTN_BACK": "返回",
  "BTN_GO_REGISTER": "立即注册",
  "REGISTER_TITLE": "创建你的账户",
  "REGISTER_SUB": "学生免费发布需求，教师零佣金接单",
  "REG_ROLE_STUDENT": "我是学生",
  "REG_ROLE_TEACHER": "我是教师",
  "REGISTER_HAVE_ACCOUNT": "已有账户？",
  "REGISTER_GO_LOGIN": "直接登录",
};
