/**
 * Contract domain — standalone model (S5). The contract is an independent record, decoupled from
 * demands and from the conversation lifecycle:
 *   - `contracts` table carries its own party tuple (student_user_id / teacher_user_id).
 *   - `conversation_id` is a nullable historical link (no FK cascade — deleting a conversation
 *     never deletes signed/revoked contracts, which are retained as evidence).
 *   - State machine: draft (signing) -> double confirmation -> signed; revoke marks revoked=1
 *     (the row and its ledger chain are kept); cancel rolls one side back to signing.
 *   - The ledger chain (contract_ledger) fingerprints every signed body hash; verify rehashes
 *     the latest entry and walks prev_hash links to detect any tampering.
 *   - Dangerous operations (draft / sign / revoke / cancel / admin remove) require a fresh
 *     capToken via danger-ops.confirmDangerOtp.
 *
 * The full contract body is generated by buildContractMd (business clauses) + fixed legal clauses
 * (LEGAL_CLAUSES) + signature block (buildSignatureBlock). Only the business section is editable.
 */
import { dbGet, dbAll, dbRun, json, error, errorMsg, toDbTime, parseIdParam } from '../../core/util.js';
import { getLedgerDb } from './schema.js';
import { requireUser, requireAdmin, requireAdminOrError } from '../../core/security.js';
import { bufToHex, encryptField } from '../../core/crypto.js';
import { confirmDangerOtp } from '../../core/danger-ops.js';
import { SERVER_TEXT } from '../../../shared/codes.js';
import { STATUS, CONTRACT_STATUS } from '../../../shared/enums.js';
import { LIMITS } from '../../../shared/config.js';
import {
  dbGetContractById, dbGetMyContracts, dbGetAllContractsAdmin, dbDeleteContract, dbCreateContract, dbSetContractMd,
} from './repo.js';
import { dbGetConversationWithNames, dbCreateMessage, dbGetTeacherProfile } from '../../../../server/db.js';
import { acceptEligibility } from '../teacher/api.js';
import { notifyUser } from '../../core/notify.js';
import { logEvent } from '../../core/log.js';
const UIC = SERVER_TEXT;

// Business-clause marker: splits the editable business section from the fixed legal section.
// The marker literal is contract content (not a comment) — its prefix is locked by the
// cross-stack sentinel parity test (test/contract-sentinel-parity.test.js).
export const CONTRACT_BUSINESS_END = '<!-- 业务条款结束，以下法律条款由平台固定，不可修改 -->';

// Fixed legal clauses (platform-controlled, never editable; re-appended server-side on save)
const LEGAL_CLAUSES = `## 第四条 甲方权利与义务

1. 有权要求乙方按照约定的内容与时间安排授课，并对教学质量进行监督；
2. 应按约定支付课时费，并为授课提供必要的学习条件与配合；
3. 如需调整课程安排，应提前与乙方协商并达成一致；
4. 对通过平台获取的教师个人信息，仅用于本次家教服务目的，不得向第三方泄露。

## 第五条 乙方权利与义务

1. 有权按约定获取课时报酬；
2. 应按约定认真备课、授课，保证教学质量；
3. 如需调整课程安排，应提前与甲方协商并达成一致；
4. 对授课过程中知悉的学生个人信息与学习情况予以保密，不得向第三方泄露。

## 第六条 课程调整、补课与违约责任

1. 任一方无法按时上课，应提前通知对方，并协商安排补课或调课；
2. 因一方过错给对方造成损失的，双方应友好协商解决；
3. 任一方严重违反本合同约定的，另一方有权解除本合同，违约方应承担相应责任。

## 第七条 合同的变更与解除

经双方协商一致，可以变更或解除本合同；任一方提前终止合同的，应提前告知对方，并妥善结清已发生而未支付的课时费用。

## 第八条 争议解决

因履行本合同发生争议，双方应首先友好协商解决；协商不成的，可依法向有管辖权的人民法院提起诉讼。

## 第九条 生效与存证

本合同自双方在平台内确认签约后生效，双方账户内各存一份，内容相同。平台对签署时的合同文本及其数字指纹（SHA-256）进行独立留档，供任一方事后校验文本一致性。

双方约定：以平台账号登录、签署时密码二次确认、服务端签署时间戳以及全文内容哈希存证，共同构成本合同电子签署的可靠条件（《中华人民共和国电子签名法》第十三条第二款），与手写签名或盖章具有同等法律效力。

---

`;

// Article 10 (signature record) is generated by buildSignatureBlock and embedded at the end of
// the body; on modify/re-rebuild it is dropped and rebuilt from the current sign state.

/** Business section + marker + fixed legal section -> full contract body */
export function contractWithLegal(businessMd) {
  const biz = String(businessMd || '').trim();
  return `${biz}\n\n${CONTRACT_BUSINESS_END}\n\n${LEGAL_CLAUSES}`;
}

// Signature block: records who signed / when inside the contract body itself. The block only
// carries the contract flow number #CD{id}; the raw SHA-256 is exposed through the ledger
// verify endpoint (avoiding a self-referencing "hash before body" loop).
export function buildSignatureBlock({ studentName, teacherName, studentSignedAt = '', teacherSignedAt = '', contractId }) {
  const partyLine = (name, signedAt) => signedAt
    ? `**${name}**（平台账号：${name}）\n签署状态：已签署　签署时间：${signedAt}`
    : `**${name}**（平台账号：${name}）\n签署状态：待签署`;
  const flowNo = contractId ? `#CD${String(contractId).padStart(6, '0')}` : '';
  return `

## 第十条 签署记录

双方确认：以下签署人已通过本人平台账号完成实名登录，并凭本人密码二次确认表达签署意愿；平台服务端记录签署时间并留存全文指纹，作为本合同的电子签署凭证。

**甲方（学生方）**：
${partyLine(studentName, studentSignedAt)}

**乙方（教师方）**：
${partyLine(teacherName, teacherSignedAt)}

平台存证：本合同全文 SHA-256 指纹已纳入防篡改存证链${flowNo ? `（存证流水号 ${flowNo}）` : ''}，任一方可随时通过平台「存证校验」核对文本一致性。`;
}

// Rebuild the full body (business + legal + signature block): the old signature block sits after
// the legal clauses and is dropped/rebuilt from the current sign state. Used by sign and cancel
// (PUT clears signed_at) so contract_md always mirrors the latest sign state. Old-format contracts
// without the marker are returned untouched (legal double-append protection).
export function rebuildFullMd(ct, conv) {
  const md = String(ct.contract_md || '');
  if (!md.includes(CONTRACT_BUSINESS_END)) return md;
  const biz = md.split(CONTRACT_BUSINESS_END)[0].trim();
  return contractWithLegal(biz) + buildSignatureBlock({
    studentName: conv.student_name, teacherName: conv.teacher_name,
    studentSignedAt: ct.drafter_signed_at || '', teacherSignedAt: ct.other_signed_at || '',
    contractId: ct.id,
  });
}

// Contract body must never be rewritten once signed (evidence chain integrity). Deactivated
// usernames are surfaced by the frontend "party deactivated" tag; contract_md is never touched.

// Build the editable business section of the contract. User-controlled fields strip the business
// marker (Q-2e-F3) so a malicious embed cannot truncate the tail / mis-place the legal block.
export function buildContractMd({ teacherName, studentName, method, schedule, location, plan, rate, createdAt, payMethod, payMethodOther, firstLessonDate, trialPay, trialPayOther }) {
  const stripSep = v => String(v ?? '').split(CONTRACT_BUSINESS_END).join('');
  const methodName = method === 'offline' ? '线下授课' : '线上授课';
  const locationText = stripSep(location) || (method === 'offline' ? '甲方常住处或双方另行约定的地点' : '双方约定的线上课堂');
  const PAY_METHOD_TEXT = { per_session: '次付（按次结算，每次课程结束后支付）', weekly: '周付（每周结算一次）', monthly: '月付（每月结算一次）' };
  const TRIAL_PAY_TEXT = { first_free: '第一次试课免费', first_hour_free: '第一小时免费，第二小时起按约定时薪收费', normal: '试课全程正常收费' };
  const payText = payMethod === 'other' ? (stripSep(payMethodOther) || '由双方另行约定') : (PAY_METHOD_TEXT[payMethod] || '由双方另行约定');
  const trialText = trialPay === 'other' ? (stripSep(trialPayOther) || '由双方另行约定') : (TRIAL_PAY_TEXT[trialPay] || '由双方另行约定');
  const biz = `# 家教服务合同

**甲方（学生方）**：${stripSep(studentName)}
**乙方（教师方）**：${stripSep(teacherName)}
**签署日期**：${createdAt || ''}

甲乙双方本着平等、自愿、诚实信用的原则，依照《中华人民共和国民法典》及相关法律法规，经友好协商，就家教服务事宜达成如下协议：

## 第一条 服务内容与授课安排

1. 授课方式：${methodName}。
2. 授课科目与内容：详见本合同第三条「教学方案」。
3. 首次上课日期：${stripSep(firstLessonDate) || '由双方另行协商确定'}。
4. 授课时间：${stripSep(schedule) || '由双方另行协商确定'}。
5. 授课地点：${locationText}。

## 第二条 课时费与支付

1. 约定时薪为每小时 **${rate}** 元（人民币）。
2. 薪资结算方式：${payText}。甲方应按约定如期支付课时费用。
3. 试课薪资方案：${trialText}。
4. 平台仅提供信息撮合与合同存证服务，不参与任何费用结算，不代收、不代付课时费用。课时费由双方在站外自行协商并直接结算（如微信、支付宝转账等），平台不对站外资金往来承担任何责任。

## 第三条 教学方案

${stripSep(plan) || '（未填写）'}`;
  return contractWithLegal(biz);
}

// ============================================================
// Ledger chain (contract_ledger): hash-chain evidence of signed bodies.
// ============================================================
const sha256Hex = text => crypto.subtle.digest('SHA-256', new TextEncoder().encode(text)).then(bufToHex);

// Chain hash material must cover body + contract_id + created_at + prev_hash, otherwise a DB
// writer could rebuild the whole ledger undetected. The body hash is taken first (avoid
// re-hashing a long body), then chained with the metadata.
async function ledgerContentHash(contractId, contractMd, createdAt, prevHash) {
  const bodyHash = await sha256Hex(contractMd);
  return sha256Hex(`${bodyHash}|${contractId}|${createdAt}|${prevHash}`);
}

// Record a signed body onto the chain: prev/seq are filtered per contract (each contract is an
// independent chain rooted at GENESIS). The prev read, seq allocation and insert happen in a
// single conditional INSERT — a concurrent fork (prev changed in DB) lands changes=0, retried
// after re-reading. Idempotent: same contract + same body hash returns the existing hash
// (a retry after a signed-then-500 may safely backfill without double-linking).
// Idempotency key = contract_id + body_hash (time-decoupled; content_hash contains a second-level
// createdAt, so it cannot be the dedup key across seconds).
export async function ledgerRecord(db, contractId, contractMd) {
  const target = getLedgerDb(db);
  const bodyHash = await sha256Hex(contractMd);
  const createdAt = toDbTime();
  for (let i = 0; i < 3; i++) {
    const prev = await dbGet(target, 'SELECT content_hash FROM contract_ledger WHERE contract_id=? ORDER BY id DESC LIMIT 1', [contractId]);
    const prevHash = prev ? prev.content_hash : 'GENESIS';
    const contentHash = await ledgerContentHash(contractId, contractMd, createdAt, prevHash);
    const r = await dbRun(target, `INSERT INTO contract_ledger (contract_id, content_hash, prev_hash, seq, body_hash, created_at)
      SELECT ?, ?, COALESCE((SELECT content_hash FROM contract_ledger WHERE contract_id=? ORDER BY id DESC LIMIT 1),'GENESIS'),
             COALESCE((SELECT MAX(seq) FROM contract_ledger WHERE contract_id=?),0)+1, ?, ?
      WHERE COALESCE((SELECT content_hash FROM contract_ledger WHERE contract_id=? ORDER BY id DESC LIMIT 1),'GENESIS') = ?
        AND NOT EXISTS (SELECT 1 FROM contract_ledger WHERE contract_id=? AND body_hash=?)`,
      [contractId, contentHash, contractId, contractId, bodyHash, createdAt, contractId, prevHash, contractId, bodyHash]);
    if (r.meta.changes > 0) return contentHash;
    // changes=0: either a lost chain-tail race or an existing entry — if the same body was already
    // recorded, return its existing hash (latest row).
    const dup = await dbGet(target, 'SELECT content_hash FROM contract_ledger WHERE contract_id=? AND body_hash=? ORDER BY id DESC LIMIT 1', [contractId, bodyHash]);
    if (dup) return dup.content_hash;
  }
  throw new Error('ledger insert retry exhausted'); // 3 failed tail races: fail the request, never silently break the chain
}

// Walk the whole chain: GENESIS head + adjacent prev_hash continuity + monotonic seq.
// Historical bodies are not in the DB (a contract may be edited across versions) — tampering with
// any historical content_hash breaks the link to the next entry's prev_hash. The latest body can
// be replayed when opts carry the current body; revoked (archived) contracts do structure-only
// validation (no body to replay).
export async function verifyChain(rows, opts = {}) {
  const headValid = rows.length ? rows[0].prev_hash === 'GENESIS' : false;
  let linksValid = true, seqValid = true;
  for (let i = 1; i < rows.length; i++) {
    if (rows[i].prev_hash !== rows[i - 1].content_hash) linksValid = false;
    if (rows[i].seq != null && rows[i - 1].seq != null && rows[i].seq !== rows[i - 1].seq + 1) seqValid = false;
  }
  let lastRehashValid = null;
  if (rows.length && !opts.archived && opts.contractId != null && opts.contractMd != null) {
    const last = rows[rows.length - 1];
    lastRehashValid = (await ledgerContentHash(opts.contractId, opts.contractMd, last.created_at, last.prev_hash)) === last.content_hash;
  }
  return { headValid, linksValid, seqValid, lastRehashValid, ok: headValid && linksValid && seqValid };
}

// Verify a contract's ledger: full chain walk + latest body replay. A revoked contract row keeps
// its ledger; the response reports archived=true and does structure-only validation.
export async function verifyContractLedger(db, contractId) {
  const rows = await dbAll(getLedgerDb(db),
    'SELECT id, contract_id, content_hash, prev_hash, seq, body_hash, created_at FROM contract_ledger WHERE contract_id=? ORDER BY id ASC', [contractId]);
  if (!rows.length) return { recorded: false };
  const ct = await dbGetContractById(db, contractId);
  const archived = !ct;
  const chain = await verifyChain(rows, archived ? {} : { contractId, contractMd: ct.contract_md });
  const last = rows[rows.length - 1];
  return {
    recorded: true, archived,
    valid: chain.ok && chain.lastRehashValid !== false, // archived: no body to replay (lastRehashValid=null), structure only
    entries: rows.length, headValid: chain.headValid, linksValid: chain.linksValid, seqValid: chain.seqValid,
    contentHash: last.content_hash, prevHash: last.prev_hash, createdAt: last.created_at,
    entryList: rows.map(r => ({ seq: r.seq, createdAt: r.created_at })),
  };
}

// ---- Party determination helpers ----
// These operate on the contract's own tuple (student_user_id / teacher_user_id) — conversation_id
// is nullable and a conversation may be deleted, so the contract row itself must decide who may
// operate. The same helper also works on conversation rows (they share the tuple shape).
export const isParticipant = (ct, userId) => !!ct && (ct.student_user_id === userId || ct.teacher_user_id === userId);
export const otherSide = (ct, userId) => userId === ct.student_user_id ? ct.teacher_user_id : ct.student_user_id;
// conv is only used for display names (notifications); null-safe because conversation_id is nullable.
export const nameOf = (conv, userId) => conv ? (userId === conv.student_user_id ? conv.student_name : conv.teacher_name) : '';

// Shared gate for contract operations: load row (404) -> status whitelist (409) -> participant
// check on the contract tuple (403). conv is fetched only as a naming/lifecycle source and may be
// null when the conversation is gone. Failures return { err: Response }; callers return g.err.
export async function loadContractFor(db, contractId, userId, statuses) {
  const ct = await dbGetContractById(db, contractId);
  if (!ct) return { err: errorMsg('CONTRACT_NOT_FOUND', 404) };
  if (!statuses.includes(ct.status)) return { err: errorMsg('CONTRACT_STATE_INVALID', 409) };
  if (!isParticipant(ct, userId)) return { err: errorMsg('NO_PERMISSION', 403) };
  const conv = ct.conversation_id ? await dbGetConversationWithNames(db, ct.conversation_id) : null;
  return { ct, conv };
}

// ---- Routes ----

// POST /api/contracts { conversationId, method, plan, rate, schedule, location, payMethod, ... }
// Draft a new standalone contract and send it to the other party. Full self-contained INSERT —
// no demand gate, no stage promotion, no conversation mutation. Requires capToken.
export async function handleCreateContract(db, body, req) {
  const { user: me, err: authErr } = await requireUser(db, req);
  if (authErr) return authErr;
  const userId = me.id;
  const conversationId = parseInt(body.conversationId, 10);
  // AF-5: illegal conversationId (parseInt(null)=NaN) must never reach D1 binding
  if (!Number.isInteger(conversationId) || conversationId <= 0) return errorMsg('INVALID_PARAMS', 404);
  const conv = await dbGetConversationWithNames(db, conversationId);
  if (!isParticipant(conv, userId)) return errorMsg('NO_PERMISSION', 403);
  // Closed conversations are read-only for both parties (no drafting)
  if (conv.status !== STATUS.ACTIVE) return errorMsg('NO_PERMISSION', 403);

  // Teacher acceptance eligibility (chsi verification + profile completeness) — checked on the
  // conversation's teacher (the drafter may be either party).
  const teacherId = me.role === 'teacher' ? userId : conv.teacher_user_id;
  const tProf = await dbGetTeacherProfile(db, teacherId);
  const el = acceptEligibility(tProf);
  if (!el.ok) {
    const key = el.reason === 'CHSI_UNVERIFIED' ? 'CHSI_VERIFY_REQUIRED' : 'PROFILE_COMPLETE_REQUIRED';
    return errorMsg(key, 403, el.reason || undefined);
  }

  // Drafting commits binding terms — dangerous operation, requires a fresh capToken
  if (!(await confirmDangerOtp(db, req, body))) return errorMsg('REAUTH_FAILED', 403);

  const method = body.method === 'offline' ? 'offline' : 'online';
  const plan = String(body.plan || '').slice(0, LIMITS.CONTRACT_PLAN_MAX);
  const rate = Math.min(LIMITS.BUDGET_MAX, Math.max(0, parseInt(body.rate) || 0)); // hourly rate clamped to BUDGET_MAX
  const schedule = String(body.schedule || '').slice(0, LIMITS.CONTRACT_SCHEDULE_MAX);
  const location = String(body.location || '').slice(0, LIMITS.CONTRACT_LOCATION_MAX);
  // Pay/trial three-element sets: whitelist enums + "other" free text; first lesson date yyyy-mm-dd
  const payMethod = ['per_session', 'weekly', 'monthly', 'other'].includes(body.payMethod) ? body.payMethod : '';
  const payMethodOther = payMethod === 'other' ? String(body.payMethodOther || '').trim().slice(0, LIMITS.PAY_OTHER_MAX) : '';
  if (payMethod === 'other' && !payMethodOther) return errorMsg('INVALID_PARAMS', 400);
  const firstLessonDate = /^\d{4}-\d{2}-\d{2}$/.test(String(body.firstLessonDate || '')) ? body.firstLessonDate : '';
  const trialPay = ['first_free', 'first_hour_free', 'normal', 'other'].includes(body.trialPay) ? body.trialPay : '';
  const trialPayOther = trialPay === 'other' ? String(body.trialPayOther || '').trim().slice(0, LIMITS.PAY_OTHER_MAX) : '';
  if (trialPay === 'other' && !trialPayOther) return errorMsg('INVALID_PARAMS', 400);

  const md = buildContractMd({
    teacherName: conv.teacher_name, studentName: conv.student_name,
    method, schedule, location, plan, rate, createdAt: new Date().toISOString().slice(0, 10),
    payMethod, payMethodOther, firstLessonDate, trialPay, trialPayOther,
  });
  const mdEnc = await encryptField(md); // contract body encrypted at rest (repo decrypts on read)
  // Independent contract row: full self-contained insert, no demand gate / no stage / no fallback
  const id = await dbCreateContract(db, {
    conversationId, studentUserId: conv.student_user_id, teacherUserId: conv.teacher_user_id,
    drafterUserId: userId, method, plan, rate, schedule, location,
    payMethod, payMethodOther, firstLessonDate, trialPay, trialPayOther,
    contractMd: mdEnc,
  });
  // Persist the body including the (all-pending) signature block
  const fullMd = md + buildSignatureBlock({
    studentName: conv.student_name, teacherName: conv.teacher_name,
    studentSignedAt: '', teacherSignedAt: '', contractId: id,
  });
  await dbSetContractMd(db, id, await encryptField(fullMd));
  // Contract event bubble visible to both parties in the conversation
  await dbCreateMessage(db, conversationId, userId, 'contract', 'contract_draft');
  await notifyUser(db, otherSide(conv, userId), 'CONTRACT_DRAFT_SENT', { name: nameOf(conv, userId) });
  await logEvent(db, { action: 'contract.create', actorUserId: userId, entity: 'contract', entityId: id,
    detail: { conversationId, method, rate }, req });
  return json({ id, message: UIC.CONTRACT_DRAFT_SENT_TOAST }, 201);
}

// GET /api/contracts -> { contracts } (my contracts, both roles)
export async function handleGetMyContracts(db, url, req) {
  const { user: me, err } = await requireUser(db, req);
  if (err) return err;
  return json({ contracts: await dbGetMyContracts(db, me.id) });
}

// GET /api/contracts/:id -> { contract } (participants and admin only)
export async function handleGetContractById(db, contractId, req) {
  const { user: me, err } = await requireUser(db, req);
  if (err) return err;
  const ct = await dbGetContractById(db, contractId);
  if (!ct) return errorMsg('CONTRACT_NOT_FOUND', 404);
  const isAdmin = requireAdminOrError(me) === null;
  if (!isAdmin && !isParticipant(ct, me.id)) return errorMsg('NO_PERMISSION', 403);
  return json({ contract: ct });
}

// POST /api/contracts/:id/sign — confirm signing; both confirmations move status -> signed.
// SIGNED is accepted so a retry after a signed-then-ledger-failure can idempotently backfill.
export async function handleSignContract(db, contractId, body, req) {
  const { user: me, err: authErr } = await requireUser(db, req);
  if (authErr) return authErr;
  const userId = me.id;
  const g = await loadContractFor(db, contractId, userId, [CONTRACT_STATUS.SIGNING, CONTRACT_STATUS.SIGNED]);
  if (g.err) return g.err;
  const { ct, conv } = g;
  // Lifecycle gate: a closed/deleted conversation forbids contract writes; retained evidence stays
  if (!conv || conv.status !== STATUS.ACTIVE) return errorMsg('CONVERSATION_CLOSED', 403);
  // Revoked contracts (status still 'signed') reject any further sign — checked before capToken
  // consumption so a stale one-time code is not spent.
  if (ct.revoked) return errorMsg('CONTRACT_ALREADY_REVOKED', 409);
  // Dangerous operation (binding transaction): fresh capToken required
  if (!(await confirmDangerOtp(db, req, body))) return errorMsg('REAUTH_FAILED', 403);

  const col = userId === ct.drafter_user_id ? 'drafter_confirmed' : 'other_confirmed';
  const signedCol = userId === ct.drafter_user_id ? 'drafter_signed_at' : 'other_signed_at';
  // Conditional UPDATE + changes winner: the status guard means a contract already cancelled or
  // signed produces no change; the changes=0 side reloads and returns idempotently. version bumps.
  const flag = await dbRun(db, `UPDATE contracts SET ${col}=1, ${signedCol}=datetime('now'), contract_status='signing', version=version+1, updated_at=datetime('now') WHERE id=? AND contract_status IN ('signing')`, [contractId]);
  if (!(flag && flag.meta && flag.meta.changes > 0)) {
    const cur = await loadContractFor(db, contractId, userId, [CONTRACT_STATUS.SIGNING, CONTRACT_STATUS.SIGNED]);
    if (cur.err) return cur.err;
    // Previous round already signed but the ledger write failed (500): idempotent backfill
    if (cur.ct.status === CONTRACT_STATUS.SIGNED) {
      try { await ledgerRecord(db, contractId, cur.ct.contract_md); }
      catch (e) { console.error('contract ledger backfill failed:', e && e.message); }
    }
    return json({ ok: true, signed: cur.ct.status === CONTRACT_STATUS.SIGNED });
  }
  const updated = await dbGetContractById(db, contractId);
  if (!updated) return errorMsg('CONTRACT_NOT_FOUND', 404); // concurrent revoke removed the row: clean 404
  const both = !!(updated.drafter_confirmed && updated.other_confirmed);
  // Rebuild the signature block (names + timestamps) and write back with a version optimistic lock —
  // under concurrent double-sign only the last landing body wins (stale body changes=0 discarded).
  const signedMd = rebuildFullMd(updated, conv);
  const mdUpdate = await dbRun(db, `UPDATE contracts SET contract_md=?, version=version+1 WHERE id=? AND version=?`,
    [await encryptField(signedMd), contractId, updated.version]);
  // Loser of the double-sign race: skip ledger/notify/log (the winner already recorded)
  if (!(mdUpdate && mdUpdate.meta && mdUpdate.meta.changes > 0)) {
    return json({ ok: false, signed: false });
  }
  // Every sign records the ledger: body embeds who/when, content_hash covers it; idempotent
  // (same body NOT EXISTS) so concurrent double-sign appends one entry and retries backfill safely.
  let contentHash = '';
  try { contentHash = await ledgerRecord(db, contractId, signedMd); }
  catch (e) {
    // Ledger failure must neither 500 (deadlock on a both-confirmed signing) nor be silent — the
    // gap is exposed via the verify panel (recorded=false) and a ledgerFailed audit flag; retry
    // goes through the SIGNED backfill branch above.
    console.error('contract ledger failed:', e && e.message);
    contentHash = '';
  }
  if (both) {
    // Conditional winner: only one side's claim changes>0, preventing duplicate notifications
    const claim = await dbRun(db, `UPDATE contracts SET contract_status='signed', prev_business=NULL, version=version+1 WHERE id=? AND contract_status='signing'`, [contractId]);
    if (claim && claim.meta && claim.meta.changes > 0) {
      await notifyUser(db, otherSide(conv, userId), 'CONTRACT_SIGNED', {});
      // Audit saves the signed body (detailMax widened, encrypted) — retained even after revoke
      await logEvent(db, { action: 'contract.signed', actorUserId: userId, entity: 'contract', entityId: contractId,
        detail: { conversationId: updated.conversation_id, contentHash,
          ...(contentHash ? {} : { ledgerFailed: true }), contractMd: signedMd },
        detailMax: 60000, req });
    }
  } else {
    await notifyUser(db, otherSide(conv, userId), 'CONTRACT_SIGN_WAITING', { name: nameOf(conv, userId) });
    await logEvent(db, { action: 'contract.sign_partial', actorUserId: userId, entity: 'contract', entityId: contractId,
      detail: { signedBy: userId, contentHash, ...(contentHash ? {} : { ledgerFailed: true }), contractMd: signedMd }, detailMax: 60000, req });
  }
  return json({ ok: true, signed: both });
}

// PUT /api/contracts/:id { contractMd, version } — edit the contract: reset both confirmations,
// sync the other party in real time. Optimistic lock on the integer version; version mismatch or
// status left 'signing' -> 409 forces a client reload.
export async function handleModifyContract(db, contractId, body, req) {
  const { user: me, err: authErr } = await requireUser(db, req);
  if (authErr) return authErr;
  const userId = me.id;
  const g = await loadContractFor(db, contractId, userId, [CONTRACT_STATUS.SIGNING]);
  if (g.err) return g.err;
  const { ct, conv } = g;
  // Lifecycle gate: closed relationship forbids edits (historical evidence retained)
  if (!conv || conv.status !== STATUS.ACTIVE) return errorMsg('CONVERSATION_CLOSED', 403);
  // A party that already confirmed cannot edit (editing resets both confirmations = withdrawing
  // one's own commitment). The unconfirmed party may still edit after the other signed.
  const myConfirmed = userId === ct.drafter_user_id ? !!ct.drafter_confirmed : !!ct.other_confirmed;
  if (myConfirmed) return errorMsg('CONTRACT_LOCKED_AFTER_SIGN', 409);
  const ver = parseInt(body.version);
  if (!Number.isInteger(ver)) return errorMsg('INVALID_PARAMS', 400);
  // The edit modal only exposes the business section — the legal section is re-appended server-side.
  // Strip any residual marker and trailing content (defense against full-body / duplicate submits).
  const md = String(body.contractMd || '').slice(0, LIMITS.CONTRACT_MD_MAX).split(CONTRACT_BUSINESS_END)[0].trim();
  if (!md) return error(UIC.CONTRACT_EMPTY, 400, 'CONTRACT_EMPTY');
  // Old-format contracts (no marker): the whole body is business — do not append a legal block,
  // otherwise the old legal text would be treated as business and duplicated.
  const oldHasMarker = (ct.contract_md || '').includes(CONTRACT_BUSINESS_END);
  const oldBiz = (oldHasMarker ? (ct.contract_md || '').split(CONTRACT_BUSINESS_END)[0] : (ct.contract_md || '')).trim();
  if (md === oldBiz) return json({ ok: true, unchanged: true }); // business unchanged: no reset, no re-notify
  // New format: business + legal + signature block (all pending — edit rolls back the sign choice);
  // old format: keep verbatim (no marker -> no signature block, historical semantics intact)
  const fullMd = oldHasMarker
    ? contractWithLegal(md) + buildSignatureBlock({
        studentName: conv.student_name, teacherName: conv.teacher_name,
        studentSignedAt: '', teacherSignedAt: '', contractId,
      })
    : md;

  // Edit returns to the signing-selection state: both confirmations + signed timestamps cleared,
  // prev_business keeps the diff baseline; optimistic lock lands in SQL WHERE (exact version)
  const upd = await dbRun(db,
    `UPDATE contracts SET contract_md=?, prev_business=?, drafter_confirmed=0, other_confirmed=0,
       drafter_signed_at='', other_signed_at='', contract_status='signing', version=version+1, updated_at=datetime('now')
     WHERE id=? AND version=? AND contract_status IN ('signing')`,
    [await encryptField(fullMd), await encryptField(oldBiz), contractId, ver]);
  if (!(upd && upd.meta && upd.meta.changes > 0)) return errorMsg('CONTRACT_MODIFIED_CONFLICT', 409, 'CONTRACT_MODIFIED_CONFLICT');
  await notifyUser(db, otherSide(conv, userId), 'CONTRACT_MODIFIED', { name: nameOf(conv, userId) });
  await logEvent(db, { action: 'contract.modify', actorUserId: userId, entity: 'contract', entityId: contractId, req });
  return json({ ok: true });
}

// POST /api/contracts/:id/revoke — revoke a signed contract (mutually agreed termination only):
// the row is kept with revoked=1 (evidence retained), the ledger and encrypted audit stay.
export async function handleRevokeContract(db, contractId, body, req) {
  const { user: me, err: authErr } = await requireUser(db, req);
  if (authErr) return authErr;
  const g = await loadContractFor(db, contractId, me.id, [CONTRACT_STATUS.SIGNED]); // unsigned goes through cancel
  if (g.err) return g.err;
  const { ct, conv } = g;
  // Lifecycle gate: closing the relationship first forbids revoke (must revoke before closing)
  if (!conv || conv.status !== STATUS.ACTIVE) return errorMsg('CONVERSATION_CLOSED', 403);
  if (ct.revoked) return errorMsg('CONTRACT_ALREADY_REVOKED', 409); // idempotent rejection
  if (!(await confirmDangerOtp(db, req, body))) return errorMsg('REAUTH_FAILED', 403); // dangerous operation
  // Revoke marks the row (does not delete): body + ledger retained for evidence; conditional
  // UPDATE so only one of two concurrent revokers runs the side effects.
  const upd = await dbRun(db,
    `UPDATE contracts SET revoked=1, revoked_by=?, contract_status='signed', version=version+1, updated_at=datetime('now')
     WHERE id=? AND revoked=0`, [me.id, contractId]);
  if (!(upd && upd.meta && upd.meta.changes > 0)) {
    const cur = await dbGetContractById(db, contractId);
    if (cur && cur.revoked) return errorMsg('CONTRACT_ALREADY_REVOKED', 409); // concurrent revoke
    return errorMsg('CONTRACT_NOT_FOUND', 404);
  }
  await notifyUser(db, otherSide(conv, me.id), 'CONTRACT_REVOKED', { name: nameOf(conv, me.id) });
  await logEvent(db, { action: 'contract.revoke', actorUserId: me.id, entity: 'contract', entityId: contractId,
    detail: { conversationId: ct.conversation_id, note: 'contract_retained' }, req });
  return json({ ok: true });
}

// GET /api/contracts/:id/verify — ledger verification: rehash the text against the chain.
// Read-only evidence check, exempt from the lifecycle gate (historical evidence stays verifiable
// after the relationship is closed). Participants and admin only (tuple-based).
export async function handleVerifyContract(db, contractId, req) {
  const { user: me, err: authErr } = await requireUser(db, req);
  if (authErr) return authErr;
  const ct = await dbGetContractById(db, contractId);
  if (!ct) return errorMsg('CONTRACT_NOT_FOUND', 404);
  const isAdmin = requireAdminOrError(me) === null;
  if (!isAdmin && !isParticipant(ct, me.id)) return errorMsg('NO_PERMISSION', 403);
  return json(await verifyContractLedger(db, contractId));
}

// GET /api/admin/contracts — admin view of all contracts
export async function handleAdminListContracts(db, url, req) {
  const { err } = await requireAdmin(db, req);
  if (err) return err;
  const contracts = await dbGetAllContractsAdmin(db);
  return json({ contracts });
}

// DELETE /api/admin/contracts/:id — admin remove (backoffice/test; full audit trail kept, removal
// logged as admin.contract.remove). Dangerous operation: capToken required.
export async function handleAdminRemoveContract(db, contractId, body, req) {
  const { admin, err } = await requireAdmin(db, req);
  if (err) return err;
  const ct = await dbGetContractById(db, contractId);
  if (!ct) return errorMsg('CONTRACT_NOT_FOUND', 404);
  if (!(await confirmDangerOtp(db, req, body))) return errorMsg('REAUTH_FAILED', 403);
  await dbDeleteContract(db, contractId);
  await logEvent(db, { action: 'admin.contract.remove', actorUserId: admin.id, actorUsername: admin.username,
    actorRole: 'admin', entity: 'contract', entityId: contractId,
    detail: { conversationId: ct.conversation_id, status: ct.status, drafterUserId: ct.drafter_user_id }, req });
  return json({ ok: true });
}

// DELETE /api/contracts/:id — cancel signing (row kept, never deleted):
//   ① my side signed, other not: cancel rolls my side back to signing (clear my confirmed +
//      signed_at), the contract stays clean and can be re-signed.
//   ② both signed: rejected (409) — that path is POST /api/contracts/:id/revoke.
// Cancellation always rolls status back to 'signing' ('pending' was the legacy draft-confirmation
// state; new contracts are created directly as 'signing').
export async function handleCancelContract(db, contractId, body, req) {
  const { user: me, err: authErr } = await requireUser(db, req);
  if (authErr) return authErr;
  const userId = me.id;
  const g = await loadContractFor(db, contractId, userId, [CONTRACT_STATUS.SIGNING]);
  if (g.err) return g.err;
  const { ct, conv } = g;
  // Lifecycle gate: closed relationship forbids cancelling a signing
  if (!conv || conv.status !== STATUS.ACTIVE) return errorMsg('CONVERSATION_CLOSED', 403);
  // Dangerous operation (withdrawing a signing commitment): capToken required
  if (!(await confirmDangerOtp(db, req, body))) return errorMsg('REAUTH_FAILED', 403);

  const myCol = userId === ct.drafter_user_id ? 'drafter_confirmed' : 'other_confirmed';
  const theirCol = userId === ct.drafter_user_id ? 'other_confirmed' : 'drafter_confirmed';
  const mySigned = userId === ct.drafter_user_id ? !!ct.drafter_confirmed : !!ct.other_confirmed;
  const bothSigned = mySigned && (!!ct[theirCol]);
  if (bothSigned) return errorMsg('CONTRACT_CANCEL_SIGNED_BLOCKED', 409); // both signed: use revoke

  // Conditional UPDATE concurrent guard: AND current status; the changes=0 side reloads and
  // returns idempotently (no side effects when the other side concurrently signed/changed state).
  // Rolls back my confirmation + signed_at, status -> 'signing' (clean "await my sign" state).
  const upd = await dbRun(db,
    `UPDATE contracts SET ${myCol}=0,
        ${userId === ct.drafter_user_id ? "drafter_signed_at=''" : "other_signed_at=''"},
        contract_status='signing', version=version+1, updated_at=datetime('now')
     WHERE id=? AND contract_status IN ('signing')`, [contractId]);
  if (!(upd && upd.meta && upd.meta.changes > 0)) {
    const cur = await dbGetContractById(db, contractId);
    if (cur && cur.status === CONTRACT_STATUS.SIGNED && !cur.revoked) return errorMsg('CONTRACT_CANCEL_SIGNED_BLOCKED', 409);
    return json({ ok: true }); // concurrent cancel: idempotent
  }
  // Rebuild the signature block reflecting my rolled-back sign state; version optimistic lock
  // with at most two rounds (a concurrent edit mid-rebuild is re-read and re-built once).
  let curCt = await dbGetContractById(db, contractId);
  if (curCt && curCt.status === CONTRACT_STATUS.SIGNING) {
    for (let i = 0; i < 2; i++) {
      const mdUpd = await dbRun(db, `UPDATE contracts SET contract_md=?, version=version+1 WHERE id=? AND version=?`,
        [await encryptField(rebuildFullMd(curCt, conv)), contractId, curCt.version]);
      if (mdUpd && mdUpd.meta && mdUpd.meta.changes > 0) break;
      curCt = await dbGetContractById(db, contractId); // concurrent advance: re-read latest version
      if (!curCt || curCt.status !== CONTRACT_STATUS.SIGNING) break;
    }
  }
  await notifyUser(db, otherSide(conv, userId), 'CONTRACT_CANCELLED', { name: nameOf(conv, userId) });
  await logEvent(db, { action: 'contract.cancel', actorUserId: userId, entity: 'contract', entityId: contractId,
    detail: { conversationId: ct.conversation_id, rollbackTo: 'signing' }, req });
  return json({ ok: true });
}

// ============================================================
// contract domain route table (S5-14: aligned to interfaces I-44/45/46)
// ============================================================
const S = (method, path, handler) => ({ method, path, handler });
export const routes = [
  S('GET', '/api/contracts', c => handleGetMyContracts(c.db, c.url, c.req)),
  S('GET', '/api/contracts/:id', c => handleGetContractById(c.db, parseIdParam(c.params.id), c.req)),
  S('POST', '/api/contracts', c => handleCreateContract(c.db, c.body, c.req)),
  S('POST', '/api/contracts/:id/sign', c => handleSignContract(c.db, parseIdParam(c.params.id), c.body, c.req)),
  S('POST', '/api/contracts/:id/revoke', c => handleRevokeContract(c.db, parseIdParam(c.params.id), c.body, c.req)),
  S('PUT', '/api/contracts/:id', c => handleModifyContract(c.db, parseIdParam(c.params.id), c.body, c.req)),
  S('DELETE', '/api/contracts/:id', c => handleCancelContract(c.db, parseIdParam(c.params.id), c.body, c.req)),
  S('GET', '/api/contracts/:id/verify', c => handleVerifyContract(c.db, parseIdParam(c.params.id), c.req)),
  S('GET', '/api/admin/contracts', c => handleAdminListContracts(c.db, c.url, c.req)),
  S('DELETE', '/api/admin/contracts/:id', c => handleAdminRemoveContract(c.db, parseIdParam(c.params.id), c.body, c.req)),
];
