/**
 * teacher feature user-facing text (copied verbatim from root constants.js UI).
 */

export const TEXT = {
  A11Y_VIEW_PROFILE: '查看该用户资料',
  AWARD_COUNT_BADGE: '🏆 荣誉 ×{n}',
  AWARD_SECTION_TITLE: '荣誉奖项',
  BTN_APPROVE: '通过',
  BTN_CANCEL: '取消',
  BTN_DELETE_REVIEW: '删除评价',
  BTN_EDIT_REVIEW: '修改评价',
  BTN_REJECT: '拒绝',
  BTN_SAVE_DEMAND: '保存修改',
  BTN_SUBMIT_REVIEW: '提交评价',
  BTN_WRITE_REVIEW: '写评价',
  CONFIRM_DELETE_REVIEW: '删除后不可恢复。确定要删除这条评价吗？',
  CONTACT_AFTER_SIGN_NOTE: '签约后展示联系方式',
  CREDENTIAL_VIEW: '点击查看',
  EMPTY_NO_REVIEWS: '还没有人写下评价。与该教师完成签约后，学生可以分享真实的上课体验。',
  EMPTY_NO_TEACHERS: '还没有老师入驻。如果你是教师，完善档案后会出现在这里；学生也可以先发布需求，匹配的老师会主动联系你。',
  ERROR_LOAD_PREFIX: '加载失败: ',
  LABEL_ADDRESS: '地址（授课区域）',
  LABEL_CONTACT: '联系方式',
  LABEL_CREDENTIAL: '学信网截图',
  LABEL_EMAIL: '邮箱',
  LABEL_GAOKAO_SCORES: '高考成绩',
  LABEL_GENDER: '性别',
  LABEL_GRADE: '年级',
  LABEL_GRADUATION_YEAR: '毕业年份',
  LABEL_INTRO: '简介',
  LABEL_NONACADEMIC_PROJECTS: '擅长非学科类项目',
  LABEL_PERSONALITY_TAGS: '性格关键词',
  LABEL_PRICE: '报价',
  LABEL_RATING: '评分',
  LABEL_REAL_NAME: '真实姓名',
  LABEL_REVIEW_CONTENT: '评价内容',
  LABEL_SCHOOL: '学校',
  LABEL_TEACHING_METHOD_PROFILE: '授课方式',
  LABEL_TIME_SLOTS: '可授课时间段',
  LABEL_WECHAT: '微信',
  MATCH_TEACHER_DETAIL_SUB: '根据你的活跃需求与该教师档案自动计算，按匹配度从高到低展示',
  MATCH_T_BRACKET_L: '【',
  MATCH_T_BRACKET_R: '】',
  MATCH_T_DEMAND_PREFIX: '需求',
  MATCH_T_PCT: '匹配度：',
  MATCH_T_TITLE: '教师匹配度明细',
  MY_REVIEW_PREFIX: '你的评价：',
  PRICE_UNIT: '元/h',
  PROFILE_EMPTY_TEACHER: '这位老师还没有填写资料',
  PROFILE_FIELD_AFTER_MATCH: '建立会话后展示',
  PROFILE_FIELD_EMPTY: '未填写',
  PROFILE_PANEL_TITLE: '个人信息',
  PROFILE_SECTION_ACADEMIC: '学科类资料',
  PROFILE_SECTION_BASIC: '基本资料',
  PROFILE_SECTION_NONACADEMIC: '非学科类资料',
  PROFILE_SECTION_PRIVATE: '私密资料',
  PROFILE_SIGNED_TAG: '已签约',
  REVIEW_COMMENT_PLACEHOLDER: '请分享你的体验...',
  REVIEW_DELETED: '评价已删除',
  REVIEW_LOCKED_HINT: '与这位老师签约后，即可写下你的评价',
  REVIEW_MODAL_TITLE_PREFIX: '评价 ',
  REVIEW_REJECTED_HINT: '未通过，可修改后重新提交',
  REVIEW_STATUS_AUDITING: '审核中',
  SECTION_REGION: '地区',
  SECTION_REVIEWS: '评价',
  SECTION_SUBJECTS: '擅长科目',
  STATUS_APPROVED: '已通过',
  SUCCESS_APPROVED: '已通过',
  SUCCESS_REJECTED: '已拒绝',
  SUCCESS_REVIEW_SUBMITTED: '评价已提交，等待管理员审核',
  TAG_MATCH: '匹配度 ',
  TAG_MATCH_HINT: ' · 点击展开明细',
  TAG_MATCH_NO_DEMAND: '发布需求后展示匹配度',
  TAG_MATCH_TITLE: '点击查看匹配度明细',
  TEACHER_SORT_MATCH: '匹配度最高',
  TEACHER_SORT_PRICE: '报价最低',
  TEACHER_SORT_RATING: '评分最高',
  VALIDATE_COMMENT_TOO_SHORT: '评价内容太短',
  VALIDATE_SELECT_RATING: '请选择评分',
  VERIFIED_BADGE: '✓ 已认证',
  VERIFIED_TITLE: '已通过学籍认证',
  PAGE_BROWSE_TEACHERS: '浏览教师',
  PAGE_BROWSE_TEACHERS_DESC: '筛选教师，查看详情与评价',
  PAGE_BROWSE_TEACHERS_PEER_DESC: '查看同行的信息与评价',
};
