/**
 * notif feature user-facing text. Broadcast classification + structured
 * notification templates are behavioral constants (shared by core/notif-pref.js,
 * the list filter and the badge filter must agree on one source) -- derived from
 * constants/text.js rather than re-declared here (audit F4: no second copy).
 */
import { TEXT as SHARED } from '../../constants/text.js';

export const TEXT = {
  PAGE_NOTIFICATIONS: '通知信息',
  PAGE_NOTIFICATIONS_DESC: '意向与推送的处理进展',
  NOTIFY_BROADCAST_PREFIX: SHARED.NOTIFY_BROADCAST_PREFIX,
  NOTIF_BLOCK_OFF: '屏蔽系统通知',
  NOTIF_BLOCK_ON: '已屏蔽系统通知',
  NOTIF_FILTER_EMPTY: '没有符合条件的通知',
  EMPTY_NO_NOTIFICATIONS: '还没有通知。试课意向、需求推送和合同进展都会汇总到这里。',
  NOTIF_READ_ARIA: '标记该条通知已读',
  // V-2-4 structured notification templates (single source: constants/text.js)
  NOTIF_INTENT_ACCEPTED: SHARED.NOTIF_INTENT_ACCEPTED,
  NOTIF_INTENT_REJECTED: SHARED.NOTIF_INTENT_REJECTED,
  NOTIF_PUSH_ACCEPTED: SHARED.NOTIF_PUSH_ACCEPTED,
  NOTIF_PUSH_REJECTED: SHARED.NOTIF_PUSH_REJECTED,
  NOTIF_SUBJECTS_FALLBACK: SHARED.NOTIF_SUBJECTS_FALLBACK,
  NOTIF_CONTRACT_DRAFT_SENT: SHARED.NOTIF_CONTRACT_DRAFT_SENT,
  NOTIF_CONTRACT_SIGN_WAITING: SHARED.NOTIF_CONTRACT_SIGN_WAITING,
  NOTIF_CONTRACT_MODIFIED: SHARED.NOTIF_CONTRACT_MODIFIED,
  NOTIF_CONTRACT_SIGNED: SHARED.NOTIF_CONTRACT_SIGNED,
  NOTIF_CONTRACT_REVOKED: SHARED.NOTIF_CONTRACT_REVOKED,
  NOTIF_CONTRACT_CANCELLED: SHARED.NOTIF_CONTRACT_CANCELLED,
  NOTIF_SIGNING_REQUEST_SENT: SHARED.NOTIF_SIGNING_REQUEST_SENT,
  NOTIF_SIGNING_CONFIRMED: SHARED.NOTIF_SIGNING_CONFIRMED,
  NOTIF_SIGNING_REJECTED: SHARED.NOTIF_SIGNING_REJECTED,
  NOTIF_FEEDBACK_RESOLVED: SHARED.NOTIF_FEEDBACK_RESOLVED,
  NOTIF_FEEDBACK_COMPLAINT_RESOLVED: SHARED.NOTIF_FEEDBACK_COMPLAINT_RESOLVED,
  NOTIF_VERIFY_APPROVED_ADMISSION: SHARED.NOTIF_VERIFY_APPROVED_ADMISSION,
  NOTIF_VERIFY_APPROVED_CHSI: SHARED.NOTIF_VERIFY_APPROVED_CHSI,
  NOTIF_VERIFY_DETAIL_PREFIX: SHARED.NOTIF_VERIFY_DETAIL_PREFIX,
  NOTIF_VERIFY_REJECTED: SHARED.NOTIF_VERIFY_REJECTED,
  NOTIF_AWARD_APPROVED: SHARED.NOTIF_AWARD_APPROVED,
  NOTIF_AWARD_REJECTED: SHARED.NOTIF_AWARD_REJECTED,
  NOTIF_CONTENT_PENALTY: SHARED.NOTIF_CONTENT_PENALTY,
  NOTIF_CONTENT_PENALTY_SUMMARY: SHARED.NOTIF_CONTENT_PENALTY_SUMMARY,
  NOTIF_PENALTY_ACTION_BAN: SHARED.NOTIF_PENALTY_ACTION_BAN,
  NOTIF_PENALTY_ACTION_REMOVE: SHARED.NOTIF_PENALTY_ACTION_REMOVE,
  NOTIF_RULE_FALLBACK: SHARED.NOTIF_RULE_FALLBACK,
};
