/**
 * Client-visible text single source (v2).
 * Generated from root constants.js UI (parity test asserts sampled keys).
 */
export const TEXT = {
  "NAV_LOGIN": "登录",
  "NAV_REGISTER": "注册",
  "ROLE_STUDENT": "学生",
  "ROLE_TEACHER": "教师",
  "ADMIN_BADGE": "管理员",
  "BTN_LOGIN": "登录",
  "BTN_REGISTER": "注册",
  "BTN_SAVE": "保存",
  "BTN_SUBMIT_DEMAND": "提交需求",
  "BTN_EDIT": "编辑",
  "BTN_SAVE_DEMAND": "保存修改",
  "BTN_DELETE_DEMAND": "删除需求",
  "BTN_DELETE_REVIEW": "删除评价",
  "BTN_REMOVE": "移除",
  "BTN_CONFIRM": "确定",
  "BAN": "封禁",
  "UNBAN": "解封",
  "VERIFY_DONE": "已通过学籍认证",
  "BTN_GENERATE_INVITE": "生成邀请码",
  "BTN_CANCEL": "取消",
  "INTENT_GREET_TITLE": "提交试课意向",
  "INTENT_GREET_DEMAND": "你将向这条需求提交试课意向：{demand}",
  "INTENT_GREET_LABEL": "和对方打个招呼（可选）",
  "INTENT_GREET_PLACEHOLDER": "简单介绍一下自己，说说为什么想接下这单～（例：老师您好，我教初中数学五年，带过三届中考班，对您孩子的分数情况很有把握）",
  "INTENT_GREET_OPTIONAL": "可留空直接提交；填写后学生会在「试课意向」里看到这段话。",
  "GREET_HEAD_STUDENT": "学生留言",
  "GREET_HEAD_TEACHER": "教师留言",
  "BTN_LOAD_MORE": "加载更多",
  "LOADING_LOGIN": "登录中...",
  "LOADING_REGISTER": "注册中...",
  "VALIDATE_PASSWORD": "密码至少 6 个字符",
  "VALIDATE_PASSWORD_MISMATCH": "两次密码不一致",
  "REG_WIZARD_STEPS": [
    "验证邀请码",
    "填写账号信息",
    "验证手机或邮箱"
  ],
  "REG_INVITE_LABEL": "邀请码",
  "REG_INVITE_PLACEHOLDER": "请输入管理员提供的邀请码",
  "REG_INVITE_HINT": "邀请码由管理员发放，一枚邀请码仅限一人使用。没有邀请码请联系平台负责人。",
  "REG_USERNAME_LABEL": "用户名",
  "REG_USERNAME_PLACEHOLDER": "3-30 个字符",
  "REG_PASSWORD_LABEL": "密码",
  "REG_PASSWORD_PLACEHOLDER": "至少 6 个字符",
  "REG_PASSWORD2_LABEL": "确认密码",
  "REG_PASSWORD2_PLACEHOLDER": "再输入一次密码",
  "REG_CONTACT_LABEL": "手机号或邮箱",
  "REG_CONTACT_PLACEHOLDER": "请输入手机号或邮箱",
  "REG_CONTACT_HINT": "绑定手机或邮箱用于登录和找回账号，任选一种即可，需通过验证码验证。",
  "AGREE_PREFIX": "我已阅读并同意",
  "AGREE_LINK_AGREEMENT": "用户协议",
  "AGREE_LINK_PRIVACY": "隐私政策",
  "REGISTER_CONTACT_REQUIRED": "请填写手机号或邮箱并输入验证码",
  "AGREE_REQUIRED": "请先勾选同意用户协议与隐私政策",
  "POLICY_KEY_AGREEMENT": "user_agreement",
  "POLICY_KEY_PRIVACY": "privacy_policy",
  "POLICY_AGREEMENT": "# 经世知途家教信息平台用户协议\n\n**版本更新日期：** 2026年8月8日\n\n**生效日期：** 2026年8月8日\n\n## 一、总则\n\n### 1.1 协议效力与缔约主体\n\n本协议由经世知途家教信息平台运营主体（以下简称“平台方/我们”）与完成注册、登录、使用平台服务的用户（家长、学员、大学生教员，以下简称“用户/您”）自愿缔结，具备合法民事合同法律效力，对双方均具有约束力。\n\n**平台公示信息（上线必填）：**\n\n**平台名称：** 经世知途家教信息平台\n\n**运营主体：** ___________（公司/个体工商户全称）\n\n**统一社会信用代码：** ___________\n\n**住所地：** ___________\n\n**官方联系邮箱：** ___________\n\n**客服投诉入口：** ___________\n\n### 1.2 平台定位\n\n本平台为大学生创业运营的纯信息撮合服务平台，不提供教学授课服务，仅为家长/学员、大学生教员提供家教需求发布、师资展示、信息检索、双向对接的中立信息服务。\n\n### 1.3 核心权责界定（重点）\n\n平台仅为信息展示与对接渠道，不开展资金托管、代收代付、在线结算、担保交易业务。平台不属于家长与教员之间家教服务合同的缔约方，不参与、不组织、不监督、不担保任何线上/线下授课行为与服务履约。\n\n### 1.4 风险告知与同意规则\n\n您确认已主动、完整阅读、理解本协议全部条款，尤其是加粗标注的责任限制、风险提示、免责条款。您完成注册、登录、使用平台服务，即代表自愿接受本协议全部约束；若您不认可本协议任意条款，无权使用本平台任何服务。\n\n### 1.5 格式条款解释规则\n\n本协议为格式合同。若条款存在两种以上合理解释的，依法作出不利于条款提供方（即平台方）的解释；但条款含义清晰明确的，应按通常含义理解。\n\n## 二、平台服务内容与服务边界\n\n### 2.1 仅限信息中介服务\n\n平台提供的全部服务仅限于：\n\n**教员端：** 个人资质、教学经历、授课科目、空闲时段信息发布与展示；\n\n**家长端：** 家教年级、科目、授课地址、期望薪资、授课频率等需求发布；\n\n**双向沟通：** 展示信息、开放沟通渠道，由用户双方自主对接、自主缔约、自主履约。\n\n### 2.2 身份核验规则与风险告知\n\n**1.** 平台对教员在校生身份、学籍证明、校园证件等材料进行形式合规审查，核验通过后展示认证标识，仅证明材料外观合规。\n\n**2.** 平台无公安核查权限、无资质开展背景调查，无法核验教员品行、心理健康、犯罪记录、真实授课水平、过往业绩真实性，亦无法担保家长发布信息的真实性。\n\n**3.** 安全强制提示：涉及未成年人授课场景，家长应当自行核验教员背景（含无犯罪记录证明等），自行承担线下核验义务。\n\n**4.** 用户对交易对象、服务风险承担自主核实义务；因用户自行核实疏忽产生的风险由用户自行承担；平台因故意或重大过失（明知虚假仍认证、收到举报拒不处置）造成用户损失的，依法承担对应过错责任。\n\n### 2.3 无资金交易与无担保规则\n\n平台全程不介入任何资金往来，不收取课时费、不托管资金、不代收代付、不担保履约。课时费标准、支付方式、退款规则、押金约定均由家长与教员自主协商、自行承担。双方资金纠纷、履约纠纷由双方自行解决，平台仅可在合法范围内协助提供备案信息用于维权取证。\n\n## 三、用户注册、账号管理与资质规则\n\n### 3.1 注册资格\n\n**教员用户：** 仅限国内正规高校在读本专科生、研究生、毕业两年内应届生，注册必须提交真实姓名、院校、专业、有效学籍材料与联系方式。\n\n**家长/学员用户：** 需提交真实有效联系方式、真实家教需求信息，禁止虚假占位、恶意发布无效需求。\n\n### 3.2 教员资质到期处置\n\n教员毕业满两年自动丧失教员入驻资质，平台将提前站内信提醒；到期后自动关闭接单、发布师资权限，保留基础浏览权限，用户可自主注销账号。对于协议终止时正在进行的授课订单，用户可与家长协商完成已约定课程或妥善交接，平台给予不少于30日的合理过渡期。\n\n### 3.3 信息真实性义务\n\n所有用户承诺发布信息真实、准确、完整，不得虚构资质、虚构需求、隐瞒关键信息。因虚假信息造成第三方或平台损失的，由发布用户承担全部法律责任。\n\n### 3.4 账号安全责任\n\n**1.** 用户对自有账号全部操作承担全部责任，负有妥善保管密码、设备、验证码的义务，因个人疏忽泄露、转借账号导致的风险自行承担。\n\n**2.** 非因平台安全漏洞导致的黑客攻击、账号异常，平台仅提供协助排查，若平台能够证明已履行法定网络安全保护义务且不存在过错的，依法不承担赔偿责任。\n\n### 3.5 账号唯一性\n\n一人一号，禁止冒用他人身份、批量恶意注册、养号营销，违规账号可予以限制或封禁。\n\n## 四、用户行为规范与禁止行为\n\n### 4.1 禁止虚假与恶意信息\n\n禁止发布虚假师资、虚假需求、虚假薪资，禁止利用平台信息开展营销、骚扰、诈骗、引流、私域推销等无关行为。\n\n### 4.2 线下交易风险郑重提示\n\n所有线下见面、授课履约、资金往来均为用户个人自主民事行为，平台不参与、不控制、不担保。用户自主选择线下交易产生的人身、财产、隐私、履约纠纷，由双方自行承担；平台仅在存在故意/重大过失时承担对应过错责任。\n\n### 4.3 禁止违法违规内容发布\n\n用户不得发布违反《网络安全法》《广告法》《个人信息保护法》等法律法规的内容，禁止发布政治敏感、色情、暴力、赌博、辱骂诽谤、侵权、违法引流等信息，违者平台可立即处置账号并报备监管部门。\n\n### 4.4 隐私保护义务\n\n用户获取的对方联系方式、个人信息，仅限本次家教对接使用，禁止倒卖、公开、批量传播、商用，违者承担侵权及法律责任。\n\n## 五、双方权利与义务（权责平衡）\n\n### 5.1 教员权利义务\n\n教员享有自主接单、自主排课、拒绝不合理需求的权利；负有如实介绍资质、按时沟通、恪守师德、文明授课、不歧视侮辱学员、无故停课提前告知的义务。\n\n### 5.2 家长/学员权利义务\n\n家长享有查看认证信息、合理反馈教学问题的权利；负有如实发布需求、尊重教员、禁止骚扰与不合理附加要求的义务。未成年人授课期间，监护人负有全程安全监护义务，首次授课建议选择公共场所或陪同到场。\n\n### 5.3 平台权利与合规义务\n\n**1.** 平台有权对虚假信息、违规用户进行警告、功能限制、账号封禁、违规公示（全程脱敏，不泄露任何个人敏感信息）。\n\n**2.** 用户申诉权利（新规必填）：用户若对平台处罚结果有异议，可在收到通知7日内通过官方邮箱/客服入口提交申诉，平台将在3个工作日内核查并答复。\n\n**3.** 平台负有信息巡查、风险提示、违法信息处置、配合监管调查、协助用户合法维权的基础合规义务。\n\n## 六、免责条款（合规无绝对免责版）\n\n### 6.1 不可抗力免责\n\n因自然灾害、政策调整、政府监管、网络大面积故障、运营商中断等不可抗力导致服务暂停、数据延迟的，平台无责，不承担违约责任。\n\n### 6.2 线下人身财产风险免责（合规兜底）\n\n线下授课、见面沟通属于用户自主民事行为，平台已充分履行安全提示、风险告知、资质形式核验义务的，对用户之间的人身伤害、财产损失、侵权纠纷不承担赔偿责任；仅在平台存在故意或重大过失情形下依法承担过错责任。\n\n### 6.3 用户自主发布信息免责\n\n用户自行发布的信息错误、虚假、过期、遗漏，由发布方自行负责；平台发现或收到反馈后可及时更正、下架，不承担赔偿责任。\n\n### 6.4 第三方链接免责\n\n平台第三方外链仅为便利展示，不担保其安全性与真实性，用户跳转访问风险自行承担。\n\n### 6.5 用户纠纷处理规则\n\n用户双方履约、薪资、教学质量纠纷由双方自行协商、诉讼解决。平台调解为协商性质，不替代司法途径。若双方达成一致，建议以书面形式确认。平台因调解行为本身存在过错导致用户新损失的除外。\n\n## 七、知识产权\n\n### 7.1 平台LOGO、UI、代码、页面编排、文案体系知识产权均归平台所有，受著作权法保护。\n\n### 7.2 未经书面授权，禁止复刻、镜像、反编译、商用搬运。\n\n### 7.3 用户发布内容授予平台非排他、免费展示使用权，仅用于平台正常服务；账号注销后，内容处理遵从隐私政策。\n\n## 八、隐私保护与数据合规\n\n### 8.1 平台隐私政策为本协议同等效力文件，严格遵循个人信息保护相关法律法规。\n\n### 8.2 用户禁止提前泄露身份证、银行卡、详细住址等敏感信息，自行把控线上沟通隐私边界。\n\n### 8.3 账号注销后，除法律法规要求留存的备案信息（留存不少于三年）外，平台将对用户普通信息、认证材料进行删除或匿名化处理；用户可依法申请个人信息查询、更正、删除。\n\n### 8.4 未成年人专项保护\n\n针对未成年学员，平台严格保护其个人信息，禁止任何用户收集、泄露、滥用未成年人隐私；家长需全程履行监护与安全管理责任。家长为未成年学员注册或发布需求时，视为该家长已获得法定监护人的明示同意，并承诺对其提供的信息的真实性、合法性承担全部责任。\n\n## 九、协议修订、变更与终止\n\n### 9.1 平台可根据法律、监管、运营需要修订协议，修订后以弹窗、站内公示方式告知，用户继续使用即视为同意更新版本。\n\n### 9.2 涉及用户重大权利义务调整的变更，平台提前15日显著公示；用户不接受的，可自主注销账号、终止服务。\n\n### 9.3 协议终止后，平台停止提供服务，但终止前的纠纷处理、责任认定、隐私保护、合规留存条款持续有效。\n\n## 十、法律适用与争议解决\n\n### 10.1 本协议适用中华人民共和国现行有效法律。\n\n### 10.2 争议优先协商解决；协商不成，统一向平台运营主体住所地有管辖权的人民法院提起诉讼。\n\n## 十一、附则\n\n### 11.1 本协议未尽事宜，依照国家法律法规执行。\n\n### 11.2 协议任一条款被认定无效的，不影响其余条款的合法效力。\n\n### 11.3 投诉、咨询、申诉渠道（上线必填）：\n\n**官方邮箱：** ___________\n\n**在线客服/申诉入口：** ___________\n\n**运营主体全称：** ___________",
  "POLICY_PRIVACY": "# 经世知途家教信息平台隐私政策\n\n**更新日期：** 2026年8月8日\n\n**生效日期：** 2026年8月8日\n\n经世知途家教信息平台（以下简称“我们/平台方”）严格依据《中华人民共和国个人信息保护法》《中华人民共和国网络安全法》《中华人民共和国未成年人保护法》《未成年人网络保护条例》等法律法规制定本隐私政策。\n\n本政策旨在清晰告知用户个人信息的收集、使用、存储、共享、保护及用户法定隐私权利。本政策与《经世知途家教信息平台用户协议》具有同等法律效力，二者条款保持完全一致，互为补充。\n\n您注册、登录、继续使用平台服务，即代表您已自愿、明确、知情同意本隐私政策全部内容。\n\n## 一、适用范围与运营主体公示\n\n**1.** 本政策适用于平台全部用户：教员用户、家长/学员用户、网站访客。\n\n**2.** 本平台为纯信息撮合类大学生创业平台，无资金托管、无支付结算、无线下教学履约行为，仅提供家教信息发布、展示、检索、用户对接服务。\n\n**3.** 本政策仅约束平台系统数据处理行为，不适用用户线下自行沟通、私下交易产生的信息流转。\n\n**官方公示信息：**\n\n**平台名称：** ___________\n\n**运营责任主体：** ___________\n\n**官方邮箱：** ___________\n\n**用户申诉/投诉入口：** ___________\n\n## 二、数据处理合法依据（法定必填）\n\n我们处理您的个人信息，严格基于以下合法基础：\n\n**1. 用户明示同意：** 您主动注册、提交信息、使用服务即视为同意；\n\n**2. 履行服务合同必要：** 为完成您要求的家教信息匹配、展示、对接服务；\n\n**3. 合法公共利益：** 防范风险、处置违规、配合司法与监管调查；\n\n**4. 法定义务合规留存：** 依法留存合规备案数据。\n\n## 三、我们收集的信息类型（最小必要原则）\n\n我们严格遵循合法、正当、必要、最小化原则，不收集无关隐私、不强制收集敏感信息、不滥用用户数据。\n\n### （一）用户主动提交信息\n\n**1. 账号注册信息：** 手机号、昵称、加密登录密码（无明文存储）。\n\n**2. 教员敏感认证信息（单独授权）：** 真实姓名、院校、专业、学籍证明、学生证、学信网截图。此类为敏感个人信息，仅用于后台身份核验，绝不对外公开、绝不商用、绝不私自导出。在上传学籍证明材料时，我们将通过独立的弹窗向您取得处理该类敏感个人信息的单独同意，您可以自主选择是否授权，不影响您使用平台的其他基础功能。\n\n**3. 服务公开信息：** 教员授课科目、时段、个人简介；家长发布的年级、科目、区域、期望薪资等需求信息。\n\n**4. 售后沟通信息：** 咨询、申诉、反馈记录。\n\n### （二）系统自动采集信息（Cookie/日志）\n\n为保障网站稳定、安全风控、防刷运维，平台自动采集基础访问数据：设备类型、浏览器、访问时间、页面轨迹、IP属地、会话Cookie。\n\n以上数据仅用于平台安全运维，不做用户画像、不做广告推送、不对外共享。\n\n### （三）未成年人信息专项规则\n\n**1.** 平台不主动收集未成年人敏感信息（身份证、详细住址、班级、出生日期）。\n\n**2.** 涉及十四周岁以下未成年人信息处理，严格遵守《个人信息保护法》第三十一条，仅在监护人明示同意后方可处理。\n\n**3.** 家长发布未成年人家教需求，视为已取得法定监护人完整、明示同意，对信息合法性承担全部责任。\n\n**4.** 严禁任何用户倒卖、泄露、传播未成年人信息，违规账号永久封禁并保留追责权利。\n\n**5. 未成年人个人信息处理专门规则（依据《个人信息保护法》第三十一条制定）：**\n\n**（1）收集前提：** 处理不满十四周岁未成年人个人信息前，必须取得其父母或其他监护人的明示、单独同意，不捆绑默认授权。\n\n**（2）收集范围：** 仅收集完成家教匹配所必需的基础信息（年级、科目需求、授课区域），严格遵循最小必要原则，不收集身份证号、详细住址、学校班级、出生日期等非必要敏感信息。\n\n**（3）使用与存储限制：** 未成年人个人信息仅用于家教信息匹配、对接服务，不作商业推送、用户画像、对外共享；未成年人个人信息在账号注销或监护人主动要求删除时，平台将依法及时删除或匿名化处理，不留冗余隐私数据。\n\n**（4）监护人专属权利：** 监护人有权随时查询、更正、补充、删除其监护的未成年学员个人信息，平台在核验监护人身份后，3个工作日内完成响应处理。\n\n**（5）专项投诉渠道：** 监护人如有未成年人隐私咨询、异议、投诉需求，可通过本政策公示的官方邮箱、平台客服申诉入口提交，平台优先核查处理。\n\n## 四、信息使用范围（无超范围使用）\n\n我们仅将信息用于以下目的，无任何变相滥用：\n\n**1.** 账号注册、登录、身份核验、权限管理；\n\n**2.** 实现师资展示、需求发布、信息匹配、用户对接等核心服务；\n\n**3.** 识别虚假信息、诈骗、骚扰、违规接单，维护平台秩序；\n\n**4.** 处理用户咨询、投诉、申诉；\n\n**5.** 推送必要的站内通知与安全提示；\n\n**6.** 依法配合司法、监管合规调查。\n\n## 五、信息共享与披露规则（严格限制）\n\n我们绝不售卖、出租、商用用户个人信息。\n\n**1. 用户自主公开：** 用户发布的家教需求、师资简介仅对平台注册用户可见，用户自行对公开内容负责。平台首页或列表页仅展示脱敏后的摘要信息（如“张同学，数学，大三”），不展示联系方式及可识别具体个人的详细信息，完整资料仅在用户双方互相匹配或主动查看时向对方开放。\n\n**2. 服务必要共享：** 仅为家教对接，双向开放联系方式，仅限本次对接使用，禁止二次传播、倒卖、商用。\n\n**3. 法定披露：** 司法、监管机关依法出具文书时，依规提供备案信息。\n\n**4. 无第三方商业共享：** 不向广告、营销、自媒体机构流转任何用户隐私数据。\n\n## 六、数据存储与留存期限（与用户协议完全对齐）\n\n**1. 账号存续期：** 正常保留服务必需数据。\n\n**2. 账号注销后：** 除法定合规备案、风控日志留存不少于三年外，所有个人资料、证件、联系方式、发布内容全部删除或匿名化，无法识别个人身份。\n\n**3. 普通访问日志：** 留存6–12个月自动清理。\n\n**4. 未成年人数据：** 注销或监护人申请删除后，立即清理或匿名化。\n\n## 七、用户法定隐私权利（含操作入口）\n\n用户依法享有完整隐私权利，平台提供便捷行使渠道：\n\n**1. 查阅、更正权：** 个人中心可自行查看、修改资料；\n\n**2. 删除、清空权：** 可自主清空发布内容，或联系客服删除非必要数据；\n\n**3. 注销权：** 用户可随时自主注销账号；\n\n**4. 撤回同意权：** 可随时撤回非必要授权，但手机号、登录密码等账号存续所必需的基础信息，在您注销账号前需继续保留，以保障您正常登录使用；\n\n**5. 申诉权：** 对数据处理、账号处罚有异议，可通过客服/邮箱申诉，平台5个工作日内答复（与用户协议统一）。\n\n## 八、信息安全保护措施\n\n**1.** 密码加密存储，无明文留存；\n\n**2.** 教员证件仅后台人工核验，不对外公开、不允许导出传播；\n\n**3.** 内部数据权限分级管控，严防内部泄露；\n\n**4.** 定期漏洞修复、防爬虫、防批量采集；\n\n**5.** 发生数据风险时，第一时间告知用户并启动应急处置。\n\n## 九、用户自主安全义务\n\n**1.** 用户严禁向对方泄露身份证、银行卡、精确住址、密码等敏感信息；\n\n**2.** 平台获取的对方信息仅限家教对接使用；\n\n**3.** 私下交易、私自泄露隐私造成的损失，由用户自行承担。\n\n## 十、第三方链接免责\n\n平台若含第三方链接，仅为用户便利。第三方独立承担隐私合规责任，平台不共享任何用户隐私数据给第三方，用户跳转访问风险自行承担。\n\n## 十一、政策更新规则\n\n**1.** 政策更新后在平台首页公示，重大权益变更弹窗/站内信告知；\n\n**2.** 用户继续使用服务即视为同意新版政策；\n\n**3.** 不认可新版条款可注销账号终止服务。\n\n## 十二、投诉与维权渠道\n\n**官方邮箱：** ___________\n\n**在线申诉入口：** ___________\n\n## 十三、附则\n\n**1.** 本政策未尽事宜依照国家法律法规执行。\n\n**2.** 任一条款无效不影响整体效力。\n\n**3.** 本政策无霸王解释权，条款存在争议时，依法作出有利于用户的解释（与用户协议统一）。",
  "VALIDATE_INVITE_FIRST": "请先验证邀请码",
  "VALIDATE_INVITE_REQUIRED": "请输入邀请码",
  "VALIDATE_SELECT_SUBJECT": "请至少选择一个科目",
  "VALIDATE_SELECT_RATING": "请选择评分",
  "VALIDATE_COMMENT_TOO_SHORT": "评价内容太短",
  "CONFIRM_DELETE_DEMAND": "删除后不可恢复，相关教师意向也会一并清除。确定要删除这条需求吗？",
  "CONFIRM_DELETE_REVIEW": "删除后不可恢复。确定要删除这条评价吗？",
  "CONFIRM_BAN": "封禁后该账户将无法登录。确定要封禁吗？",
  "CONFIRM_UNBAN": "确定要解除该账户的封禁吗？",
  "SUCCESS_INVITE_CONFIRMED": "邀请码已确认，请填写注册信息",
  "SUCCESS_DEMAND_SUBMITTED": "需求已提交！",
  "SUCCESS_DEMAND_UPDATED": "需求已更新！",
  "SUCCESS_DEMAND_DELETED": "需求已删除",
  "SUCCESS_BANNED": "已封禁该账户",
  "SUCCESS_UNBANNED": "已解封该账户",
  "REVIEW_DELETED": "评价已删除",
  "STATUS_PENDING": "待审核",
  "STATUS_APPROVED": "已通过",
  "STATUS_REJECTED": "已拒绝",
  "SUCCESS_PROFILE_SAVED": "信息已保存！",
  "SUCCESS_REVIEW_SUBMITTED": "评价已提交，等待管理员审核",
  "SUCCESS_COPIED": "已复制",
  "SUCCESS_APPROVED": "已通过",
  "SUCCESS_REJECTED": "已拒绝",
  "ERROR_LOAD_PREFIX": "加载失败: ",
  "ERROR_GENERATE_INVITE": "生成失败: ",
  "NETWORK_ERROR": "网络连接失败，请检查网络后重试",
  "EMPTY_NO_TEACHERS": "还没有老师入驻。如果你是教师，完善档案后会出现在这里；学生也可以先发布需求，匹配的老师会主动联系你。",
  "EMPTY_NO_DEMANDS": "还没有学生发布需求。教师可以先完善档案，新需求会按匹配度推荐给你。",
  "EMPTY_NO_MY_DEMANDS": "还没有发布过需求。点「新建需求」，填写学生情况和期望的科目、预算，老师看到后会联系你。",
  "EMPTY_NO_REVIEWS": "还没有人写下评价。与该教师完成签约后，学生可以分享真实的上课体验。",
  "EMPTY_NO_USERS": "当前筛选条件下没有用户。调整筛选条件后再看看。",
  "TEACHER_SORT_MATCH": "匹配度最高",
  "TEACHER_SORT_RATING": "评分最高",
  "TEACHER_SORT_PRICE": "报价最低",
  "INVITE_NO_EXPIRY": "无有效期 · 一人使用即失效",
  "INVITE_MANAGER_TITLE": "邀请码管理",
  "INVITE_MANAGER_EMPTY": "还没有邀请码，点击「生成邀请码」创建",
  "INVITE_MANAGER_CODE": "邀请码",
  "INVITE_MANAGER_STATUS": "状态",
  "INVITE_MANAGER_USED": "已使用",
  "INVITE_MANAGER_ACTIVE": "未使用",
  "INVITE_MANAGER_USED_BY": "使用者",
  "INVITE_MANAGER_CREATED": "创建时间",
  "INVITE_MANAGER_REVOKE": "作废",
  "INVITE_MANAGER_REVOKED": "邀请码已作废",
  "PRICE_UNIT": "元/h",
  "BTN_VIEW_DETAIL": "查看详情 / 评价",
  "SCORE_SCALE_SUFFIX": "分制",
  "SUBMITTER_PARENT": "家长",
  "SUBMITTER_STUDENT": "学生",
  "SUBMITTER_PREFIX": "提交者: ",
  "BUDGET_NEGOTIABLE": "面议",
  "BUDGET_NO_LIMIT": "不限",
  "BUDGET_UNIT_SUFFIX": "元/h",
  "PAGE_NOTIFICATIONS": "通知信息",
  "PAGE_ACCOUNT_SETTINGS": "设置",
  "HINT_ROLE_STUDENT": "学生账户",
  "HINT_ROLE_TEACHER": "教师账户",
  "HINT_ROLE_ADMIN": "管理员账户",
  "INTENT_ACCEPTED_GO": "已建立联系 →",
  "INTENT_PENDING": "意向已提交",
  "INTENT_REJECTED": "未获选",
  "BTN_SUBMIT_INTENT": "提交试课意向",
  "INTENT_SUBMITTED_TOAST": "试课意向已提交，等待学生处理",
  "PROFILE_INCOMPLETE_HINT": "提交试课意向前，请先完善教师档案：省份、年级、性别、擅长科目、报价均为必填。学生要看到完整的教师信息，才能判断是否接受你的意向。",
  "BTN_LATER": "稍后再说",
  "BTN_GO_COMPLETE_PROFILE": "去完善档案",
  "BTN_PUSH_DEMAND": "发送需求",
  "PUSH_TEACHER_FALLBACK": "该老师",
  "PUSH_MODAL_TITLE_PREFIX": "把需求发给 ",
  "PUSH_MODAL_HINT": "选一条需求发送给这位老师，对方会在需求大厅优先看到它。",
  "PUSH_GREET_LABEL": "和老师打个招呼（可选）",
  "PUSH_GREET_PLACEHOLDER": "简单介绍一下自己，说说为什么想请这位老师～（例：老师您好，孩子初二数学偏弱，看到您带过三届中考班，想请您试试）",
  "PUSH_GREET_OPTIONAL": "可留空直接发送；填写后老师会在需求卡上看到这段话。",
  "EMPTY_NO_MY_DEMANDS_SHORT": "你还没有需求，先去「我的需求」发布一条吧。",
  "PUSH_NO_AVAILABLE_DEMANDS": "暂时没有可发送的需求。先到「我的需求」发布一条，开放中的需求才能发给老师。",
  "BTN_SEND": "发送",
  "VALIDATE_SELECT_DEMAND": "请先选择一条需求",
  "PUSH_SENT_FALLBACK": "需求已发送",
  "PUSH_NOTE_TEXT": "学生主动向你提交了需求",
  "BTN_PUSH_REJECT": "暂时没空",
  "BTN_PUSH_ACCEPT": "确认试课意向",
  "PUSH_SECTION_TITLE": "学生主动发给你的需求",
  "PUSH_ACCEPTED_TOAST": "已确认，可在「我的会话」开始对话",
  "PUSH_REJECTED_TOAST": "已谢绝",
  "PUSH_ACCEPTED_TAG": "已确认",
  "PUSH_REJECTED_TAG": "已谢绝",
  "CONTRACT_DRAFT_SENT_TOAST": "合同草案已发送，等待对方确认",
  "CONTRACT_BIZ_END": "<!-- 业务条款结束",
  "BTN_SEND_NOTIFICATION": "发通知",
  "NOTIFY_BROADCAST_PREFIX": "【系统通知】",
  "NOTIF_INTENT_ACCEPTED": "学生已同意你的试课意向，会话已建立，请前往「我的会话」查看详情",
  "NOTIF_INTENT_REJECTED": "关于「{subjects}」的家教需求，学生已经和更合适的老师建立了联系。你的档案仍在教师广场展示，新的匹配机会会继续推送。",
  "NOTIF_PUSH_ACCEPTED": "教师已确认你发送的需求，会话已建立，请前往「我的会话」查看详情",
  "NOTIF_PUSH_REJECTED": "关于「{subjects}」的家教需求，这位老师暂时排不开。我们会继续为你留意匹配的老师，有进展会在这里通知你。",
  "NOTIF_SUBJECTS_FALLBACK": "相关科目",
  "NOTIF_CONTRACT_DRAFT_SENT": "「{name}」发来一份合同草案，请前往「我的合同」查看并确认",
  "NOTIF_CONTRACT_SIGN_WAITING": "「{name}」已确认签约，请在「我的合同」内完成你的确认",
  "NOTIF_CONTRACT_MODIFIED": "「{name}」修改了合同内容，双方签约确认已重置，请重新查看",
  "NOTIF_CONTRACT_SIGNED": "双方已完成签约，合同生效。请按约定时间开始上课。",
  "NOTIF_CONTRACT_REVOKED": "「{name}」已撤销双方签署的合同，活跃数据已抹除，存证留档保留。",
  "NOTIF_CONTRACT_CANCELLED": "「{name}」已取消签约，可于会话中继续商议细节",
  "NOTIF_SIGNING_REQUEST_SENT": "「{name}」向你发送了签约请求",
  "NOTIF_SIGNING_CONFIRMED": "对方已确认签约请求",
  "NOTIF_SIGNING_REJECTED": "对方已拒绝此次签约请求",
  "NOTIF_FEEDBACK_RESOLVED": "你反馈的问题已经处理好了。具体结果可以到「我的投诉与反馈」查看。",
  "NOTIF_FEEDBACK_COMPLAINT_RESOLVED": "你的投诉已处理完毕，结果可以在「我的投诉与反馈」里查看。",
  "NOTIF_VERIFY_APPROVED_ADMISSION": "录取通知书核验已通过，你的接单资格已开放",
  "NOTIF_VERIFY_APPROVED_CHSI": "学信网学籍核验已通过",
  "NOTIF_VERIFY_DETAIL_PREFIX": "核验信息：",
  "NOTIF_VERIFY_REJECTED": "学信网学籍核验未通过，请重新提交验证码",
  "NOTIF_VERIFY_REVOKED": "你的接单资格已被管理员撤销，可重新提交学信网核验",
  "NOTIF_AWARD_APPROVED": "你的荣誉奖项「{title}」已通过审核，将展示在你的教师主页。",
  "NOTIF_AWARD_REJECTED": "你的荣誉奖项「{title}」未通过审核，请登录查看驳回理由。",
  "NOTIF_CONTENT_PENALTY": "你的{label}因违反规则「{rule}」被管理员{action}。原因：{reason}",
  "NOTIF_CONTENT_PENALTY_SUMMARY": "。触发内容：{summary}",
  "NOTIF_PENALTY_ACTION_BAN": "封禁账户",
  "NOTIF_PENALTY_ACTION_REMOVE": "移除内容",
  "NOTIF_RULE_FALLBACK": "平台规则",
  "BROADCAST_MODAL_TITLE": "发送系统通知",
  "BROADCAST_TITLE_PLACEHOLDER": "通知标题（推送时自动加【系统通知】前缀）",
  "BROADCAST_BODY_PLACEHOLDER": "输入通知正文，全部用户都会收到（支持轻量 Markdown）",
  "VALIDATE_BROADCAST_EMPTY": "通知内容不能为空",
  "BROADCAST_CONFIRM_TEXT": "广播将通知全站所有用户，请输入密码确认发送。",
  "BROADCAST_SENT_TOAST": "通知已发送给全部用户",
  "PAGE_BROWSE_TEACHERS_PEER_DESC": "查看同行的信息与评价",
  "CHAT_BTN_DRAFT_CONTRACT": "起草合同",
  "CHAT_PLUS_ARIA": "附件与合同",
  "CHAT_PREVIEW_CONTRACT": "[合同草案]",
  "CHAT_PREVIEW_SIGNING_REQ": "[签约请求]",
  "CHAT_PREVIEW_SIGNING_RESP": "[签约回应]",
  "CHAT_CONTRACT_BUBBLE_MINE": "你向对方发送了一份合同草案，可前往「我的合同」查看进度",
  "CHAT_CONTRACT_BUBBLE_OTHER": "对方向你发送了一份合同草案，请前往「我的合同」查看并确认",
  "PAGE_MY_CONTRACTS": "我的合同",
  "PAGE_MY_CONTRACTS_DESC": "合同草案确认与正式签约",
  "DRAFT_MODAL_TITLE": "起草合同",
  "SIGNING_REQUEST_SENT_TOAST": "签约请求已发送",
  "SIGNING_CONFIRMED": "对方已确认签约请求",
  "SIGNING_REJECTED": "对方已拒绝此次签约请求",
  "SIGNING_MY_CONFIRMED": "你已确认签约请求",
  "SIGNING_MY_REJECTED": "你已拒绝此次签约请求",
  "SIGNING_MODAL_TITLE": "发起签约",
  "SIGNING_MODAL_HINT": "选择需求、确认报价、时间与授课方式后发送，由对方确认",
  "SIGNING_DEMAND_LABEL": "选择需求",
  "SIGNING_DEMAND_PLACEHOLDER": "请选择要签约的需求",
  "VALIDATE_SIGNING_DEMAND": "请选择要签约的需求",
  "SIGNING_NO_DEMAND_HINT": "暂时没有开放中的需求。先发布一条需求，双方确认意向后才能发起签约。",
  "SIGNING_DEMANDS_LOAD_FAIL": "需求列表加载失败，请刷新页面后重试。",
  "LABEL_SIGNING_PRICE": "报价（元/小时）",
  "LABEL_SIGNING_SCHEDULE": "授课时间（每周固定时间段）",
  "LABEL_SIGNING_METHOD": "授课方式",
  "SIGNING_PRICE_PLACEHOLDER": "例如 150",
  "SIGNING_METHOD_ONLINE": "线上授课",
  "SIGNING_METHOD_OFFLINE": "线下授课",
  "BTN_SIGNING_SEND": "发送签约请求",
  "CHAT_SIGNING_REQUEST_TITLE": "对方向你发送了签约请求",
  "CHAT_SIGNING_MINE_TITLE": "你向对方发送了签约请求",
  "CHAT_SIGNING_PRICE": "报价",
  "CHAT_SIGNING_SCHEDULE": "时间",
  "CHAT_SIGNING_METHOD": "方式",
  "BTN_SIGNING_CONFIRM": "确认签约",
  "BTN_SIGNING_REJECT": "拒绝",
  "SIGNING_REJECTED_TEXT": "已拒绝此次签约请求",
  "VALIDATE_SIGNING_PRICE": "请填写有效报价",
  "VALIDATE_SIGNING_SCHEDULE": "请填写授课时间",
  "FUNDS_NOTE": "平台仅提供信息撮合与合同存证服务，不参与任何费用结算。课时费请由双方自行协商并在站外直接结算（如微信、支付宝转账等），平台不代收、不代付。",
  "FUNDS_NOTE_SHORT": "平台不参与费用结算，课费请与对方站外直接结算。",
  "LABEL_CONTRACT_METHOD": "教学方式",
  "LABEL_CONTRACT_PLAN": "教学方案",
  "LABEL_CONTRACT_RATE": "约定时薪（元/小时）",
  "CONTRACT_PLAN_PLACEHOLDER": "描述教学目标、内容安排与上课节奏，发送后将按此信息生成正式合同",
  "VALIDATE_CONTRACT_PLAN": "请填写教学方案",
  "VALIDATE_CONTRACT_RATE": "请填写约定时薪",
  "CONTRACT_EMPTY": "合同内容不能为空",
  "CONTRACT_PRICE_PLACEHOLDER": "如：150",
  "ADMIN_CONTRACT_DRAFTER_PREFIX": "起草 ",
  "LABEL_CONTRACT_SCHEDULE": "授课时间（每周固定时间段）",
  "LABEL_CONTRACT_LOCATION": "授课地点",
  "CONTRACT_LOCATION_PLACEHOLDER": "甲方常住处或双方另行约定的地点",
  "CONTRACT_LOCATION_NOTE": "出于隐私保护，授课地点请使用「甲方常住处」等模糊表述，勿将详细地址上传至平台。",
  "LABEL_CONTRACT_PAY_METHOD": "薪资结算方式",
  "PAY_METHOD_PER_SESSION": "次付",
  "PAY_METHOD_WEEKLY": "周付",
  "PAY_METHOD_MONTHLY": "月付",
  "PAY_METHOD_OTHER": "其他",
  "CONTRACT_PAY_METHOD_OTHER_PLACEHOLDER": "请输入结算方式，如：每 10 次课结算一次",
  "VALIDATE_CONTRACT_PAY_METHOD_OTHER": "请输入具体的薪资结算方式",
  "LABEL_CONTRACT_FIRST_LESSON": "首次上课日期",
  "SEG_YEAR_ARIA": "年",
  "SEG_MONTH_ARIA": "月",
  "SEG_DAY_ARIA": "日",
  "SEG_HOUR_ARIA": "时",
  "SEG_MINUTE_ARIA": "分",
  "VALIDATE_CONTRACT_FIRST_LESSON_INCOMPLETE": "请完整填写首次上课日期（年/月/日）",
  "LABEL_CONTRACT_TRIAL_PAY": "试课薪资方案",
  "TRIAL_PAY_FIRST_FREE": "第一次试课免费",
  "TRIAL_PAY_FIRST_HOUR_FREE": "第一小时免费，第二小时收费",
  "TRIAL_PAY_NORMAL": "全程正常收费",
  "TRIAL_PAY_OTHER": "其他",
  "CONTRACT_TRIAL_PAY_OTHER_PLACEHOLDER": "请输入试课薪资方案",
  "VALIDATE_CONTRACT_TRIAL_PAY_OTHER": "请输入具体的试课薪资方案",
  "LABEL_CONTRACT_DEMAND": "对应需求",
  "CONTRACT_DEMANDS_SIGNED_HINT": "仅已签约需求可继续签合同",
  "CONTRACT_REQUIRE_SIGNED": "请选择已签约需求",
  "CONTRACT_DEMANDS_EMPTY": "还没有已签约的需求。双方都确认签约后，这里才能起草正式合同。",
  "CONTRACT_DEMANDS_LOAD_FAIL": "需求列表加载失败，请刷新页面后重试。",
  "DEMAND_TAG_CONTRACTED": "已签约",
  "DEMAND_TAG_REVOKED": "合同已撤销",
  "TAG_MATCH": "匹配度 ",
  "TAG_MATCH_HINT": " · 点击展开明细",
  "TAG_MATCH_TITLE": "点击查看匹配度明细",
  "TAG_MATCH_NO_DEMAND": "发布需求后展示匹配度",
  "MATCH_DETAIL_TITLE": "匹配度明细",
  "MATCH_DETAIL_SUB": "根据你的教师档案与这条需求自动计算",
  "MATCH_ITEM_SUBJECT": "科目匹配",
  "MATCH_ITEM_PERSONALITY": "性格匹配",
  "MATCH_ITEM_REGION": "区域匹配",
  "MATCH_ITEM_BUDGET": "预算匹配",
  "MATCH_ITEM_GENDER": "性别匹配",
  "MATCH_SUBJECT_HIT": "命中 {hit}/{total} 门需求科目",
  "MATCH_REGION_HIT": "同省（{name}），区域吻合",
  "MATCH_REGION_MISS": "省份不符，区域不匹配",
  "MATCH_DISTANCE_SAME": "同镇/同街道，零距离",
  "MATCH_DISTANCE_HIT": "距授课点约 {km} 公里",
  "MATCH_DISTANCE_ONLINE": "线上授课，距离不计分",
  "MATCH_DISTANCE_NO_LOCALE": "教师未填上海常住地，未计入",
  "MATCH_BUDGET_HIT": "报价在需求预算区间内",
  "MATCH_BUDGET_MISS": "报价超出需求预算区间",
  "MATCH_PERSONALITY_HIT": "命中 {hit}/{total} 个偏好性格",
  "MATCH_PERSONALITY_MISS": "教师性格与偏好无重合",
  "MATCH_GENDER_ANY": "需求不限性别",
  "MATCH_GENDER_HIT": "性别符合需求偏好",
  "MATCH_GENDER_MISS": "性别不符需求偏好",
  "MATCH_GENDER_UNDISCLOSED": "教师未透露性别，明确偏好折半计分",
  "MATCH_DIM_SKIP": "该项缺数据，未计入",
  "MATCH_NOTE": "计分口径：科目 {subject} 分（命中需求科目的比例）+ 区域 {region} 分（上海线下按教师常住地距授课点公里数计分、线上单不计）+ 预算 {budget} 分（报价在区间内）+ 性格 {personality} 分（偏好性格重合比例）+ 性别 {gender} 分（偏好性别吻合）。缺数据的维度不计分，总分按有效维度归一化到 100。",
  "MATCH_T_TITLE": "教师匹配度明细",
  "MATCH_TEACHER_DETAIL_SUB": "根据你的活跃需求与该教师档案自动计算，按匹配度从高到低展示",
  "MATCH_T_PCT": "匹配度：",
  "MATCH_T_DEMAND_PREFIX": "需求",
  "MATCH_T_BRACKET_L": "【",
  "MATCH_T_BRACKET_R": "】",
  "BTN_REOPEN_DEMAND": "重开需求",
  "DEMAND_REOPENED_TOAST": "需求已重新开放",
  "CONFIRM_REOPEN_DEMAND": "重开后该需求将重新出现在需求大厅，再次接受教师意向。确定重开吗？",
  "DEMAND_PREFIX": "需求 ",
  "BTN_VERIFY_LEDGER": "存证校验",
  "CONTRACT_LEDGER_VALID": "存证校验通过：合同文本与签署指纹一致",
  "CONTRACT_LEDGER_INVALID": "存证校验异常：文本与签署指纹不一致",
  "CONTRACT_LEDGER_ARCHIVED": "该合同已撤销，签署时的存证留档仍保留",
  "CONTRACT_LEDGER_NONE": "该合同暂无存证记录",
  "BTN_REVOKE_CONTRACT": "撤销合同",
  "REVOKE_MODAL_TITLE": "撤销合同",
  "REVOKE_CONTRACT_WARN": "此功能仅限在双方已经约定好结束合同时使用。撤销后合同不再生效，双方列表保留「已撤销」状态、正文与存证台账留档（合同不删除）。由此产生的一切法律后果由双方自行承担。",
  "BTN_THINK_AGAIN": "再想想",
  "BTN_CONTINUE_DANGER": "我已知晓后果，继续",
  "REVOKE_CONTRACT_FINAL": "最终确认：撤销后不可恢复，确定继续吗？",
  "CONTRACT_REVOKED_TOAST": "合同已撤销",
  "BTN_DEACTIVATE_ACCOUNT": "注销账户",
  "DEACTIVATE_WARN": "注销后：你的教师档案、发布的帖子与点赞、反馈、通知等仅与你一人相关的数据将被永久删除；需求、会话、合同、评价等涉及双方的数据会保留，但你的用户名将显示为「已注销用户」。此操作不可恢复。",
  "DEACTIVATE_FINAL": "最终确认：注销后账户与个人数据不可恢复，确定继续吗？",
  "DEACTIVATE_DONE_TOAST": "账户已注销",
  "REAUTH_PASSWORD_LABEL": "当前密码",
  "REAUTH_PASSWORD_HINT": "输入当前密码以确认此操作",
  "PEER_DEACTIVATED_TAG": "一方已注销",
  "GUEST_NOT_LOGGED_IN": "未登录",
  "GUEST_TAP_TO_LOGIN": "点击登录以使用全部功能",
  "AUTH_LOGIN_TITLE": "欢迎回到经途·伴学",
  "AUTH_LOGIN_SUB": "登录后继续管理需求、会话与合同",
  "AUTH_LOGIN_TITLE_GUEST": "登录后继续刚才的操作",
  "AUTH_LOGIN_SUB_GUEST": "登录成功后会自动返回你刚才所在的页面",
  "AUTH_LOGIN_TITLE_TEACHER": "登录教师账户",
  "AUTH_LOGIN_SUB_TEACHER": "教师端可浏览学生需求、提交试课意向和管理合同",
  "AUTH_LOGIN_TITLE_STUDENT": "登录学生账户",
  "AUTH_LOGIN_SUB_STUDENT": "学生端可发布需求、联系老师和管理签约",
  "PROFILE_PANEL_TITLE": "个人信息",
  "REVIEW_LOCKED_HINT": "与这位老师签约后，即可写下你的评价",
  "LABEL_GRADE": "年级",
  "LABEL_GENDER": "性别",
  "LABEL_PRICE": "报价",
  "LABEL_INTRO": "简介",
  "LABEL_GAOKAO_SCORES": "高考成绩",
  "LABEL_SUBJECT": "科目",
  "DEMAND_DETAIL_TITLE_FALLBACK": "需求详情",
  "DEMAND_SORT_MATCH": "匹配度最高",
  "DEMAND_SORT_NEWEST": "最新发布",
  "DEMAND_SORT_BUDGET": "预算从低到高",
  "DEMAND_FILTER_ALL": "全部",
  "DEMAND_FILTER_EMPTY": "没有符合筛选条件的需求",
  "LABEL_SCHOOL": "学校",
  "LABEL_REAL_NAME": "真实姓名",
  "LABEL_CONTACT": "联系方式",
  "LABEL_WECHAT": "微信",
  "LABEL_EMAIL": "邮箱",
  "LABEL_PRICE_RANGE": "报价区间（元/小时）",
  "LABEL_TEACHING_METHOD_PROFILE": "授课方式",
  "LABEL_TIME_SLOTS": "可授课时间段",
  "LABEL_GRADUATION_YEAR": "毕业年份",
  "GRAD_YEAR_PLACEHOLDER": "如 2020（留空按最新政策）",
  "GRAD_YEAR_SUFFIX": "年",
  "LABEL_PERSONALITY_TAGS": "性格关键词",
  "PERSONALITY_TAGS_HINT": "（最多 {max} 个）",
  "TAG_PICK_LIMIT": "最多选 {max} 个",
  "LABEL_NONACADEMIC_PROJECTS": "擅长非学科类项目",
  "LABEL_TARGET_PROJECTS": "需求项目",
  "LABEL_NONACADEMIC_PRICES": "非学科类项目报价",
  "PROFILE_SECTION_BASIC": "基本资料",
  "PROFILE_SECTION_ACADEMIC": "学科类资料",
  "PROFILE_SECTION_NONACADEMIC": "非学科类资料",
  "PROFILE_SECTION_PRIVATE": "私密资料",
  "CHSI_GATE_TITLE": "验证学信网学籍",
  "CHSI_GATE_STEPS": [
    "打开学信网 APP",
    "登录后进入「学籍查询」",
    "申请《学籍在线验证报告》",
    "复制在线验证码（有效期 180 天）"
  ],
  "CHSI_GATE_HINT": "提交验证码后，管理员会人工核对你的学籍信息（院校、层次、专业、在读状态、入学年份），通过后开放接单资格。",
  "CHSI_GATE_PLACEHOLDER": "请输入学信网在线验证码",
  "CHSI_GATE_SUBMIT": "提交核验",
  "CHSI_GATE_PENDING": "验证码已提交，管理员核验中（一般 24 小时内完成），通过后开放接单资格",
  "ADMISSION_SWITCH_LINK": "我是大一新生，改为验证录取通知书",
  "ADMISSION_GATE_TITLE": "验证录取通知书",
  "ADMISSION_GATE_BACK": "← 返回学信网验证",
  "ADMISSION_SHOOT_HINT": "请拍摄或上传录取通知书的完整整页照片，确保姓名、考生号、录取院校与专业清晰可读",
  "ADMISSION_PRIVACY_NOTE": "隐私保护声明：录取通知书照片仅用于身份核验，管理员人工核对后将加密存储，不会公开展示，审核结束后仅保留核验结论。",
  "ADMISSION_UPLOAD_BTN": "选择录取通知书照片",
  "ADMISSION_SUBMIT": "提交核验",
  "ADMISSION_GATE_PENDING": "录取通知书已提交，管理员核验中（一般 24 小时内完成），通过后开放接单资格",
  "ADMISSION_IMAGE_INVALID": "录取通知书图片格式不正确（仅支持 jpg/png 等常见图片）",
  "ADMISSION_IMAGE_TOO_LARGE": "录取通知书图片过大，请压缩后重新上传",
  "CHSI_CODE_REQUIRED": "请输入学信网在线验证码",
  "VERIF_NONE": "未提交核验",
  "VERIF_PENDING": "待核验",
  "VERIF_APPROVED": "已通过",
  "VERIF_REJECTED": "已拒绝",
  "CREDENTIAL_VIEW": "点击查看",
  "CONTRACT_STATUS_SIGNING": "待签约",
  "CONTRACT_STATUS_SIGNED": "已签约",
  "CONTRACT_STATUS_REVOKED": "已撤销",
  "BTN_SIGN": "开始签约",
  "BTN_SIGN_WAITING": "等待对方确认签约",
  "BTN_MODIFY_CONTRACT": "修改内容",
  "BTN_VIEW_CONTRACT": "查看合同",
  "BTN_CANCEL_CONTRACT": "取消签约",
  "MODIFY_CONTRACT_TITLE": "修改合同内容",
  "CONTRACT_VIEW_DIFF_TITLE": "查看合同 · 本次改动",
  "CONTRACT_MODIFY_BIZ_HINT": "仅可修改业务条款，法律条款不可修改",
  "CONTRACT_DIFF_HINT": "本次修改的改动处已高亮：绿色=新增，红色删除线=移除；法律条款未改动。",
  "SIGN_MODAL_TITLE": "开始签约",
  "SIGN_READ_HINT": "请阅读合同全文并滚动到底部，方可确认",
  "SIGN_COUNTDOWN_HINT": "{secs}秒后可确认签约",
  "SIGN_READY_HINT": "已阅读完毕，可确认签约",
  "SIGN_READ_DONE_BTN": "我已阅读并确认签约",
  "CONFIRM_SIGN_TWICE": "确认签约后合同即生效、不可单方撤销。你确定已仔细阅读并确认这份合同吗？",
  "CONFIRM_SIGN_FINAL": "请输入账户密码完成最终确认。确认后合同生效，单方无法撤销。",
  "CONFIRM_SIGNING_ACCEPT": "接受签约？需求将锁定为已成交，其他教师的试课意向会被自动拒绝。请输入账户密码完成最终确认。",
  "CONFIRM_CANCEL_CONTRACT": "取消后回到待签约状态、合同保留（会话保留）。确定取消签约吗？",
  "CONTRACT_EMPTY_LIST": "还没有合同。双方确认签约后，可在「我的会话」里起草正式合同。",
  "CONTRACT_MODIFIED_TOAST": "修改已同步给对方，双方需重新确认签约",
  "CONTRACT_CANCELLED_TOAST": "已取消签约，合同保留待重新签约",
  "CONTRACT_REVOKED_BY_ME": "你已撤销合同",
  "CONTRACT_REVOKED_BY_PEER": "对方已撤销合同",
  "CONTRACT_SIGNED_TOAST": "签约完成",
  "CONTRACT_SIGN_DONE_BOTH": "双方已签署",
  "CONTRACT_PARTY_SIGNED_A": "甲方已签",
  "CONTRACT_PARTY_PENDING_A": "甲方待签",
  "CONTRACT_PARTY_SIGNED_B": "乙方已签",
  "CONTRACT_PARTY_PENDING_B": "乙方待签",
  "SIGN_MODAL_DISCLOSE": "你将以平台账号「{username}」电子签署本合同：实名登录 + 密码二次确认即构成可靠电子签名，签署后合同即生效。",
  "CONTRACT_VERIFY_PANEL_TITLE": "存证校验",
  "CONTRACT_VERIFY_HASH": "当前指纹",
  "CONTRACT_VERIFY_ENTRIES": "台账条目",
  "CONTRACT_VERIFY_FLOW": "存证流水号",
  "CONTRACT_VERIFY_LABEL_HEAD": "链头",
  "CONTRACT_VERIFY_LABEL_LINK": "连续性",
  "CONTRACT_VERIFY_LABEL_SEQ": "序号",
  "CONTRACT_VERIFY_CD_PREFIX": "#CD",
  "CONTRACT_VERIFY_ENTRY_UNIT": "条",
  "ADMIN_POSTS_EMPTY": "还没有教师发布资料，新帖子会出现在这里。",
  "PAGE_ADMIN_CONTRACTS": "合同管理",
  "PAGE_ADMIN_CONTRACTS_DESC": "查看全站合同与状态，仅用于处理异常数据",
  "ADMIN_CONTRACTS_EMPTY": "还没有合同记录。",
  "BTN_REMOVE_CONTRACT": "移除合同",
  "CONFIRM_ADMIN_REMOVE_CONTRACT": "移除后合同彻底删除（操作留档保留）。确定移除该合同吗？",
  "ADMIN_CONTRACT_REMOVED_TOAST": "合同已移除",
  "PAGE_ABOUT": "关于平台",
  "PAGE_ABOUT_DESC": "平台介绍与用户支持",
  "ABOUT_FOOTNOTE": "平台由上海财经大学学生团队维护。有建议或遇到问题，可以到「关于平台」-「{feedback}」告诉我们，我们会逐条看。",
  "ABOUT_WHO_TITLE": "我们是谁",
  "ABOUT_WHO_TEXT": "经途·伴学信息门户是由上海财经大学在校学生的家教团体运营的公益信息平台。我们的初衷很简单：为想做家教的同学（尤其是持有教师资格证的在校大学生与研究生）提供勤工俭学、社会实践的机会，也帮家长和同学直接对接合适的老师，中间不赚一分钱差价。平台不开展任何有偿培训业务，不向老师收取佣金，也不向家长学员收取任何中介费用。为响应国家「双减」政策，我们谢绝在职老师及校外培训机构注册与合作。",
  "ABOUT_FUNDS_TITLE": "关于费用",
  "ABOUT_FUNDS_TEXT": "平台是公益信息平台，仅提供信息撮合与合同存证服务，不参与任何费用结算，也不从任何交易中抽成。课时费的金额与支付方式由你与老师/学员自行协商，并在站外直接结算（如微信、支付宝转账）。请勿向平台支付任何费用。",
  "ABOUT_USAGE_TITLE": "平台基本用法",
  "ABOUT_FLOW_STEP_1": "发布需求：填写年级、科目与预算，发布你的家教需求",
  "ABOUT_FLOW_STEP_2": "对接教师：把需求直接发给心仪的教师，或等待教师发来试课意向",
  "ABOUT_FLOW_STEP_3": "确认开聊：对方确认后自动开启会话，在站内沟通课程细节",
  "ABOUT_FLOW_STEP_4": "起草合同：在会话中起草家教服务合同，约定时间、地点与课时费",
  "ABOUT_FLOW_STEP_5": "双方签约：到「我的合同」确认签署，按约开始上课",
  "ABOUT_SECURITY_TITLE": "安全与隐私保护",
  "ABOUT_SECURITY_INTRO": "我们把大家的信息安全看得很重。下面这些保护，是为了让你和家长都能安心使用：",
  "ABOUT_SECURITY_ITEMS": [
    {
      "t": "密码加密保管",
      "d": "注册密码经过高强度加密后才存进数据库，任何人（包括我们自己）都看不到你的原始密码。"
    },
    {
      "t": "登录不反复传密码",
      "d": "登录后用一次性加密凭证通行，密码不会一次次在网络上传输；还能在「账户设置」里随时让别的设备下线。"
    },
    {
      "t": "联系方式先藏起来",
      "d": "微信、电话等联系方式要等双方签约后才向对方展示，在此之前谁也看不到，不怕被陌生人骚扰。"
    },
    {
      "t": "个人信息按需可见",
      "d": "真实姓名、学籍认证材料只在双方建立联系之后才互相展示，平时对所有人隐藏。"
    },
    {
      "t": "地址只到街道一级",
      "d": "平台只收集、保存、展示到区/镇/街道一级，从不收集详细门牌地址，上课地点由双方自行商量约定。"
    },
    {
      "t": "合同防篡改存证",
      "d": "签好的合同会生成加密存证并环环相扣，一旦签署就没法被悄悄改动，对双方都是保障。"
    },
    {
      "t": "全程加密传输",
      "d": "你和网站之间往来的所有数据都走加密通道，防止半路被人偷看。"
    },
    {
      "t": "自动抵御恶意试探",
      "d": "对频繁尝试登录、批量注册等异常行为，系统会自动限流并临时封禁，守护账户安全。"
    }
  ],
  "ABOUT_SUPPORT_TITLE": "用户支持",
  "ABOUT_SUPPORT_OWNER": "平台负责人：康同学",
  "ABOUT_SUPPORT_WECHAT": "微信：13524121020",
  "ABOUT_SUPPORT_EMAIL": "邮箱：support_sufe_tutor@163.com",
  "BTN_FEEDBACK": "用户反馈",
  "BTN_COMPLAINT_FEEDBACK": "投诉与反馈",
  "FEEDBACK_CHOOSE_BUG": "我要反馈 Bug",
  "FEEDBACK_CHOOSE_SUGGESTION": "我要提出建议",
  "FEEDBACK_CHOOSE_COMPLAINT": "我要投诉",
  "FEEDBACK_MODAL_TITLE_BUG": "反馈 Bug",
  "FEEDBACK_MODAL_TITLE_SUGGEST": "提出建议",
  "FEEDBACK_TITLE_PLACEHOLDER": "一句话概括你的问题或建议",
  "FEEDBACK_PLACEHOLDER": "详细描述你遇到的问题或建议（支持轻量 Markdown）",
  "FEEDBACK_EMPTY": "反馈内容不能为空",
  "FEEDBACK_SENT_TOAST": "反馈已提交，感谢你的声音",
  "BTN_MY_COMPLAINTS_FEEDBACK": "我的投诉与反馈",
  "FEEDBACK_COMPLAINT_SUBJECT_TEACHER": "教师",
  "FEEDBACK_COMPLAINT_SUBJECT_STUDENT": "学生",
  "FEEDBACK_COMPLAINT_SUBJECT_PLATFORM": "平台服务",
  "MY_FEEDBACK_TITLE": "我的投诉与反馈",
  "MY_FEEDBACK_EMPTY": "还没有提交过反馈或投诉",
  "PAGE_ADMIN_FEEDBACK": "用户反馈",
  "PAGE_ADMIN_FEEDBACK_DESC": "查看并处理用户提交的问题与建议（投诉在独立页处理）",
  "ADMIN_FEEDBACK_EMPTY": "还没有用户反馈，新的问题和建议会出现在这里。",
  "FEEDBACK_TAG_BUG": "Bug",
  "FEEDBACK_TAG_SUGGEST": "建议",
  "FEEDBACK_TAG_COMPLAINT": "投诉",
  "FEEDBACK_STATUS_OPEN": "未处理",
  "FEEDBACK_STATUS_RESOLVED": "已处理",
  "BTN_MARK_RESOLVED": "标记已处理",
  "FEEDBACK_RESOLVED_TOAST": "已标记处理并通知提出者",
  "COMPLAINT_MODAL_TITLE": "提交投诉",
  "COMPLAINT_TAB_TEACHER": "投诉教师",
  "COMPLAINT_TAB_STUDENT": "投诉学生",
  "COMPLAINT_TAB_POST": "投诉帖子",
  "COMPLAINT_RECENT_LABEL": "最近联系的人",
  "COMPLAINT_SEARCH_PLACEHOLDER": "输入 id 或昵称搜索",
  "COMPLAINT_SEARCH_POST_PLACEHOLDER": "输入帖子 id 或标题搜索",
  "COMPLAINT_SEARCH_EMPTY": "未找到匹配对象，可输入 id 精确搜索",
  "COMPLAINT_TARGET_REQUIRED": "请选择要投诉的对象",
  "COMPLAINT_REASON_REQUIRED": "请选择投诉理由",
  "COMPLAINT_REASON_LABEL": "投诉理由",
  "SELECT_PROVINCE_FIRST": "请先选择地区",
  "COMPLAINT_SELECTED_PREFIX": "已选择：",
  "COMPLAINT_CHANGE_TARGET": "更换",
  "COMPLAINT_REASON_PLACEHOLDER": "请选择理由",
  "COMPLAINT_DETAIL_LABEL": "补充描述",
  "COMPLAINT_DETAIL_PLACEHOLDER": "补充具体问题、发生时间等（选填，支持轻量 Markdown）",
  "COMPLAINT_REASONS": [
    "虚假信息或欺诈",
    "侮辱谩骂或骚扰",
    "侵犯隐私",
    "违法违规内容",
    "恶意营销或广告",
    "其他"
  ],
  "COMPLAINT_SENT_TOAST": "投诉已提交，我们会尽快核实处理",
  "COMPLAINT_STATUS_OPEN": "处理中",
  "COMPLAINT_STATUS_RESOLVED": "已处理",
  "COMPLAINT_ATTACH_LABEL": "上传附件（选填，最多 4 个，图片可上传 4 张以下）",
  "COMPLAINT_ATTACH_ADD": "添加附件",
  "COMPLAINT_ATTACH_TOO_MANY": "附件最多 4 个",
  "COMPLAINT_ATTACH_UPLOADING": "请等待附件上传完成",
  "COMPLAINT_ATTACH_FAIL": "附件加载失败",
  "PAGE_ADMIN_COMPLAINT": "投诉处理",
  "PAGE_ADMIN_COMPLAINT_DESC": "查看并处理用户提交的投诉（对象 / 理由 / 详情）",
  "ADMIN_COMPLAINT_EMPTY": "还没有投诉记录，新投诉会出现在这里。",
  "BTN_COMPLAINT_RESOLVE": "标记已处理",
  "PAGE_ADMIN_CONTENT": "内容审核",
  "PAGE_ADMIN_CONTENT_DESC": "集中查看全站用户内容，可删除违规内容或封禁作者",
  "ADMIN_CONTENT_EMPTY": "当前筛选条件下没有内容。",
  "ADMIN_CONTENT_PENALTY_DELETE": "删除",
  "ADMIN_CONTENT_PENALTY_BAN": "封禁作者",
  "ADMIN_CONTENT_PENALTY_REASON": "处罚原因（必填）",
  "ADMIN_CONTENT_PENALTY_RULE": "触犯规则",
  "ADMIN_CONTENT_TYPE_POST": "帖子",
  "ADMIN_CONTENT_TYPE_DEMAND": "需求",
  "ADMIN_CONTENT_TYPE_TEACHER": "教师档案",
  "ADMIN_CONTENT_TYPE_REVIEW": "评价",
  "ADMIN_CONTENT_TYPE_MESSAGE": "聊天",
  "ADMIN_CONTENT_TYPE_FEEDBACK": "反馈",
  "ADMIN_CONTENT_TYPE_COMPLAINT": "投诉",
  "ADMIN_CONTENT_TYPE_UPLOAD": "附件",
  "ADMIN_CONTENT_TYPE_CONTRACT": "合同",
  "ADMIN_STAT_TOTAL_USERS": "总用户",
  "ADMIN_STAT_STUDENTS": "学生",
  "ADMIN_STAT_TEACHERS": "教师",
  "ADMIN_STAT_PROFILES": "教师档案",
  "ADMIN_STAT_DEMANDS": "学生需求",
  "ADMIN_SECTION_REVIEWS": "评价",
  "ADMIN_STAT_REVIEWS_TOTAL": "总数",
  "ADMIN_STAT_REVIEWS_APPROVED": "已通过",
  "ADMIN_STAT_REVIEWS_PENDING": "待审核",
  "ADMIN_STAT_REVIEWS_REJECTED": "已拒绝",
  "ADMIN_SECTION_INVITES": "邀请码",
  "ADMIN_STAT_INVITES_USED": "已使用",
  "ADMIN_STAT_INVITES_ACTIVE": "可用",
  "ADMIN_SECTION_TODO": "待办",
  "ADMIN_STAT_VERIFY_PENDING": "待核验教师",
  "ADMIN_STAT_AWARDS_PENDING": "待发奖学金",
  "ADMIN_STAT_FEEDBACKS_OPEN": "未处理反馈",
  "ADMIN_STAT_COMPLAINTS_OPEN": "未处理投诉",
  "ADMIN_SECTION_TRAFFIC": "请求指标",
  "ADMIN_STAT_REQUESTS": "请求数",
  "ADMIN_STAT_ERRORS": "5xx",
  "ADMIN_STAT_SLOW": "慢请求",
  "ADMIN_STAT_LIMITED": "限流",
  "ADMIN_STAT_AVG_MS": "平均延迟(ms)",
  "ADMIN_SECTION_TOP_PATHS": "热点路径",
  "ADMIN_SECTION_STATUS": "状态分布",
  "ADMIN_CONTENT_TYPE_SIGNING": "签约请求",
  "COMPLAINT_RESOLVED_TOAST": "已标记处理并通知投诉人",
  "SETTINGS_AVATAR": "账户头像",
  "BTN_UPLOAD_AVATAR": "上传头像",
  "AVATAR_SAVED_TOAST": "头像已更新",
  "PUSH_BTN_COOLDOWN": "已发送",
  "SCORE_UNIT": "分",
  "LOADING": "加载中...",
  "OPTION_PLACEHOLDER": "请选择",
  "CONTACT_PLACEHOLDER": "手机邮箱",
  "VALIDATE_SELECT_PROVINCE": "请选择省份",
  "BTN_PREV_STEP": "上一步",
  "BTN_BACK_LANDING": "返回首页",
  "BTN_NEXT_STEP": "下一步",
  "VALIDATE_SELECT_GRADE": "请选择学生年级",
  "VALIDATE_ADDRESS_REQUIRED": "请选择所在区与镇/街道",
  "VALIDATE_BUDGET_RANGE": "预算区间有误：最低价不能高于最高价",
  "VALIDATE_CONTACT_REQUIRED": "请填写家长与学生联系方式",
  "VALIDATE_TEACHER_PROFILE_REQUIRED": "请完善教师档案必填项：省份、年级、性别、擅长科目、报价与授课方式均需填写",
  "VALIDATE_SELECT_SUBJECTS": "请选择擅长科目",
  "VALIDATE_SELECT_PRICE": "请填写报价区间",
  "VALIDATE_SELECT_TIME_SLOTS": "请选择可授课时间段",
  "DW_STEP_PROVINCE": "省份",
  "DW_STEP_METHOD": "教学方式",
  "DW_STEP_STUDENT": "学生概况",
  "DW_STEP_SUBJECTS": "科目",
  "DW_STEP_SCORES": "成绩情况",
  "DW_STEP_TEACHER_PREF": "教师偏好",
  "DW_STEP_BUDGET": "预算与时间",
  "DW_STEP_SUBMIT": "补充信息",
  "PAGE_MY_DEMANDS": "我的需求",
  "PAGE_BROWSE_TEACHERS": "浏览教师",
  "PAGE_MY_CHATS": "我的会话",
  "PAGE_BROWSE_DEMANDS": "需求大厅",
  "PAGE_RESOURCE_SHARE": "资料共享",
  "PAGE_TEACHER_PROFILE": "教师档案",
  "PAGE_ADMIN_STATS": "统计",
  "PAGE_ADMIN_TRAFFIC": "流量监测",
  "PAGE_ADMIN_STUDENTS": "学生管理",
  "PAGE_ADMIN_TEACHERS": "教师管理",
  "PAGE_ADMIN_DEMANDS": "需求管理",
  "PAGE_ADMIN_REVIEWS": "评价管理",
  "PAGE_ADMIN_AWARDS": "奖项审核",
  "PAGE_ADMIN_POSTS": "资料管理",
  "PAGE_MY_DEMANDS_DESC": "发布与管理家教需求",
  "PAGE_BROWSE_TEACHERS_DESC": "筛选教师，查看详情与评价",
  "PAGE_MY_CHATS_DESC": "与匹配的师生在线沟通",
  "PAGE_BROWSE_DEMANDS_DESC": "浏览学生需求并提交意向",
  "PAGE_RESOURCE_SHARE_DESC": "与同行共享教学资源",
  "PAGE_TEACHER_PROFILE_DESC": "完善教师档案与高考成绩",
  "PAGE_ADMIN_STATS_DESC": "平台运行数据总览",
  "PAGE_ADMIN_TRAFFIC_DESC": "站点流量与平均延迟",
  "PAGE_ADMIN_STUDENTS_DESC": "学生账户与封禁管理",
  "PAGE_ADMIN_TEACHERS_DESC": "教师账户与封禁管理",
  "PAGE_ADMIN_DEMANDS_DESC": "全平台需求管理",
  "PAGE_ADMIN_REVIEWS_DESC": "评价审核与删除",
  "PAGE_ADMIN_POSTS_DESC": "管理教师共享的资料帖子",
  "PAGE_NOTIFICATIONS_DESC": "意向与推送的处理进展",
  "PAGE_ACCOUNT_SETTINGS_DESC": "外观主题与账户设置",
  "MODULE_INFO_TIP": "模块介绍",
  "MODULE_INFO": {
    "my-demands": "## 这是什么\n你的家教需求管理中心：发布、查看、修改需求，并处理老师发来的试课意向。\n\n## 怎么用\n**新建需求：** 点右上角「新建需求」，按引导填写学科或非学科项目、年级、预算、期望时间等，提交后需求即发布到需求广场，老师能看到并投递意向。\n\n**处理意向：** 发布后，老师对这条需求的试课意向会逐条出现在需求下方。点开可看到老师姓名、擅长科目与报价，逐个同意或拒绝。\n\n**管理需求：** 已签约或想下架的需求可编辑或删除；撤销的需求可以重新开放。\n\n## 小贴士\n资料填得越完整，匹配到的老师越精准，越容易被选中。",
    "browse-teachers": "## 这是什么\n全平台教师列表，学生端默认按与你需求的匹配度从高到低排列。\n\n## 怎么用\n**筛选：** 用上方筛选按地区、科目、性别、报价等缩小范围。\n\n**看卡片：** 每张卡片展示老师的学校年级、擅长科目、高考成绩、授课方式与报价；右侧匹配度按钮会列出你每个需求的具体得分。\n\n**看详情：** 点卡片任意处打开完整资料卡，含性格关键词、可授课时间段与历史评价。\n\n## 小贴士\n满意的老师可直接把需求发给他，或先进会话聊一聊再决定。",
    "my-chats": "## 这是什么\n与老师/学生一对一沟通的聊天窗口，所有交流都会留档。\n\n## 怎么用\n**会话列表：** 左侧是全部会话，点开即可收发文字、图片和文件，消息会自动同步。\n\n**对方资料：** 右上角人头图标可打开对方资料卡。\n\n**签约入口：** 聊天里的「+」号可呼出发起签约或起草合同，谈妥后在这里确认签约关系。",
    "my-contracts": "## 这是什么\n合同管理区：起草、确认、签署与撤销都在这里完成。\n\n## 怎么用\n**起草签约：** 在会话里谈妥条件后，起草合同并选择对应的已签约需求，双方确认后正式签约。\n\n**查看修改：** 每张合同卡显示签约对象、授课方式、时薪与状态；可查看正式合同全文、修改条款。\n\n**存证与撤销：** 已签合同可查存证；确需结束时按流程撤销。\n\n## 小贴士\n合同签好即具有法律效力，是双方权益的保障，签署前请仔细核对条款。",
    "notifications": "## 这是什么\n平台各类提醒的汇总页：试课意向、学生推送的需求、签约与合同进展都会通知到这里。\n\n## 怎么用\n**查看：** 每条通知可直接看到内容，处理过的意向与需求去「我的需求」查看状态。\n\n**屏蔽公告：** 右上角「屏蔽系统通知」可一键过滤平台公告类消息，再点一次恢复。",
    "account-settings": "## 这是什么\n账户与外观设置页。\n\n## 怎么用\n**账户信息：** 查看用户名与身份，上传头像，管理已登录设备——发现陌生设备可随时踢下线。\n\n**外观设置：** 切换亮色/暗色/跟随系统主题；用「UI大小」滑块整体调整字号、按钮与侧边栏尺寸。\n\n**退出与注销：** 页面底部是退出登录（二次确认）与注销账户（需密码二次认证，注销后数据会被清理）。",
    "about": "## 这是什么\n平台介绍与帮助中心，也是了解平台理念与规则的地方。\n\n## 怎么用\n**阅读：** 平台理念、基本签约流程、安全与隐私说明、版本更新记录都在这里。\n\n**反馈：** 页面下方有反馈入口，遇到 Bug 或有建议可留给我们。\n\n**重温引导：** 「重温新手引导」按钮随时可以再看一遍各模块的用法。",
    "browse-demands": "## 这是什么\n学生发布的全部家教需求，教师端默认按与你档案的匹配度从高到低排列。\n\n## 怎么用\n**筛选：** 用上方筛选按年级、科目、地区、预算等缩小范围。\n\n**看需求：** 每张需求卡展示学生年级、目标科目、当前成绩、期望时间与预算区间。\n\n**投递意向：** 看中的需求点「提交试课意向」，系统先弹二次确认避免误发海投；确认后学生收到并决定是否同意。\n\n## 小贴士\n档案越完整匹配度越高，越容易被学生选中；「学生主动发给你的需求」会置顶展示，记得及时处理。",
    "resource-share": "## 这是什么\n教师之间共享教学资源的交流区。\n\n## 怎么用\n**发布：** 顶部可发布图文帖子，分享课件、讲义或教学心得。\n\n**浏览：** 列表可按搜索与排序浏览同行分享的资料，看到有用的可以点赞。\n\n## 小贴士\n发布时注意不要包含他人隐私信息。",
    "teacher-profile": "## 这是什么\n完善你的教师档案——资料越完整，匹配度越高、越容易被学生选中。\n\n## 怎么用\n按四个大区填写：\n\n**基本资料：** 地区、年级、学校、性别。\n\n**学科资料：** 擅长科目、按毕业省份政策填写的高考成绩、报价区间。\n\n**非学科资料：** 可教的项目与各自报价。\n\n**私密资料：** 微信等联系方式，仅在你与对方建立会话/签约后展示。\n\n## 小贴士\n填完点保存即时生效；毕业年份决定高考成绩按哪年政策计算，请如实填写。",
    "admin-stats": "## 这是什么\n平台运行数据总览。\n\n## 怎么用\n展示注册用户数、需求数、合同数等核心指标，快速把握平台整体活跃情况。数据为实时统计，定期刷新即可掌握最新状态。",
    "admin-traffic": "## 这是什么\n站点流量与延迟监测。\n\n## 怎么用\n查看访问量与 API 响应时间，及时发现异常波动。延迟异常时优先排查网络与服务端健康状态。",
    "admin-students": "## 这是什么\n学生账户管理。\n\n## 怎么用\n查看全部学生列表，可封禁或解封违规账户，维护平台秩序。封禁前请先确认违规证据。",
    "admin-teachers": "## 这是什么\n教师账户管理。\n\n## 怎么用\n查看全部教师列表，处理学籍认证审核，封禁/解封违规账户。",
    "admin-demands": "## 这是什么\n全平台需求管理。\n\n## 怎么用\n查看所有用户发布的需求，可删除违规内容，维护广场秩序。",
    "admin-reviews": "## 这是什么\n评价审核与删除。\n\n## 怎么用\n用户提交的评价先在这里审核，通过的才会公开；违规内容可删除或拒绝。",
    "admin-awards": "## 这是什么\n教师荣誉奖项审核。\n\n## 怎么用\n教师上传奖状证明提交奖项，管理员在此人工核对后通过或驳回；通过的奖项才展示在教师主页。",
    "admin-posts": "## 这是什么\n资料帖子管理。\n\n## 怎么用\n查看教师共享的资料帖子，删除含隐私或违规信息的帖子。",
    "admin-contracts": "## 这是什么\n合同管理。\n\n## 怎么用\n查看平台全部合同与状态，必要时移除测试或异常数据。",
    "admin-feedback": "## 这是什么\n用户反馈处理。\n\n## 怎么用\n查看用户提交的 Bug 与建议，逐条查看详情并标记处理状态。",
    "admin-complaint": "## 这是什么\n投诉处理。\n\n## 怎么用\n查看用户提交的投诉——投诉对象（教师/学生/帖子）、理由与详情都会快照存档，即使对象已注销或删除也不影响追溯。\n\n**处理：** 逐条核实后点「标记已处理」，系统会通知投诉人处理结果。\n\n## 小贴士\n投诉是独立的合规通道，与用户反馈分开管理；处理时先核实快照信息与聊天记录，再决定如何处置。",
    "admin-content": "## 这是什么\n全站统一内容审核界面：一声令下看到平台所有用户可操作的内容，一声令下完成处罚。\n\n## 怎么用\n**看内容：** 上方按类型切换（帖子/需求/教师档案/评价/聊天/反馈/投诉/附件），每张卡片展示作者、内容摘要与状态。\n\n**处罚：** 点卡片右侧按钮，填写处罚原因（必填）与触犯规则，可「删除」该内容或「封禁作者」——处罚后系统会自动把原因、规则与触发内容摘要通知给作者本人。\n\n## 小贴士\n处罚前先核实触发内容与聊天上下文；封禁会同时阻止该账户继续登录。"
  },
  "MODAL_TITLE_DEMAND_CREATE": "提交学生需求",
  "MODAL_TITLE_DEMAND_EDIT": "编辑学生需求",
  "HINT_SELECT_TARGET_SUBJECTS": "请先选择目标科目",
  "HINT_SELECT_PROVINCE_GRADE": "请先选择省份和年级",
  "HINT_SELECT_PROVINCE_GAOKAO": "请先选择省份（高考所在地），按该省政策填写高考成绩",
  "INTENT_STATUS_PENDING": "待处理",
  "INTENT_STATUS_ACCEPTED": "已同意",
  "INTENT_STATUS_REJECTED": "已拒绝",
  "EMPTY_NO_INTENTS": "还没有教师提交意向。收到意向后，可以在这里同意或拒绝。",
  "INTENT_ACCEPTED_TOAST": "已同意，可在「我的会话」中开始对话",
  "INTENT_REJECTED_TOAST": "已拒绝该意向",
  "REVIEW_MODAL_TITLE_PREFIX": "评价 ",
  "REVIEW_STATUS_AUDITING": "审核中",
  "REVIEW_REJECTED_HINT": "未通过，可修改后重新提交",
  "BTN_EDIT_REVIEW": "修改评价",
  "BTN_SUBMIT_REVIEW": "提交评价",
  "CONTACT_AFTER_SIGN_NOTE": "签约后展示联系方式",
  "CONTRACT_SUBJECT_LINE_PREFIX": "授课科目：",
  "TAG_BANNED": "已封禁",
  "CHAT_TITLE": "会话",
  "CHAT_EMPTY_NO_CONVS": "还没有会话。学生同意教师试课意向、或教师确认学生推送后，会话会自动建立。",
  "CHAT_ROLE_STUDENT": "学生",
  "CHAT_ROLE_TEACHER": "教师",
  "CHAT_CONV_NOT_FOUND": "未找到与该学生的会话",
  "CHAT_EMPTY_NO_MESSAGES": "还没有消息，先打个招呼吧",
  "CHAT_PREVIEW_ME_PREFIX": "我：",
  "CHAT_PREVIEW_IMAGE": "[图片]",
  "CHAT_PREVIEW_FILE": "[文件]",
  "CHAT_UNKNOWN_USER": "未知用户",
  "CHAT_BACK_TO_LIST": "会话列表",
  "CHAT_CLOSED_TIP": "会话已结束，不能再发消息。如需继续沟通，请重新发起会话或走合同流程。",
  "CHAT_SIGN_TIP": "双方已确认签约，建议在「我的合同」里起草正式合同。\n平台不代收代付，课费请与对方协商后站外结算。",
  "CHAT_ATTACH_IMAGE": "图片",
  "CHAT_ATTACH_FILE": "文件",
  "CHAT_INPUT_PLACEHOLDER": "输入消息",
  "CHAT_BTN_SEND": "发送",
  "CHAT_FILE_TOO_LARGE": "文件太大（上限 500KB，图片会自动压缩）",
  "CHAT_DOWNLOAD": "下载",
  "CHAT_FILE_FALLBACK": "文件",
  "CHAT_STAGE_WAIT": "请等待文件处理完成再发送",
  "CHAT_DROP_HINT": "松开加入发送",
  "CHAT_ATTACH_FAIL": "附件加载失败",
  "CHAT_ATTACH_REMOVED": "附件已被发送方移除",
  "CHAT_PLACEHOLDER_TITLE": "选择左侧会话，开始沟通",
  "CHAT_PLACEHOLDER_SUB": "同意试课意向后自动建立会话，消息会自动同步",
  "POSTS_SEARCH_PLACEHOLDER": "搜索标题或正文",
  "POSTS_SORT_NEW": "最新优先",
  "POSTS_SORT_HOT": "最热优先",
  "BTN_CREATE_POST": "发布帖子",
  "POSTS_EMPTY": "还没有帖子，分享一份教学资料，帮到更多同行。",
  "POST_BTN_DELETE": "删除",
  "BTN_CONFIRM_DELETE": "确认删除",
  "POST_ANONYMOUS": "匿名",
  "POST_LIKE_ARIA": "点赞",
  "POST_VIEW_ARIA": "查看帖子全文",
  "POST_LIKED_TOAST": "已点赞",
  "POST_UNLIKED_TOAST": "已取消点赞",
  "POSTS_VIEW_FAV": "我的收藏",
  "POSTS_FAV_ACTIVE": "已进入我的收藏",
  "BTN_FAVORITE": "收藏",
  "BTN_FAVORITED": "已收藏",
  "POST_FAV_ARIA": "收藏",
  "POST_FAVORITED_TOAST": "已收藏，可在「我的收藏」查看",
  "POST_UNFAVORITED_TOAST": "已取消收藏",
  "POSTS_FAV_EMPTY": "还没有收藏，看到有用的教学资料点一下书签图标，收藏后在这里随时查看。",
  "POST_MODAL_TITLE_CREATE": "发布帖子",
  "POST_LABEL_TITLE": "标题",
  "POST_TITLE_PLACEHOLDER": "一句话概括分享内容",
  "POST_LABEL_BODY": "正文",
  "POST_MD_BOLD": "加粗",
  "POST_MD_IMAGE": "插入图片",
  "POST_BODY_PLACEHOLDER": "支持轻量 Markdown：## 大标题、### 小标题、**加粗**、插入图片（图片以本地文件嵌入）",
  "POST_PREVIEW_TITLE": "预览效果",
  "POST_PREVIEW_BTN": "预览效果",
  "POST_PREVIEW_EMPTY": "暂无内容，点击「预览效果」查看渲染结果",
  "POST_MD_BOLD_DEFAULT": "加粗文本",
  "POST_IMAGE_ONLY": "请选择图片文件",
  "POST_IMAGE_ALT": "图片",
  "POST_IMG_BLOCKED": "[图片：链接未放行，不予渲染]",
  "POST_TITLE_REQUIRED": "标题不能为空",
  "POST_TITLE_TOO_LONG": "标题不能超过 60 个字符",
  "POST_BODY_TOO_LONG": "正文不能超过 20000 个字符",
  "POST_DELETE_FORBIDDEN": "仅作者本人可删除该帖子",
  "POST_PUBLISHING": "发布中",
  "POST_PUBLISHED": "发布成功",
  "BTN_PUBLISH": "发布",
  "BTN_CLOSE": "关闭",
  "A11Y_VIEW_PROFILE": "查看该用户资料",
  "VERIFIED_BADGE": "✓ 已认证",
  "VERIFIED_TITLE": "已通过学籍认证",
  "POST_DELETE_TITLE": "删除帖子",
  "POST_DELETE_CONFIRM": "删除后不可恢复，点赞数据一并清空。确认删除这篇帖子？",
  "EMPTY_NO_NOTIFICATIONS": "还没有通知。试课意向、需求推送和合同进展都会汇总到这里。",
  "NOTIF_FILTER_EMPTY": "没有符合条件的通知",
  "NOTIF_READ_ARIA": "标记该条通知已读",
  "NOTIF_BLOCK_OFF": "屏蔽系统通知",
  "NOTIF_BLOCK_ON": "已屏蔽系统通知",
  "SETTINGS_APPEARANCE_TITLE": "外观设置",
  "SETTINGS_THEME_LABEL": "界面配色",
  "SETTINGS_THEME_HINT": "亮色、暗色或跟随系统自动切换",
  "SETTINGS_UI_SCALE_LABEL": "UI大小",
  "SETTINGS_UI_SCALE_HINT": "调整界面文字、按钮与输入组件的整体大小（{min}%~{max}%，默认 {def}%）",
  "SETTINGS_STYLE_LABEL": "页面风格",
  "SETTINGS_STYLE_HINT": "整站视觉风格：液态玻璃（毛玻璃+光影）／平面简约（纯色无磨砂，更轻快）",
  "STYLE_LIQUID": "液态玻璃",
  "STYLE_FLAT": "平面简约",
  "SETTINGS_ORB_LABEL": "背景光球",
  "SETTINGS_ORB_HINT": "背景漂移光球的显示效果：鲜艳=彩色柔光，淡雅=若有若无，隐藏=纯净底色",
  "SETTINGS_ORB_FLAT_HIDDEN": "（平面简约下强制隐藏）",
  "ORB_MODE_VIVID": "鲜艳",
  "ORB_MODE_ELEGANT": "淡雅",
  "ORB_MODE_HIDDEN": "隐藏",
  "THEME_LIGHT": "亮色",
  "THEME_DARK": "暗色",
  "THEME_SYSTEM": "跟随系统",
  "SETTINGS_ACCOUNT_TITLE": "账户设置",
  "SETTINGS_USERNAME": "账户用户名",
  "SETTINGS_ROLE": "账户角色",
  "SETTINGS_PHONE": "电话",
  "SETTINGS_EMAIL": "邮箱",
  "SETTINGS_UNBOUND": "未绑定",
  "AWARD_SECTION_TITLE": "荣誉奖项",
  "AWARD_ADD_BTN": "添加奖项",
  "AWARD_TITLE_LABEL": "奖项名称",
  "AWARD_TITLE_PLACEHOLDER": "如：全国高中数学联赛一等奖",
  "AWARD_ISSUER_LABEL": "颁发机构",
  "AWARD_ISSUER_PLACEHOLDER": "如：中国数学会",
  "AWARD_DATE_LABEL": "获奖时间",
  "AWARD_DATE_PLACEHOLDER": "如 2025-06（可选）",
  "AWARD_PROOF_LABEL": "奖状证明",
  "AWARD_PROOF_HINT": "上传奖状/获奖证书图片，管理员审核通过后公开展示",
  "AWARD_STATUS_PENDING": "待审核",
  "AWARD_STATUS_APPROVED": "已通过",
  "AWARD_STATUS_REJECTED": "已驳回",
  "AWARD_SUBMITTED": "奖项已提交，等待管理员审核",
  "FILE_TYPE_BLOCKED": "不支持的文件类型",
  "AWARD_COUNT_BADGE": "🏆 荣誉 ×{n}",
  "AWARD_EMPTY": "还没有添加奖项。提交获奖证明并审核通过后，会展示在教师主页。",
  "AWARD_DELETE_CONFIRM": "确定删除该奖项吗？删除后需重新提交审核。",
  "AWARD_REJECTED_NOTE_PREFIX": "驳回理由：",
  "BTN_SUBMIT": "提交",
  "BTN_SUBMITTING": "提交中...",
  "SUCCESS_DELETED": "已删除",
  "BTN_DELETE": "删除",
  "ADMIN_AWARD_APPROVE": "通过",
  "ADMIN_AWARD_REJECT": "驳回",
  "ADMIN_AWARD_REJECT_HINT": "驳回理由（必填，将通知教师）",
  "ADMIN_AWARD_PROOF_VIEW": "查看奖状",
  "ADMIN_AWARD_NONE": "当前没有待审核的奖项，新提交会出现在这里。",
  "ADMIN_PENALTY_REASON_PLACEHOLDER": "如：含详细门牌号，违反平台隐私红线",
  "ADMIN_PENALTY_RULE_PLACEHOLDER": "如：地址门控 / 内容安全",
  "ADMIN_PENALTY_CONFIRM": "将{action}该内容并通知作者，确认继续？",
  "ADMIN_PENALTY_DONE": "已处理",
  "ADMIN_CONTENT_PENALTY_TITLE": "处罚{type} #{id}",
  "ADMIN_CONTENT_PENALTY_HINT": "处罚后将自动通知作者，附上原因、规则与触发内容摘要。",
  "ADMIN_AWARD_TEACHER_LABEL": "教师",
  "COMPLAINT_REPORTER_LABEL": "投诉人",
  "ADMIN_AWARD_APPROVE_CONFIRM": "确定通过该奖项审核吗？通过后将展示在教师主页。",
  "ADMIN_AWARD_REJECT_CONFIRM": "确定驳回该奖项吗？理由将通知教师。",
  "ADMIN_AWARD_REJECT_PLACEHOLDER": "如：奖状模糊、无法辨认颁发机构",
  "BTN_MODIFY": "修改",
  "PHONE_LABEL": "手机号",
  "PHONE_PLACEHOLDER": "请输入中国大陆手机号",
  "EMAIL_LABEL": "邮箱",
  "EMAIL_PLACEHOLDER": "请输入邮箱",
  "CODE_LABEL": "验证码",
  "CODE_PLACEHOLDER": "输入验证码",
  "CODE_SEND": "发送验证码",
  "CODE_SEND_AGAIN": "{time}后重发",
  "CODE_SENT": "验证码已发送",
  "OTP_SCENE_BIND": "绑定验证",
  "OTP_SCENE_REGISTER": "注册验证",
  "OTP_SCENE_LOGIN": "登录验证",
  "OTP_PHONE_LABEL": "手机验证码",
  "OTP_EMAIL_LABEL": "邮箱验证码",
  "OTP_BIND_DONE": "绑定成功",
  "BTN_BIND": "绑定",
  "BIND_PHONE_TITLE": "绑定手机号",
  "BIND_EMAIL_TITLE": "绑定邮箱",
  "USERNAME_CHANGE_TITLE": "修改用户名",
  "USERNAME_NEW_PLACEHOLDER": "输入新用户名（3-30 字符，不含 @ 与纯数字）",
  "USERNAME_NEW_LABEL": "新用户名",
  "USERNAME_NEW_HINT": "修改后全平台即时更新；7 天内只能改一次。",
  "USERNAME_CHANGE_CONFIRM_FMT": "确定将用户名修改为「{name}」吗？修改后 7 天内不可再次修改。",
  "USERNAME_COOLDOWN": "用户名 7 天内只能修改一次",
  "USERNAME_COOLDOWN_BTN": "{time}后可再次修改用户名",
  "USERNAME_LENGTH_ERR": "用户名长度需在 3-30 个字符之间",
  "USERNAME_CHARS_ERR": "用户名只能包含中文、字母、数字及 _ . - （3-30 个字符），且不能为纯数字、不能含 @",
  "USERNAME_USE_PASSWORD": "用户名账户请使用密码登录",
  "CRED_IDENT_INVALID": "请输入有效的手机号或邮箱",
  "CRED_FORMAT_PHONE": "手机号格式不正确",
  "CRED_FORMAT_EMAIL": "邮箱格式不正确",
  "BTN_USERNAME_SAVE": "确认修改",
  "BTN_USERNAME_SAVING": "保存中...",
  "LOGIN_PASSWORD_REQUIRED": "请输入登录密码",
  "LOADING_VERIFY": "核验中…",
  "LOGIN_SWITCH_CODE": "验证码登录",
  "LOGIN_SWITCH_PASSWORD": "密码登录",
  "LOGIN_IDENTIFIER_PLACEHOLDER": "请输入用户名/手机号/邮箱",
  "LOGIN_ACCOUNT_MISSING": "没有找到这个用户名、手机号或邮箱。请检查输入；还没有账号的话，可以先注册。",
  "CAPTCHA_TITLE": "拖动滑块完成拼图",
  "CAPTCHA_TIP": "拖动滑块，将拼图块对齐到缺口位置",
  "CAPTCHA_PASS": "验证通过",
  "CAPTCHA_FAIL": "没对准缺口，再试一次",
  "CAPTCHA_ARIA": "拖动滑块完成拼图验证",
  "BTN_LOGOUT": "退出登录",
  "CONFIRM_LOGOUT": "退出后需要重新登录。确定退出当前账户吗？",
  "SETTINGS_DEVICES": "登录设备管理",
  "SETTINGS_PRIVACY_TITLE": "隐私设置",
  "SETTINGS_PRIVACY_ON": "允许",
  "SETTINGS_PRIVACY_OFF": "关闭",
  "SETTINGS_PRIVACY_PROFILE_LABEL": "允许访客浏览我的教师档案",
  "SETTINGS_PRIVACY_PROFILE_HINT": "关闭后，未登录的游客看不到你的资料卡，仅登录用户可见",
  "SETTINGS_PRIVACY_DEMAND_LABEL": "允许访客浏览我的需求",
  "SETTINGS_PRIVACY_DEMAND_HINT": "关闭后，未登录的游客看不到你发布的需求，仅登录用户可见",
  "SETTINGS_PRIVACY_SAVED": "隐私设置已保存",
  "SETTINGS_DEVICES_HINT": "以下是登录过此账户的设备，可让其他设备下线。",
  "SETTINGS_DEVICES_EMPTY": "当前只有这台设备登录。",
  "DEVICE_CURRENT": "当前设备",
  "DEVICE_UNKNOWN": "未知设备",
  "DEVICE_LOGIN_AT": "登录于 ",
  "BTN_DEVICE_LOGOUT": "下线",
  "DEVICE_REVOKE_CONFIRM": "确定要让该设备退出登录吗？该设备上的会话将立即失效。",
  "DEVICE_REVOKE_DONE": "该设备已下线",
  "ONBOARD_TITLE": "欢迎来到经途·伴学信息门户",
  "ONBOARD_INTRO": "学生和家教老师直接对接，零佣金、不收费；三步就能开始使用。",
  "ONBOARD_POLICY": [
    "学生：发布需求 → 浏览教师 → 匹配后站内沟通",
    "教师：浏览需求 → 提交试课意向 → 匹配后站内沟通",
    "匹配成功后在「我的会话」沟通上课细节，到「我的合同」正式签约",
    "平台不向老师或学生收取中介费，课费由双方自行结算"
  ],
  "ONBOARD_CONFIRM": "知道了",
  "ONBOARD_CONFIRM_BROWSE": "知道了，进客户端逛逛",
  "ONBOARD_REVISIT_BTN": "重温新手引导",
  "TOUR_SKIP_GLOBAL": "跳过引导",
  "TOUR_ARIA_LABEL": "新手引导",
  "TOUR_STEP_BROWSE_DEMANDS": "需求大厅：学生发布的家教需求都在这，按匹配度排好序。点击进入。",
  "TOUR_STEP_DEMAND_LIST": "这里就是需求列表。每张卡写着发起人、科目、年级、预算和上课方式，先看这几项判断是否合适。",
  "TOUR_STEP_DEMAND_CARD": "一条需求卡：期望时间、预算区间、授课方式都在上面，先看看合不合适。",
  "TOUR_STEP_DEMAND_DETAIL": "这是需求详情：学习目标、上课安排和学生信息都在这里，提交意向前先完整看一遍。",
  "TOUR_STEP_DEMAND_DETAIL_CLOSE": "点击关闭详情，回到需求列表。",
  "TOUR_DEMO_CHAT_NAME_TEACHER": "示例学生",
  "TOUR_DEMO_CHAT_NAME_STUDENT": "示例教师",
  "TOUR_DEMO_CHAT_PREVIEW": "示例会话：这里展示聊天窗口，还没有消息。",
  "TOUR_DEMO_CHAT_EMPTY": "示例会话：还没有消息，可以试试下方的输入框和 + 号。",
  "TOUR_DEMO_CONTRACT_TITLE": "示例合同",
  "TOUR_DEMO_CONTRACT_HINT": "这里展示合同卡片：对方、科目、报价与状态都在这里，操作按钮在下方。",
  "TOUR_DEMO_CONTRACT_VIEW": "查看合同",
  "TOUR_DEMO_CONTRACT_MODIFY": "修改合同",
  "TOUR_DEMO_CONTRACT_CONFIRM": "确认合同",
  "TOUR_STEP_DEMAND_INTENT_BTN": "「提交试课意向」按钮：觉得合适就点它，等学生确认后自动开启会话。",
  "TOUR_STEP_DEMAND_ID_TAG": "需求编号 #0001：沟通时用它指代这条需求，对方一看就知道是哪条。",
  "TOUR_STEP_BROWSE_TEACHERS": "教师广场：平台上的全部教师都在这，按匹配度从高到低排。点击进入。",
  "TOUR_STEP_BROWSE_TEACHERS_PEER": "教师同行：看看其他老师怎么介绍自己、怎么定价，可以用来调整自己的档案。",
  "TOUR_STEP_TEACHERS_LIST": "教师列表：每张卡片显示地区、学校、年级、报价区间、可授课时间。",
  "TOUR_STEP_FILTER_TOGGLE": "「筛选」按钮：按科目、报价上限、最低评分过滤教师。",
  "TOUR_STEP_TEACHER_USERNAME": "点老师的名片卡片（整卡可点），打开右侧资料栏看成绩、评价和联系方式规则。",
  "TOUR_STEP_PROFILE_CLOSE": "点右上角 ✕ 关闭资料栏，回到列表。",
  "TOUR_STEP_TEACHER_PUSH_BTN": "「发送需求」按钮：把你的需求直接发给这位老师。",
  "TOUR_STEP_PUSH_MODAL": "选一条你的需求发送过去，老师确认后自动开启会话。点击关闭。",
  "TOUR_STEP_RESOURCE_SHARE": "资料共享：同行分享教学资料的地方。点击进入。",
  "TOUR_STEP_POSTS_LIST": "资料列表：按最新 / 最热排序，浏览同行分享的帖子。",
  "TOUR_STEP_POSTS_SEARCH": "搜索框：输入关键词，快速找你想看的资料。",
  "TOUR_STEP_POSTS_SORT": "排序：最新优先 / 最热优先，随你切换。",
  "TOUR_STEP_POSTS_CREATE": "「发布帖子」按钮：分享一份教学资料，帮到更多同行。",
  "TOUR_STEP_POSTS_MODAL": "发布窗口：填标题和正文，支持 Markdown 和插入图片。点击关闭。",
  "TOUR_STEP_MY_CHATS": "我的会话：匹配成功后的沟通窗口，双方的联系方式此时互相不可见。点击进入。",
  "TOUR_STEP_CONV_ITEM": "左侧是会话列表，每个会话对应一位师生。点一个打开聊天窗。",
  "TOUR_STEP_CHAT_MESSAGES": "这里是聊天记录，消息会自动同步；聊天内容用于平台留档，联系方式此时仍互相不可见。",
  "TOUR_STEP_CHAT_SEND": "底部输入框打字，点「发送」；也支持图片和文件。",
  "TOUR_STEP_CHAT_PLUS": "点这个 + 号，唤出功能栏；下面的每一项都介绍一下。",
  "TOUR_STEP_CHAT_PLUS_IMAGE": "「图片」：把截图、错题照片直接发进会话，点开可看大图。",
  "TOUR_STEP_CHAT_PLUS_FILE": "「文件」：教案、资料 PDF 也能发——选文件后随消息发送。",
  "TOUR_STEP_CHAT_PLUS_SIGNING": "「发起签约」：谈妥了就在这里发起签约意向，对方确认后进入合同流程。",
  "TOUR_STEP_CHAT_PLUS_DRAFT": "「起草合同」：签约确认后，在这里起草正式合同条款发给对方。",
  "TOUR_STEP_MY_CONTRACTS": "我的合同：谈妥上课细节后，在这走正式签约，保障双方权益。点击进入。",
  "TOUR_STEP_CONTRACTS_LIST": "合同列表：每张卡片对应一份合同，带状态标签（待确认 / 签署中 / 已签）。",
  "TOUR_STEP_CONTRACT_CARD": "一张合同卡：看对方、科目、报价、关联需求编号。",
  "TOUR_STEP_CONTRACT_ACTIONS": "底部操作：确认签约、修改合同、查看合同。签好后联系方式才互相可见。",
  "TOUR_STEP_NOTIFICATIONS": "通知信息：试课意向、需求推送、合同进展都汇总在这。点击进入。",
  "TOUR_STEP_NOTIF_LIST": "通知列表：每条通知写着处理进展，点击未读通知即可标为已读。",
  "TOUR_STEP_NOTIF_ITEM": "一条通知：展示内容与时间；红点代表未读。",
  "TOUR_STEP_NOTIF_BLOCK": "右上角「屏蔽系统通知」：不想看系统广播点一下，再点恢复。",
  "TOUR_STEP_ACCOUNT_SETTINGS": "设置：账户设置与外观设置都在这里。点击进入。",
  "TOUR_STEP_SETTINGS_ACCOUNT": "账户设置区：头像、用户名、角色；可以上传头像。",
  "TOUR_STEP_SETTINGS_THEME": "界面配色：亮色、暗色或跟随系统自动切换。",
  "TOUR_STEP_SETTINGS_UI_SCALE": "UI 大小：拖动滑块整体调大调小界面文字和按钮。",
  "TOUR_STEP_SETTINGS_LOGOUT": "页底「退出登录」，注销账户也在这里。",
  "TOUR_STEP_SETTINGS_LOGOUT_MODAL": "退出前会再次确认；注销账户入口也在设置页底部，操作不可恢复。",
  "TOUR_STEP_ABOUT": "关于平台：平台理念、基本用法、安全隐私与反馈通道。点击进入。",
  "TOUR_STEP_ABOUT_WHO": "我们是谁：一句话介绍平台定位。",
  "TOUR_STEP_ABOUT_FLOW": "学生签约完整流程：发布需求 → 双向匹配 → 站内沟通 → 确认意向 → 正式签约。",
  "TOUR_STEP_ABOUT_SECURITY": "安全与隐私：联系方式签约后才展示，详细住址不收集，敏感资料加密存储。",
  "TOUR_STEP_ABOUT_FEEDBACK": "反馈通道：遇到问题或建议，点这里告诉我们。",
  "TOUR_STEP_MY_DEMANDS": "我的需求：你发布的家教需求都在这管理。点击进入。",
  "TOUR_STEP_MY_DEMANDS_LIST": "需求列表：每条显示科目、预算、状态；待处理的教师意向有红点提醒。",
  "TOUR_STEP_INTENT_TOGGLE": "展开「教师意向」：谁想来教，同意或拒绝都在这处理。",
  "TOUR_STEP_DEMAND_WIZARD": "发布需求是分步表单，跟着顶部进度条逐页填写；每页填完会自动进入下一页，随时可以返回修改。",
  "TOUR_STEP_NEW_DEMAND_BTN": "点「新建需求」打开发布表单。",
  "TOUR_STEP_NEW_DEMAND_MODAL": "表单共 8 步：省份 → 授课方式 → 学生信息 → 科目 → 成绩情况 → 教师偏好 → 预算时间 → 联系方式。顶部进度条随页推进，随时可返回修改。",
  "TOUR_STEP_GUEST_LOGIN": "到这里就逛完啦：点下方个人信息栏登录或注册，登录后就能使用全部功能。",
  "TOUR_STEP_ADMIN_DATA": "运营数据总览：平台统计与待办数据汇总在这个区域。",
  "TOUR_STEP_ADMIN_STATS": "统计页：平台运营数据总览。",
  "TOUR_STEP_ADMIN_TODO": "待办事项：待审核的评价、奖项与未处理反馈、投诉都汇总在这，点一下直达处理页。",
  "TOUR_STEP_ADMIN_AWARDS": "奖项审核：核对教师上传的奖状证明，通过后展示在教师主页；驳回时填理由通知教师。",
  "TOUR_STEP_ADMIN_CONTENT": "内容审核：全站内容统一提取与一键处罚（删除/封禁），处罚会自动通知作者。",
  "TOUR_STEP_ADMIN_END": "以上是管理端核心工作台。封禁、处罚、广播等危险操作都需要密码二次确认。",
  "TOUR_STEP_USER_BAR": "个人信息栏：点头像查看自己的信息；退出登录在「设置」页，想重温新手引导去「关于平台」页。",
  "USAGE_GUIDE_BTN": "详细用法介绍",
  "USAGE_GUIDE_TITLE": "详细用法介绍",
  "USAGE_GUIDE_SECTIONS": [
    {
      "t": "一、用户注册",
      "p": [
        "账户分为学生和教师两种，注册时需要设置用户名、密码，并绑定手机号或邮箱（需验证码验证）。教师注册还需要管理员发放的邀请码。"
      ]
    },
    {
      "t": "二、家教签约（主要功能）",
      "p": [
        "发布需求：学生在「我的需求」里填写年级、科目、预算等信息，发布一条家教需求。",
        "双向匹配：学生可在「浏览教师」页面把需求直接发给心仪的教师，等教师确认；教师也可以在「需求广场」里给感兴趣的需求发送试课意向，等学生确认。无论哪条路，只要对方点头，双方就自动开启会话。",
        "站内沟通：匹配成功后，双方在「我的会话」里沟通上课细节，支持发送图片和文件。这个阶段双方的联系方式互相不可见，所有交流都在站内、有留档。",
        "签约：会话里任一方点「+」发送一份合同草案，约定授课地点、方式、费用与双方权利义务；随后双方各自到「我的合同」里确认签署。合同具有法律效力，签好后双方的联系方式才会互相展示，之后转入站外沟通，撮合完成。"
      ]
    },
    {
      "t": "三、（教师端）资料共享",
      "p": [
        "这里用于教师之间分享教学资料，支持图文和 Markdown 排版。资料是公开的，学生也可以浏览。"
      ]
    },
    {
      "t": "四、（教师端）个人资料",
      "p": [
        "教师档案包含科目成绩、报价、可授课时间和获奖证明等，用来帮助学生判断是否合适。联系方式只在签约后展示，学信网信息仅管理员核验时查看。"
      ]
    },
    {
      "t": "五、设置",
      "p": [
        "可设置亮色/暗色外观、调整界面大小、更换头像、绑定手机或邮箱，以及查看和管理登录设备。"
      ]
    },
    {
      "t": "六、关于平台",
      "p": [
        "这里介绍平台定位、基本用法和安全隐私说明；有问题或建议，可以通过页面底部的反馈通道告诉我们。"
      ]
    },
    {
      "t": "七、其他小巧思",
      "p": [
        "从教师端看学生需求会有「匹配度」标签，点开能看到教师与这单需求的匹配度明细；后续计划把匹配度扩展成智能排序引擎。",
        "根据你设置的省份和年级，可选科目和赋分制也会不同。",
        "平台在数据安全和合规上下了很多功夫：用户数据加密存储，签署合同有验证流程，能保证合同在法律上有效。"
      ]
    }
  ],
  "LABEL_PROVINCE": "省份",
  "LABEL_STUDENT_GRADE": "学生年级",
  "LABEL_STUDENT_GENDER": "学生性别",
  "LABEL_TARGET_SUBJECTS": "目标科目",
  "LABEL_MULTI_SUFFIX": "（可多选）",
  "LABEL_TYPE_ACADEMIC": "学科辅导",
  "LABEL_TYPE_NONACADEMIC": "非学科培养",
  "BADGE_TYPE_ACADEMIC": "学科",
  "BADGE_TYPE_NONACADEMIC": "非学科",
  "LABEL_PREFERRED_PERSONALITY": "偏好老师性格",
  "LABEL_PREFERRED_GENDER": "偏好老师性别",
  "LABEL_TEACHING_GOAL": "教学目标",
  "TEACHING_GOALS_HINT": "（最多 {max} 个）",
  "LABEL_SKILL_STATUS": "技能现状",
  "SKILL_NOTE_PLACEHOLDER": "描述当前水平/证书/考级/获奖（选填）",
  "OPTION_GENDER_NOT_SAY": "不愿透露",
  "OPTION_PREF_GENDER_ANY": "不限",
  "LABEL_CURRENT_SCORES": "各科当前大概成绩",
  "LABEL_TEACHING_METHOD": "期望教学方式",
  "LABEL_ADDRESS": "地址（授课区域）",
  "ADDRESS_PLACEHOLDER": "选择所在区与镇/街道",
  "SH_ADDR_SELECT_DISTRICT_FIRST": "请先选择区",
  "LABEL_BUDGET": "预算区间（元/小时）",
  "PLACEHOLDER_MIN": "最低",
  "PLACEHOLDER_MAX": "最高",
  "LABEL_EXPECTED_TIME": "期望开课时间",
  "SLOT_ADD_LABEL": "新建时间段",
  "SLOT_DOW_PLACEHOLDER": "选择星期",
  "SLOT_TIME_START_GHOST": "开始时间",
  "SLOT_TIME_END_GHOST": "结束时间",
  "TIME_PICKER_ARIA": "选择整点时间",
  "TIME_DEL_ARIA": "删除该时间段",
  "VALIDATE_TIME_SLOT_INCOMPLETE": "请补全时间段（星期与起止时间），或删除不完整的时间段",
  "VALIDATE_TIME_SLOT_RANGE": "时间段的结束时间需晚于开始时间",
  "LABEL_SUBMITTER": "提交者身份",
  "LABEL_PARENT_CONTACT": "家长联系方式",
  "LABEL_STUDENT_CONTACT": "学生联系方式",
  "LABEL_ADDITIONAL_INFO": "其他补充信息",
  "DEMAND_DETAIL_GOAL": "学习目标",
  "DEMAND_DETAIL_ARRANGE": "上课安排",
  "DEMAND_DETAIL_STUDENT": "学生信息",
  "DEMAND_DETAIL_EMPTY": "未填写",
  "DEMAND_DETAIL_CONTACT_HINT": "签约后可查看联系方式",
  "DEMAND_INFO_PLACEHOLDER": "上课时间偏好、特殊要求等",
  "LABEL_RATING": "评分",
  "LABEL_REVIEW_CONTENT": "评价内容",
  "REVIEW_COMMENT_PLACEHOLDER": "请分享你的体验...",
  "SECTION_SUBJECTS": "擅长科目",
  "BTN_WRITE_REVIEW": "写评价",
  "BTN_VIEW": "查看",
  "BTN_AGREE": "同意",
  "INTENTS_TITLE": "试课意向",
  "MY_REVIEW_PREFIX": "你的评价：",
  "ADDRESS_PREFIX": "地址：",
  "REGISTERED_AT_PREFIX": "注册于 ",
  "DEMAND_COUNT_SUFFIX": " 条需求",
  "RATING_SCORE_SUFFIX": " 分",
  "ERROR_REQUEST_FAILED": "请求失败",
  "POST_DELETED": "帖子已删除",
  "ADMIN_TODO_TITLE": "待办事项",
  "ADMIN_TODO_REVIEWS": "待审核评价",
  "ADMIN_TODO_AWARDS": "待审核奖项",
  "ADMIN_TODO_FEEDBACKS": "未处理反馈",
  "ADMIN_TODO_COMPLAINTS": "未处理投诉",
  "ADMIN_TOTAL_USERS": "总用户",
  "ADMIN_STUDENTS": "学生",
  "ADMIN_TEACHERS": "教师",
  "ADMIN_DEMANDS": "需求数",
  "ADMIN_PROFILES": "教师档案",
  "ADMIN_REVIEWS_APPROVED": "已通过评价",
  "ADMIN_REVIEWS_PENDING": "待审评价",
  "ADMIN_INVITES_USED": "已用邀请码",
  "ADMIN_RECENT_USERS": "最近注册用户",
  "TRAFFIC_TITLE": "站点总流量",
  "TRAFFIC_LATENCY_TITLE": "平均延迟",
  "TRAFFIC_RANGE_24H": "24小时",
  "TRAFFIC_RANGE_7D": "近7天",
  "TRAFFIC_TOTAL_FMT": "合计 {n} 次",
  "TRAFFIC_SAMPLE_FMT": "样本 {n} 桶",
  "TRAFFIC_MS_UNIT": " ms",
  "CHART_EMPTY": "这段时间还没有采样数据。",
  "CHART_DEFAULT_TITLE": "折线图",
  "CHART_TABLE_LABEL": "数据明细",
  "CHART_TIME_LABEL": "时间",
  "TRAFFIC_RANGE_30D": "近30天",
  "TRAFFIC_HINT": "口径：仅统计写操作与失败请求（读/轮询流量不入留档）；平均延迟 = 服务端处理耗时",
  "ADMIN_RECENT_DEMANDS": "最近需求",
  "ADMIN_TODO_VERIFICATIONS": "待核验申请",
  "ADMIN_DASH_24H": "24 小时请求",
  "ADMIN_DASH_ERRORS": "服务端异常",
  "ADMIN_DASH_SLOW": "慢请求",
  "ADMIN_DASH_LIMITED": "限流命中",
  "ADMIN_DASH_AVG": "平均耗时",
  "ADMIN_DASH_AVG_FMT": "{n} ms",
  "ADMIN_DASH_TOP_PATHS": "高频接口（近 24 小时）",
  "ADMIN_DASH_STATUS": "状态码分布",
  "ADMIN_DASH_EMPTY": "指标采样刚开始，稍后就有数据。",
  "BTN_APPROVE": "通过",
  "BTN_REJECT": "拒绝",
  "REGION_HINT_FILL_MAIN": "在上方勾选擅长的主科后，在此填写成绩",
  "REGION_HINT_FILL_ELECTIVE": "在上方勾选擅长的选考科目后，在此填写成绩",
  "REGION_HINT_OFFLINE_ONLY": "目前只支持上海的线下教学",
  "REGION_HINT_PICK_PROVINCE": "请先选择高考所在省份",
  "REGION_HINT_PICK_GRADE": "请先选择年级，再选目标科目",
  "REGION_HINT_NO_SUBJECTS": "该地区暂无可选科目",
  "REGION_HINT_PICK_SUBJECTS": "请先选择目标科目",
  "REGION_SCORE_PLACEHOLDER": "分数",
  "REGION_GRADE_PLACEHOLDER": "请选择等第",
  "REGION_FIRST_SUBJECT_LABEL": "首选科目",
  "REGION_FIRST_TWO_HINT": "（二选一）",
  "REGION_STANDARD_SCORE_NOTE": "标准分",
  "GAOKAO_POLICY_MISMATCH_WARN": "检测到 {n} 条成绩按往年政策填写，当前政策无法匹配。请填写「毕业年份」切换到当年政策，否则保存后这些成绩将被移除。",
  "REGION_TRACK_SCIENCE": "理科",
  "REGION_TRACK_ARTS": "文科",
  "REGION_SH_ELECTIVE_MAX_NOTE": "上海选考满分 70",
  "REGION_TAB_GRADE": "等第制",
  "REGION_TAB_SCORE": "分数制",
  "UNIT_DAY": "天",
  "UNIT_HOUR": "时",
  "UNIT_MIN": "分",
  "UNIT_SEC": "秒",
  "LIST_SEP": "、",
  "EMPTY_DASH": "—",
  "PRICE_FROM_SUFFIX": "起",
  "PRICE_TO_PREFIX": "至",
  "APP_NAME": "经途·伴学信息门户",
  "LANDING_SUBTITLE": "零佣金家教信息共享平台",
  "LANDING_EYEBROW": "上海财经大学学生创立 · 运营至今",
  "LANDING_TAGLINE": "找家教零佣金更高效",
  "LANDING_COPY": "由上海财经大学学生团队运营。平台不向老师抽佣，也不向学生收费：发布需求、浏览教师、站内沟通、正式签约都在这里完成，课费由双方自行结算。",
  "LANDING_KICKER": "不抽佣 · 师生直接对接 · 信息透明",
  "LANDING_NOTE": "教师不抽佣 · 学生免费 · 课费双方自行结算",
  "LANDING_FOOTER": "© 2026 经途·伴学信息门户 · 由上财学生团队运营",
  "ENTRY_STUDENT_TITLE": "我要找家教",
  "ENTRY_STUDENT_DESC": "发布学习需求，浏览教师档案，匹配后直接沟通",
  "ENTRY_TEACHER_TITLE": "我要做家教",
  "ENTRY_TEACHER_DESC": "完善教师档案，浏览学生需求，确认意向后接单",
  "SIDEBAR_TOGGLE_ARIA": "展开/收起侧边栏",
  "SIDEBAR_NAV_ARIA": "主导航",
  "SIDEBAR_CLOSE": "关闭菜单",
  "BTN_NEW_DEMAND": "新建需求",
  "FILTER_TOGGLE": "筛选",
  "ADMIN_ADMISSION_IMAGE": "录取通知书",
  "ADMIN_AWARD_PROOF": "奖状证明",
  "ADMIN_BAN": "封禁用户",
  "ADMIN_BAN_CONFIRM": "确认封禁？",
  "ADMIN_DELETE_CONFIRM": "确认删除？",
  "ADMIN_DONE": "操作成功",
  "ADMIN_INVITE": "邀请码管理",
  "ADMIN_PENALTY": "内容处罚",
  "ADMIN_POST_VIEW": "帖子详情",
  "ADMIN_REASON": "处罚原因",
  "ADMIN_REASON_REQUIRED": "请填写处罚原因",
  "ADMIN_UNBAN_CONFIRM": "确认解封？",
  "BTN_BACK": "返回",
  "BTN_GO_REGISTER": "立即注册",
  "LOGIN_CODE_HINT": "验证码将发送到该账户绑定的手机或邮箱，5 分钟内有效，每天最多发送 10 次",
  "LOGIN_IDENTIFIER_LABEL": "用户名 / 手机号 / 邮箱",
  "LOGIN_PASSWORD_LABEL": "登录密码",
  "LOGIN_REMEMBER": "在这台设备上保持登录，下次免输密码",
  "REGISTER_GO_LOGIN": "直接登录",
  "REGISTER_HAVE_ACCOUNT": "已有账户？",
  "REGISTER_SUB": "学生免费发布需求，教师零佣金接单",
  "REGISTER_TITLE": "创建你的账户",
  "REG_ROLE_STUDENT": "我是学生",
  "REG_ROLE_TEACHER": "我是教师",
  "CHAT_SEND_PARTIAL_FAILED": "部分消息未发送，已恢复输入",
  "BTN_CONTINUE": "继续",
  "BTN_REVOKE": "撤销",
  "LABEL_NEW_USERNAME": "新用户名",
  "SETTINGS_AVATAR_INVALID": "头像格式不正确",
  "SETTINGS_AVATAR_SAVED": "头像已更新",
  "SETTINGS_AVATAR_TITLE": "修改头像",
  "SETTINGS_DEACTIVATED": "账户已注销",
  "SETTINGS_DEACTIVATE_CONFIRM": "确定注销账户吗？",
  "SETTINGS_DEACTIVATE_TITLE": "注销账户",
  "SETTINGS_DEACTIVATE_WARN": "注销后账号将被墓碑化",
  "SETTINGS_DEVICES_TITLE": "设备管理",
  "SETTINGS_DEVICE_REVOKED": "已撤销该设备登录",
  "SETTINGS_DEVICE_REVOKE_CONFIRM": "撤销该设备登录？",
  "SETTINGS_SAVED": "设置已保存",
  "SETTINGS_USERNAME_CHANGED": "用户名修改成功",
  "SETTINGS_USERNAME_CONFIRM": "确定修改用户名？",
  "SETTINGS_USERNAME_TITLE": "修改用户名",
  "DEMAND_DELETED_TOAST": "需求已删除",
  "INTENT_RESOLVED_TOAST": "已同意，可在「我的会话」中开始对话",
  "LABEL_SORT": "排序",           // Q-4a-M1b: teacher list filter/sort panel labels
  "LABEL_DAY": "可授课日",
  "LABEL_VERIFIED": "认证状态",
  "FILTER_UNVERIFIED": "未认证"
};
export default TEXT;
