/**
 * 服务端常量 shim（V-1-1）：只做 re-export，不写任何业务值。
 * 业务值唯一源在 ../src/shared/{config,enums,codes}.js。
 */
export {
  CONFIG, LIMITS, SECURITY, TEXT_AUDIT, RATE_LIMITS,
  CORS_ALLOWED_ORIGINS, CORS_HEADERS, SECURITY_HEADERS,
  INVITE_GATE_ENABLED, LEGACY_ADMIN_PASSWORD,
  INITIAL_RATING, INITIAL_WEIGHT,
  NUM_T, NUM_SEP, ADDRESS_GUARD, PHONE_HASH_COND, EMAIL_HASH_COND,
} from '../src/shared/config.js';
export {
  STATUS, SUBJECTS, STUDENT_GRADES, FIVE_FOUR_PROVINCES, TEACHER_GRADES,
  GENDERS, TEACHING_METHODS, WEEKDAYS, PERSONALITY_TAGS,
  NONACADEMIC_PROJECTS, TEACHING_GOALS, DEMAND_TYPES,
  ROLES, VERIFY_TYPES, COMPLAINT_TARGET_TYPES, AWARD_STATUS,
  DEACTIVATED_USER_PREFIX,
} from '../src/shared/enums.js';
export { MSG, CODES, NOTIFY_TYPES } from '../src/shared/codes.js';
