/**
 * contract feature user-facing text/data (copied verbatim from root constants.js UI).
 */

export const TEXT = {
  BTN_CANCEL: '取消',
  BTN_CANCEL_CONTRACT: '取消签约',
  BTN_CONTINUE_DANGER: '我已知晓后果，继续',
  BTN_MODIFY_CONTRACT: '修改内容',
  BTN_REVOKE_CONTRACT: '撤销合同',
  BTN_SAVE: '保存',
  BTN_SEND: '发送',
  BTN_SIGN: '开始签约',
  BTN_SIGNING_SEND: '发送签约请求',
  BTN_SIGN_WAITING: '等待对方确认签约',
  BTN_THINK_AGAIN: '再想想',
  BTN_VERIFY_LEDGER: '存证校验',
  BTN_VIEW_CONTRACT: '查看合同',
  CONFIRM_CANCEL_CONTRACT: '取消后回到待签约状态、合同保留（会话保留）。确定取消签约吗？',
  CONFIRM_SIGN_FINAL: '请输入账户密码完成最终确认。确认后合同生效，单方无法撤销。',
  CONFIRM_SIGN_TWICE: '确认签约后合同即生效、不可单方撤销。你确定已仔细阅读并确认这份合同吗？',
  CONTRACT_CANCELLED_TOAST: '已取消签约，合同保留待重新签约',
  CONTRACT_DEMANDS_EMPTY: '还没有已签约的需求。双方都确认签约后，这里才能起草正式合同。',
  CONTRACT_DEMANDS_LOAD_FAIL: '需求列表加载失败，请刷新页面后重试。',
  CONTRACT_DEMANDS_SIGNED_HINT: '仅已签约需求可继续签合同',
  CONTRACT_DIFF_HINT: '本次修改的改动处已高亮：绿色=新增，红色删除线=移除；法律条款未改动。',
  CONTRACT_DRAFT_SENT_TOAST: '合同草案已发送，等待对方确认',
  CONTRACT_EMPTY: '合同内容不能为空',
  CONTRACT_EMPTY_LIST: '还没有合同。双方确认签约后，可在「我的会话」里起草正式合同。',
  CONTRACT_LEDGER_ARCHIVED: '该合同已撤销，签署时的存证留档仍保留',
  CONTRACT_LEDGER_INVALID: '存证校验异常：文本与签署指纹不一致',
  CONTRACT_LEDGER_NONE: '该合同暂无存证记录',
  CONTRACT_LEDGER_VALID: '存证校验通过：合同文本与签署指纹一致',
  CONTRACT_LOCATION_NOTE: '出于隐私保护，授课地点请使用「甲方常住处」等模糊表述，勿将详细地址上传至平台。',
  CONTRACT_LOCATION_PLACEHOLDER: '甲方常住处或双方另行约定的地点',
  CONTRACT_MODIFIED_TOAST: '修改已同步给对方，双方需重新确认签约',
  CONTRACT_MODIFY_BIZ_HINT: '仅可修改业务条款，法律条款不可修改',
  CONTRACT_PARTY_PENDING_A: '甲方待签',
  CONTRACT_PARTY_PENDING_B: '乙方待签',
  CONTRACT_PARTY_SIGNED_A: '甲方已签',
  CONTRACT_PARTY_SIGNED_B: '乙方已签',
  CONTRACT_PAY_METHOD_OTHER_PLACEHOLDER: '请输入结算方式，如：每 10 次课结算一次',
  CONTRACT_PLAN_PLACEHOLDER: '描述教学目标、内容安排与上课节奏，发送后将按此信息生成正式合同',
  CONTRACT_PRICE_PLACEHOLDER: '如：150',
  CONTRACT_REQUIRE_SIGNED: '请选择已签约需求',
  CONTRACT_REVOKED_BY_ME: '你已撤销合同',
  CONTRACT_REVOKED_BY_PEER: '对方已撤销合同',
  CONTRACT_REVOKED_TOAST: '合同已撤销',
  CONTRACT_SIGNED_TOAST: '签约完成',
  CONTRACT_SIGN_DONE_BOTH: '双方已签署',
  CONTRACT_SUBJECT_LINE_PREFIX: '授课科目：',
  CONTRACT_TRIAL_PAY_OTHER_PLACEHOLDER: '请输入试课薪资方案',
  CONTRACT_VERIFY_CD_PREFIX: '#CD',
  CONTRACT_VERIFY_ENTRIES: '台账条目',
  CONTRACT_VERIFY_ENTRY_UNIT: '条',
  CONTRACT_VERIFY_FLOW: '存证流水号',
  CONTRACT_VERIFY_HASH: '当前指纹',
  CONTRACT_VERIFY_LABEL_HEAD: '链头',
  CONTRACT_VERIFY_LABEL_LINK: '连续性',
  CONTRACT_VERIFY_LABEL_SEQ: '序号',
  CONTRACT_VERIFY_PANEL_TITLE: '存证校验',
  CONTRACT_VIEW_DIFF_TITLE: '查看合同 · 本次改动',
  DRAFT_MODAL_TITLE: '起草合同',
  ERROR_LOAD_PREFIX: '加载失败: ',
  FUNDS_NOTE: '平台仅提供信息撮合与合同存证服务，不参与任何费用结算。课时费请由双方自行协商并在站外直接结算（如微信、支付宝转账等），平台不代收、不代付。',
  LABEL_CONTRACT_DEMAND: '对应需求',
  LABEL_CONTRACT_FIRST_LESSON: '首次上课日期',
  LABEL_CONTRACT_LOCATION: '授课地点',
  LABEL_CONTRACT_METHOD: '教学方式',
  LABEL_CONTRACT_PAY_METHOD: '薪资结算方式',
  LABEL_CONTRACT_PLAN: '教学方案',
  LABEL_CONTRACT_RATE: '约定时薪（元/小时）',
  LABEL_CONTRACT_SCHEDULE: '授课时间（每周固定时间段）',
  LABEL_CONTRACT_TRIAL_PAY: '试课薪资方案',
  LABEL_SIGNING_METHOD: '授课方式',
  LABEL_SIGNING_PRICE: '报价（元/小时）',
  LABEL_SIGNING_SCHEDULE: '授课时间（每周固定时间段）',
  MODIFY_CONTRACT_TITLE: '修改合同内容',
  PAY_METHOD_MONTHLY: '月付',
  PAY_METHOD_OTHER: '其他',
  PAY_METHOD_PER_SESSION: '次付',
  PAY_METHOD_WEEKLY: '周付',
  POST_MD_BOLD: '加粗',
  POST_PREVIEW_BTN: '预览效果',
  PRICE_UNIT: '元/h',
  REVOKE_CONTRACT_FINAL: '最终确认：撤销后不可恢复，确定继续吗？',
  REVOKE_CONTRACT_WARN: '此功能仅限在双方已经约定好结束合同时使用。撤销后合同不再生效，双方列表保留「已撤销」状态、正文与存证台账留档（合同不删除）。由此产生的一切法律后果由双方自行承担。',
  REVOKE_MODAL_TITLE: '撤销合同',
  SIGNING_DEMANDS_LOAD_FAIL: '需求列表加载失败，请刷新页面后重试。',
  SIGNING_DEMAND_LABEL: '选择需求',
  SIGNING_DEMAND_PLACEHOLDER: '请选择要签约的需求',
  SIGNING_METHOD_OFFLINE: '线下授课',
  SIGNING_METHOD_ONLINE: '线上授课',
  SIGNING_MODAL_HINT: '选择需求、确认报价、时间与授课方式后发送，由对方确认',
  SIGNING_MODAL_TITLE: '发起签约',
  SIGNING_NO_DEMAND_HINT: '暂时没有开放中的需求。先发布一条需求，双方确认意向后才能发起签约。',
  SIGNING_PRICE_PLACEHOLDER: '例如 150',
  SIGNING_REQUEST_SENT_TOAST: '签约请求已发送',
  SIGN_COUNTDOWN_HINT: '{secs}秒后可确认签约',
  SIGN_MODAL_DISCLOSE: '你将以平台账号「{username}」电子签署本合同：实名登录 + 密码二次确认即构成可靠电子签名，签署后合同即生效。',
  SIGN_MODAL_TITLE: '开始签约',
  SIGN_READY_HINT: '已阅读完毕，可确认签约',
  SIGN_READ_DONE_BTN: '我已阅读并确认签约',
  SIGN_READ_HINT: '请阅读合同全文并滚动到底部，方可确认',
  TRIAL_PAY_FIRST_FREE: '第一次试课免费',
  TRIAL_PAY_FIRST_HOUR_FREE: '第一小时免费，第二小时收费',
  TRIAL_PAY_NORMAL: '全程正常收费',
  TRIAL_PAY_OTHER: '其他',
  VALIDATE_CONTRACT_FIRST_LESSON_INCOMPLETE: '请完整填写首次上课日期（年/月/日）',
  VALIDATE_CONTRACT_PAY_METHOD_OTHER: '请输入具体的薪资结算方式',
  VALIDATE_CONTRACT_PLAN: '请填写教学方案',
  VALIDATE_CONTRACT_RATE: '请填写约定时薪',
  VALIDATE_CONTRACT_TRIAL_PAY_OTHER: '请输入具体的试课薪资方案',
  VALIDATE_SIGNING_DEMAND: '请选择要签约的需求',
  VALIDATE_SIGNING_PRICE: '请填写有效报价',
  VALIDATE_SIGNING_SCHEDULE: '请填写授课时间',
  PAGE_MY_CONTRACTS: '我的合同',
  PAGE_MY_CONTRACTS_DESC: '合同草案确认与正式签约',
  CONTRACT_BIZ_END: '<!-- 业务条款结束',
  POST_MD_BOLD_DEFAULT: '粗体',
};
