/**
 * posts feature user-facing text (copied verbatim from root constants.js UI).
 */

export const TEXT = {
  BROADCAST_BODY_PLACEHOLDER: '输入通知正文，全部用户都会收到（支持轻量 Markdown）',
  BROADCAST_CONFIRM_TEXT: '广播将通知全站所有用户，请输入密码确认发送。',
  BROADCAST_MODAL_TITLE: '发送系统通知',
  BROADCAST_SENT_TOAST: '通知已发送给全部用户',
  BROADCAST_TITLE_PLACEHOLDER: '通知标题（推送时自动加【系统通知】前缀）',
  BTN_CANCEL: '取消',
  BTN_COMPLAINT_FEEDBACK: '投诉与反馈',
  BTN_CONFIRM_DELETE: '确认删除',
  BTN_CREATE_POST: '发布帖子',
  BTN_FAVORITE: '收藏',
  BTN_FAVORITED: '已收藏',
  BTN_PUBLISH: '发布',
  BTN_SEND: '发送',
  BTN_SEND_NOTIFICATION: '发通知',
  FEEDBACK_CHOOSE_BUG: '我要反馈 Bug',
  FEEDBACK_CHOOSE_COMPLAINT: '我要投诉',
  FEEDBACK_CHOOSE_SUGGESTION: '我要提出建议',
  FEEDBACK_EMPTY: '反馈内容不能为空',
  FEEDBACK_MODAL_TITLE_BUG: '反馈 Bug',
  FEEDBACK_MODAL_TITLE_SUGGEST: '提出建议',
  FEEDBACK_PLACEHOLDER: '详细描述你遇到的问题或建议（支持轻量 Markdown）',
  FEEDBACK_SENT_TOAST: '反馈已提交，感谢你的声音',
  FEEDBACK_STATUS_OPEN: '未处理',
  FEEDBACK_STATUS_RESOLVED: '已处理',
  FEEDBACK_TITLE_PLACEHOLDER: '一句话概括你的问题或建议',
  MY_FEEDBACK_EMPTY: '还没有提交过反馈或投诉',
  MY_FEEDBACK_TITLE: '我的投诉与反馈',
  POSTS_EMPTY: '还没有帖子，分享一份教学资料，帮到更多同行。',
  POSTS_FAV_ACTIVE: '已进入我的收藏',
  POSTS_FAV_EMPTY: '还没有收藏，看到有用的教学资料点一下书签图标，收藏后在这里随时查看。',
  POSTS_SEARCH_PLACEHOLDER: '搜索标题或正文',
  POSTS_SORT_HOT: '最热优先',
  POSTS_SORT_NEW: '最新优先',
  POSTS_VIEW_FAV: '我的收藏',
  POST_ANONYMOUS: '匿名',
  POST_BODY_PLACEHOLDER: '支持轻量 Markdown：## 大标题、### 小标题、**加粗**、插入图片（图片以本地文件嵌入）',
  POST_BTN_DELETE: '删除',
  POST_DELETED: '帖子已删除',
  POST_DELETE_CONFIRM: '删除后不可恢复，点赞数据一并清空。确认删除这篇帖子？',
  POST_DELETE_TITLE: '删除帖子',
  POST_FAVORITED_TOAST: '已收藏，可在「我的收藏」查看',
  POST_FAV_ARIA: '收藏',
  POST_IMAGE_ALT: '图片',
  POST_IMAGE_ONLY: '请选择图片文件',
  POST_LABEL_TITLE: '标题',
  POST_LIKED_TOAST: '已点赞',
  POST_LIKE_ARIA: '点赞',
  POST_MD_BOLD_DEFAULT: '加粗文本',
  POST_MODAL_TITLE_CREATE: '发布帖子',
  POST_PREVIEW_EMPTY: '暂无内容，点击「预览效果」查看渲染结果',
  POST_PREVIEW_TITLE: '预览效果',
  POST_PUBLISHED: '发布成功',
  POST_PUBLISHING: '发布中',
  POST_TITLE_PLACEHOLDER: '一句话概括分享内容',
  POST_TITLE_REQUIRED: '标题不能为空',
  POST_UNFAVORITED_TOAST: '已取消收藏',
  POST_UNLIKED_TOAST: '已取消点赞',
  POST_VIEW_ARIA: '查看帖子全文',
  VALIDATE_BROADCAST_EMPTY: '通知内容不能为空',
  PAGE_RESOURCE_SHARE: '资料共享',
  PAGE_RESOURCE_SHARE_DESC: '与同行共享教学资源',
};
