/**
 * settings feature user-facing text (copied verbatim from root constants.js UI).
 */

export const TEXT = {
  ABOUT_FLOW_STEP_1: '发布需求：填写年级、科目与预算，发布你的家教需求',
  ABOUT_FLOW_STEP_2: '对接教师：把需求直接发给心仪的教师，或等待教师发来试课意向',
  ABOUT_FLOW_STEP_3: '确认开聊：对方确认后自动开启会话，在站内沟通课程细节',
  ABOUT_FLOW_STEP_4: '起草合同：在会话中起草家教服务合同，约定时间、地点与课时费',
  ABOUT_FLOW_STEP_5: '双方签约：到「我的合同」确认签署，按约开始上课',
  ABOUT_FUNDS_TEXT: '平台是公益信息平台，仅提供信息撮合与合同存证服务，不参与任何费用结算，也不从任何交易中抽成。课时费的金额与支付方式由你与老师/学员自行协商，并在站外直接结算（如微信、支付宝转账）。请勿向平台支付任何费用。',
  ABOUT_FUNDS_TITLE: '关于费用',
  ABOUT_SECURITY_INTRO: '我们把大家的信息安全看得很重。下面这些保护，是为了让你和家长都能安心使用：',
  ABOUT_SECURITY_ITEMS: '',
  ABOUT_SECURITY_TITLE: '安全与隐私保护',
  ABOUT_SUPPORT_EMAIL: '邮箱：support_sufe_tutor@163.com',
  ABOUT_SUPPORT_OWNER: '平台负责人：康同学',
  ABOUT_SUPPORT_TITLE: '用户支持',
  ABOUT_SUPPORT_WECHAT: '微信：13524121020',
  ABOUT_USAGE_TITLE: '平台基本用法',
  ABOUT_WHO_TEXT: '经途·伴学信息门户是由上海财经大学在校学生的家教团体运营的公益信息平台。我们的初衷很简单：为想做家教的同学（尤其是持有教师资格证的在校大学生与研究生）提供勤工俭学、社会实践的机会，也帮家长和同学直接对接合适的老师，中间不赚一分钱差价。平台不开展任何有偿培训业务，不向老师收取佣金，也不向家长学员收取任何中介费用。为响应国家「双减」政策，我们谢绝在职老师及校外培训机构注册与合作。',
  ABOUT_WHO_TITLE: '我们是谁',
  ADMISSION_GATE_BACK: '← 返回学信网验证',
  ADMISSION_GATE_PENDING: '录取通知书已提交，管理员核验中（一般 24 小时内完成），通过后自动开放资料填写',
  ADMISSION_GATE_TITLE: '验证录取通知书',
  ADMISSION_IMAGE_INVALID: '录取通知书图片格式不正确（仅支持 jpg/png 等常见图片）',
  ADMISSION_IMAGE_TOO_LARGE: '录取通知书图片过大，请压缩后重新上传',
  ADMISSION_PRIVACY_NOTE: '隐私保护声明：录取通知书照片仅用于身份核验，管理员人工核对后将加密存储，不会公开展示，审核结束后仅保留核验结论。',
  ADMISSION_SHOOT_HINT: '请拍摄或上传录取通知书的完整整页照片，确保姓名、考生号、录取院校与专业清晰可读',
  ADMISSION_SUBMIT: '提交核验',
  ADMISSION_SWITCH_LINK: '我是大一新生，改为验证录取通知书',
  ADMISSION_UPLOAD_BTN: '选择录取通知书照片',
  ADMISSION_VERIFYING: '提交中…',
  AVATAR_SAVED_TOAST: '头像已更新',
  AWARD_ADD_BTN: '添加奖项',
  AWARD_DATE_LABEL: '获奖时间',
  AWARD_DATE_PLACEHOLDER: '如 2025-06（可选）',
  AWARD_DELETE_CONFIRM: '确定删除该奖项吗？删除后需重新提交审核。',
  AWARD_EMPTY: '还没有添加奖项。提交获奖证明并审核通过后，会展示在教师主页。',
  AWARD_ISSUER_LABEL: '颁发机构',
  AWARD_ISSUER_PLACEHOLDER: '如：中国数学会',
  AWARD_PROOF_HINT: '上传奖状/获奖证书图片，管理员审核通过后公开展示',
  AWARD_PROOF_LABEL: '奖状证明',
  AWARD_REJECTED_NOTE_PREFIX: '驳回理由：',
  AWARD_STATUS_APPROVED: '已通过',
  AWARD_STATUS_PENDING: '待审核',
  AWARD_STATUS_REJECTED: '已驳回',
  AWARD_SUBMITTED: '奖项已提交，等待管理员审核',
  AWARD_TITLE_LABEL: '奖项名称',
  AWARD_TITLE_PLACEHOLDER: '如：全国高中数学联赛一等奖',
  BTN_CANCEL: '取消',
  BTN_CLOSE: '关闭',
  BTN_COMPLAINT_FEEDBACK: '投诉与反馈',
  BTN_CONTINUE_DANGER: '我已知晓后果，继续',
  BTN_DEACTIVATE_ACCOUNT: '注销账户',
  BTN_DELETE: '删除',
  BTN_DEVICE_LOGOUT: '下线',
  BTN_LOGOUT: '退出登录',
  BTN_MODIFY: '修改',
  BTN_MY_COMPLAINTS_FEEDBACK: '我的投诉与反馈',
  BTN_SAVE: '保存',
  BTN_SUBMIT: '提交',
  BTN_SUBMITTING: '提交中...',
  BTN_THINK_AGAIN: '再想想',
  BTN_UPLOAD_AVATAR: '上传头像',
  BTN_USERNAME_SAVE: '确认修改',
  BTN_USERNAME_SAVING: '保存中...',
  CHSI_CODE_REQUIRED: '请输入学信网在线验证码',
  CHSI_GATE_HINT: '提交验证码后，平台会核对你的学籍信息（院校、层次、专业、在读状态、入学年份），通过后自动填入资料卡。',
  CHSI_GATE_PENDING: '验证码已提交，管理员核验中（一般 24 小时内完成），通过后自动开放资料填写',
  CHSI_GATE_PLACEHOLDER: '请输入学信网在线验证码',
  CHSI_GATE_STEPS: ['打开学信网 APP', '登录后进入「学籍查询」', '申请《学籍在线验证报告》', '复制在线验证码（有效期 180 天）'],
  CHSI_GATE_SUBMIT: '提交核验',
  CHSI_GATE_TITLE: '验证学信网学籍',
  CHSI_GATE_VERIFYING: '核验中…',
  CHSI_INFO_LEVEL: '层次',
  CHSI_INFO_MAJOR: '专业',
  CHSI_INFO_SCHOOL: '院校全称',
  CHSI_INFO_STATUS: '在读状态',
  CHSI_INFO_TITLE: '学信网核验信息（自动填入，不可修改）',
  CHSI_INFO_YEAR: '入学年份',
  CHSI_SUCCESS: '学信网核验通过，学籍信息已自动填入',
  CONFIRM_LOGOUT: '退出后需要重新登录。确定退出当前账户吗？',
  CONTACT_AFTER_SIGN_NOTE: '签约后展示联系方式',
  CREDENTIAL_REUPLOAD: '重新上传',
  CREDENTIAL_UPLOAD: '上传',
  CREDENTIAL_UPLOADED_VIEW: '已上传，点击查看',
  DEACTIVATE_DONE_TOAST: '账户已注销',
  DEACTIVATE_FINAL: '最终确认：注销后账户与个人数据不可恢复，确定继续吗？',
  DEACTIVATE_WARN: '注销后：你的教师档案、发布的帖子与点赞、反馈、通知等仅与你一人相关的数据将被永久删除；需求、会话、合同、评价等涉及双方的数据会保留，但你的用户名将显示为「已注销用户」。此操作不可恢复。',
  DEVICE_CURRENT: '当前设备',
  DEVICE_LOGIN_AT: '登录于 ',
  DEVICE_REVOKE_CONFIRM: '确定要让该设备退出登录吗？该设备上的会话将立即失效。',
  DEVICE_REVOKE_DONE: '该设备已下线',
  DEVICE_UNKNOWN: '未知设备',
  ERROR_REQUEST_FAILED: '请求失败',
  FILE_TYPE_BLOCKED: '不支持的文件类型',
  GAOKAO_POLICY_MISMATCH_WARN: '检测到 {n} 条成绩按往年政策填写，当前政策无法匹配。请填写「毕业年份」切换到当年政策，否则保存后这些成绩将被移除。',
  GRAD_YEAR_PLACEHOLDER: '如 2020（留空按最新政策）',
  HINT_SELECT_PROVINCE_GAOKAO: '请先选择省份（高考所在地），按该省政策填写高考成绩',
  LABEL_GRADUATION_YEAR: '毕业年份',
  LABEL_NONACADEMIC_PRICES: '非学科类项目报价',
  LABEL_NONACADEMIC_PROJECTS: '擅长非学科类项目',
  LABEL_PERSONALITY_TAGS: '性格关键词',
  LABEL_PRICE_RANGE: '报价区间（元/小时）',
  LABEL_SHANGHAI_RESIDENCE: '上海常住地',
  LABEL_TEACHING_METHOD_PROFILE: '授课方式',
  LABEL_TIME_SLOTS: '可授课时间段',
  ONBOARD_REVISIT_BTN: '重温新手引导',
  OPTION_PLACEHOLDER: '请选择',
  ORB_MODE_ELEGANT: '淡雅',
  ORB_MODE_HIDDEN: '隐藏',
  ORB_MODE_VIVID: '鲜艳',
  PAGE_ABOUT: '关于平台',
  PAGE_TITLE_EDIT_PROFILE: '编辑个人资料',
  PERSONALITY_TAGS_HINT: '（最多 {max} 个）',
  PLACEHOLDER_MAX: '最高',
  PLACEHOLDER_MIN: '最低',
  POST_IMAGE_ONLY: '请选择图片文件',
  PROFILE_FIELD_AFTER_MATCH: '建立会话后展示',
  PROFILE_SECTION_ACADEMIC: '学科类资料',
  PROFILE_SECTION_BASIC: '基本资料',
  PROFILE_SECTION_NONACADEMIC: '非学科类资料',
  PROFILE_SECTION_PRIVATE: '私密资料',
  SETTINGS_ACCOUNT_TITLE: '账户设置',
  SETTINGS_APPEARANCE_TITLE: '外观设置',
  SETTINGS_AVATAR: '账户头像',
  SETTINGS_DEVICES: '登录设备',
  SETTINGS_DEVICES_EMPTY: '当前只有这台设备登录。',
  SETTINGS_DEVICES_HINT: '以下是登录过此账户的设备，可让其他设备下线。',
  SETTINGS_EMAIL: '邮箱',
  SETTINGS_ORB_FLAT_HIDDEN: '（平面简约下强制隐藏）',
  SETTINGS_ORB_HINT: '背景漂移光球的显示效果：鲜艳=彩色柔光，淡雅=若有若无，隐藏=纯净底色',
  SETTINGS_ORB_LABEL: '背景光球',
  SETTINGS_PHONE: '电话',
  SETTINGS_PRIVACY_DEMAND_HINT: '关闭后，未登录的游客看不到你发布的需求，仅登录用户可见',
  SETTINGS_PRIVACY_DEMAND_LABEL: '允许访客浏览我的需求',
  SETTINGS_PRIVACY_OFF: '关闭',
  SETTINGS_PRIVACY_ON: '允许',
  SETTINGS_PRIVACY_PROFILE_HINT: '关闭后，未登录的游客看不到你的资料卡，仅登录用户可见',
  SETTINGS_PRIVACY_PROFILE_LABEL: '允许访客浏览我的教师档案',
  SETTINGS_PRIVACY_SAVED: '隐私设置已保存',
  SETTINGS_PRIVACY_TITLE: '隐私设置',
  SETTINGS_ROLE: '账户角色',
  SETTINGS_STYLE_HINT: '整站视觉风格：液态玻璃（毛玻璃+光影）／平面简约（纯色无磨砂，更轻快）',
  SETTINGS_STYLE_LABEL: '页面风格',
  SETTINGS_THEME_HINT: '亮色、暗色或跟随系统自动切换',
  SETTINGS_THEME_LABEL: '界面配色',
  SETTINGS_UI_SCALE_HINT: '调整界面文字、按钮与输入组件的整体大小（{min}%~{max}%，默认 {def}%）',
  SETTINGS_UI_SCALE_LABEL: 'UI大小',
  SETTINGS_UNBOUND: '未绑定',
  SETTINGS_USERNAME: '账户用户名',
  SHANGHAI_RESIDENCE_NOTE: '仅上海线下订单参与距离匹配（选至镇/街道即可，精确位置后续自行沟通）',
  STYLE_FLAT: '平面简约',
  STYLE_LIQUID: '液态玻璃',
  SUCCESS_DELETED: '已删除',
  SUCCESS_PROFILE_SAVED: '信息已保存！',
  THEME_DARK: '暗色',
  THEME_LIGHT: '亮色',
  THEME_SYSTEM: '跟随系统',
  USAGE_GUIDE_BTN: '详细用法介绍',
  USERNAME_CHANGE_CONFIRM_FMT: '确定将用户名修改为「{name}」吗？修改后 7 天内不可再次修改。',
  USERNAME_CHANGE_TITLE: '修改用户名',
  USERNAME_CHARS_ERR: '用户名只能包含中文、字母、数字及 _ . - （3-30 个字符），且不能为纯数字、不能含 @',
  USERNAME_COOLDOWN: '用户名 7 天内只能修改一次',
  USERNAME_COOLDOWN_BTN: '{time}后可再次修改用户名',
  USERNAME_LENGTH_ERR: '用户名长度需在 3-30 个字符之间',
  USERNAME_NEW_HINT: '修改后全平台即时更新；7 天内只能改一次。',
  USERNAME_NEW_LABEL: '新用户名',
  USERNAME_NEW_PLACEHOLDER: '输入新用户名（3-30 字符，不含 @ 与纯数字）',
  VALIDATE_SELECT_PROVINCE: '请选择省份',
  VALIDATE_SELECT_SUBJECT: '请至少选择一个科目',
  BTN_CONTINUE: '继续',
  BTN_REVOKE: '撤销',
  LABEL_NEW_USERNAME: '新用户名',
  PAGE_ACCOUNT_SETTINGS: '设置',
  PAGE_ACCOUNT_SETTINGS_DESC: '外观主题与账户设置',
  SETTINGS_AVATAR_INVALID: '头像格式不正确',
  SETTINGS_AVATAR_SAVED: '头像已更新',
  SETTINGS_AVATAR_TITLE: '修改头像',
  SETTINGS_DEACTIVATED: '账户已注销',
  SETTINGS_DEACTIVATE_CONFIRM: '确定注销账户吗？',
  SETTINGS_DEACTIVATE_TITLE: '注销账户',
  SETTINGS_DEACTIVATE_WARN: '注销后账号将被墓碑化',
  SETTINGS_DEVICES_TITLE: '设备管理',
  SETTINGS_DEVICE_REVOKED: '已撤销该设备登录',
  SETTINGS_DEVICE_REVOKE_CONFIRM: '撤销该设备登录？',
  SETTINGS_SAVED: '设置已保存',
  SETTINGS_USERNAME_CHANGED: '用户名修改成功',
  SETTINGS_USERNAME_CONFIRM: '确定修改用户名？',
  SETTINGS_USERNAME_TITLE: '修改用户名',
};
