/**
 * student/demand feature user-facing text (copied verbatim from root constants.js UI).
 */

export const TEXT = {
  A11Y_VIEW_PROFILE: '查看该用户资料',
  ADDRESS_PLACEHOLDER: '选择所在区与镇/街道',
  ADDRESS_PREFIX: '地址：',
  BADGE_TYPE_ACADEMIC: '学科',
  BADGE_TYPE_NONACADEMIC: '非学科',
  BTN_AGREE: '同意',
  BTN_CANCEL: '取消',
  BTN_DELETE_DEMAND: '删除需求',
  BTN_EDIT: '编辑',
  BTN_NEXT_STEP: '下一步',
  BTN_PREV_STEP: '上一步',
  BTN_PUSH_ACCEPT: '确认试课意向',
  BTN_PUSH_DEMAND: '发送需求',
  BTN_PUSH_REJECT: '暂时没空',
  BTN_REJECT: '拒绝',
  BTN_REMOVE: '移除',
  BTN_REOPEN_DEMAND: '重开需求',
  BTN_SAVE_DEMAND: '保存修改',
  BTN_SEND: '发送',
  BTN_SUBMIT_DEMAND: '提交需求',
  BTN_SUBMIT_INTENT: '提交试课意向',
  BTN_VIEW: '查看',
  BUDGET_NEGOTIABLE: '面议',
  BUDGET_NO_LIMIT: '不限',
  BUDGET_UNIT_SUFFIX: '元/h',
  CONFIRM_DELETE_DEMAND: '删除后不可恢复，相关教师意向也会一并清除。确定要删除这条需求吗？',
  CONFIRM_REOPEN_DEMAND: '重开后该需求将重新出现在需求大厅，再次接受教师意向。确定重开吗？',
  CONTACT_AFTER_SIGN_NOTE: '签约后展示联系方式',
  CONTACT_PLACEHOLDER: '手机邮箱',
  DEMAND_DETAIL_ARRANGE: '上课安排',
  DEMAND_DETAIL_CONTACT_HINT: '签约后可查看联系方式',
  DEMAND_DETAIL_EMPTY: '未填写',
  DEMAND_DETAIL_GOAL: '学习目标',
  DEMAND_DETAIL_STUDENT: '学生信息',
  DEMAND_DETAIL_TITLE_FALLBACK: '需求详情',
  DEMAND_FILTER_ALL: '全部',
  DEMAND_FILTER_EMPTY: '没有符合筛选条件的需求',
  DEMAND_INFO_PLACEHOLDER: '上课时间偏好、特殊要求等',
  DEMAND_REOPENED_TOAST: '需求已重新开放',
  DEMAND_SORT_BUDGET: '预算从低到高',
  DEMAND_SORT_MATCH: '匹配度最高',
  DEMAND_SORT_NEWEST: '最新发布',
  DEMAND_TAG_CONTRACTED: '已签约',
  DEMAND_TAG_REVOKED: '合同已撤销',
  DW_STEP_BUDGET: '预算与时间',
  DW_STEP_METHOD: '教学方式',
  DW_STEP_PROVINCE: '省份',
  DW_STEP_SCORES: '成绩情况',
  DW_STEP_STUDENT: '学生概况',
  DW_STEP_SUBJECTS: '科目',
  DW_STEP_SUBMIT: '补充信息',
  DW_STEP_TEACHER_PREF: '教师偏好',
  EMPTY_NO_DEMANDS: '还没有学生发布需求。教师可以先完善档案，新需求会按匹配度推荐给你。',
  EMPTY_NO_INTENTS: '还没有教师提交意向。收到意向后，可以在这里同意或拒绝。',
  EMPTY_NO_MY_DEMANDS: '还没有发布过需求。点「新建需求」，填写学生情况和期望的科目、预算，老师看到后会联系你。',
  EMPTY_NO_MY_DEMANDS_SHORT: '你还没有需求，先去「我的需求」发布一条吧。',
  ERROR_LOAD_PREFIX: '加载失败: ',
  GREET_HEAD_STUDENT: '学生留言',
  GREET_HEAD_TEACHER: '教师留言',
  HINT_SELECT_PROVINCE_GRADE: '请先选择省份和年级',
  HINT_SELECT_TARGET_SUBJECTS: '请先选择目标科目',
  INTENTS_TITLE: '试课意向',
  INTENT_ACCEPTED_GO: '已建立联系 →',
  INTENT_ACCEPTED_TOAST: '已同意，可在「我的会话」中开始对话',
  INTENT_GREET_DEMAND: '你将向这条需求提交试课意向：{demand}',
  INTENT_GREET_LABEL: '和对方打个招呼（可选）',
  INTENT_GREET_OPTIONAL: '可留空直接提交；填写后学生会在「试课意向」里看到这段话。',
  INTENT_GREET_PLACEHOLDER: '简单介绍一下自己，说说为什么想接下这单～（例：老师您好，我教初中数学五年，带过三届中考班，对您孩子的分数情况很有把握）',
  INTENT_GREET_TITLE: '提交试课意向',
  INTENT_PENDING: '意向已提交',
  INTENT_REJECTED: '未获选',
  INTENT_REJECTED_TOAST: '已拒绝该意向',
  INTENT_STATUS_ACCEPTED: '已同意',
  INTENT_STATUS_PENDING: '待处理',
  INTENT_STATUS_REJECTED: '已拒绝',
  INTENT_SUBMITTED_TOAST: '试课意向已提交，等待学生处理',
  LABEL_ADDITIONAL_INFO: '其他补充信息',
  LABEL_ADDRESS: '地址（授课区域）',
  LABEL_BUDGET: '预算区间（元/小时）',
  LABEL_BUDGET_SHORT: '预算',
  LABEL_CONTACT: '联系方式',
  LABEL_CURRENT_SCORES: '各科当前大概成绩',
  LABEL_EXPECTED_TIME: '期望开课时间',
  LABEL_GENDER: '性别',
  LABEL_GRADE: '年级',
  LABEL_METHOD: '教学方式',
  LABEL_MULTI_SUFFIX: '（可多选）',
  LABEL_PARENT_CONTACT: '家长联系方式',
  LABEL_PREFERRED_GENDER: '偏好老师性别',
  LABEL_PREFERRED_PERSONALITY: '偏好老师性格',
  LABEL_PROVINCE: '省份',
  LABEL_SKILL_STATUS: '技能现状',
  LABEL_STUDENT_CONTACT: '学生联系方式',
  LABEL_STUDENT_GENDER: '学生性别',
  LABEL_STUDENT_GRADE: '学生年级',
  LABEL_SUBJECT: '科目',
  LABEL_SUBMITTER: '提交者身份',
  LABEL_TARGET_PROJECTS: '需求项目',
  LABEL_TARGET_SUBJECTS: '目标科目',
  LABEL_TEACHING_GOAL: '教学目标',
  LABEL_TEACHING_METHOD: '期望教学方式',
  LABEL_TEACHING_METHOD_PROFILE: '授课方式',
  LABEL_TYPE_ACADEMIC: '学科辅导',
  LABEL_TYPE_NONACADEMIC: '非学科培养',
  MATCH_BUDGET_HIT: '报价在需求预算区间内',
  MATCH_BUDGET_MISS: '报价超出需求预算区间',
  MATCH_DETAIL_SUB: '根据你的教师档案与这条需求自动计算',
  MATCH_DETAIL_TITLE: '匹配度明细',
  MATCH_DIM_SKIP: '该项缺数据，未计入',
  MATCH_DISTANCE_HIT: '距授课点约 {km} 公里',
  MATCH_DISTANCE_NO_LOCALE: '教师未填上海常住地，未计入',
  MATCH_DISTANCE_ONLINE: '线上授课，距离不计分',
  MATCH_DISTANCE_SAME: '同镇/同街道，零距离',
  MATCH_GENDER_ANY: '需求不限性别',
  MATCH_GENDER_HIT: '性别符合需求偏好',
  MATCH_GENDER_MISS: '性别不符需求偏好',
  MATCH_GENDER_UNDISCLOSED: '教师未透露性别，明确偏好折半计分',
  MATCH_ITEM_BUDGET: '预算匹配',
  MATCH_ITEM_GENDER: '性别匹配',
  MATCH_ITEM_PERSONALITY: '性格匹配',
  MATCH_ITEM_REGION: '区域匹配',
  MATCH_ITEM_SUBJECT: '科目匹配',
  MATCH_NOTE: '计分口径：科目 {subject} 分（命中需求科目的比例）+ 区域 {region} 分（上海线下按教师常住地距授课点公里数计分、线上单不计）+ 预算 {budget} 分（报价在区间内）+ 性格 {personality} 分（偏好性格重合比例）+ 性别 {gender} 分（偏好性别吻合）。缺数据的维度不计分，总分按有效维度归一化到 100。',
  MATCH_PERSONALITY_HIT: '命中 {hit}/{total} 个偏好性格',
  MATCH_PERSONALITY_MISS: '教师性格与偏好无重合',
  MATCH_REGION_HIT: '同省（{name}），区域吻合',
  MATCH_REGION_MISS: '省份不符，区域不匹配',
  MATCH_SUBJECT_HIT: '命中 {hit}/{total} 门需求科目',
  MODAL_TITLE_DEMAND_CREATE: '提交学生需求',
  MODAL_TITLE_DEMAND_EDIT: '编辑学生需求',
  OPTION_GENDER_NOT_SAY: '不愿透露',
  OPTION_PLACEHOLDER: '请选择',
  OPTION_PREF_GENDER_ANY: '不限',
  PERSONALITY_TAGS_HINT: '（最多 {max} 个）',
  PLACEHOLDER_MAX: '最高',
  PLACEHOLDER_MIN: '最低',
  PRICE_UNIT: '元/h',
  PROFILE_INCOMPLETE_HINT: '提交试课意向前，请先完善教师档案：省份、年级、性别、擅长科目、报价均为必填。学生要看到完整的教师信息，才能判断是否接受你的意向。',
  PROFILE_INCOMPLETE_TITLE: '档案不完整',
  PUSH_ACCEPTED_TAG: '已确认',
  PUSH_ACCEPTED_TOAST: '已确认，可在「我的会话」开始对话',
  PUSH_BTN_COOLDOWN: '已发送',
  PUSH_GREET_LABEL: '和老师打个招呼（可选）',
  PUSH_GREET_OPTIONAL: '可留空直接发送；填写后老师会在需求卡上看到这段话。',
  PUSH_GREET_PLACEHOLDER: '简单介绍一下自己，说说为什么想请这位老师～（例：老师您好，孩子初二数学偏弱，看到您带过三届中考班，想请您试试）',
  PUSH_MODAL_HINT: '选一条需求发送给这位老师，对方会在需求大厅优先看到它。',
  PUSH_MODAL_TITLE_PREFIX: '把需求发给 ',
  PUSH_NOTE_TEXT: '学生主动向你提交了需求',
  PUSH_NO_AVAILABLE_DEMANDS: '暂时没有可发送的需求。先到「我的需求」发布一条，开放中的需求才能发给老师。',
  PUSH_REJECTED_TAG: '已谢绝',
  PUSH_REJECTED_TOAST: '已谢绝',
  PUSH_SECTION_TITLE: '学生主动发给你的需求',
  PUSH_SENT_FALLBACK: '需求已发送',
  PUSH_TEACHER_FALLBACK: '该老师',
  REGION_HINT_OFFLINE_ONLY: '目前只支持上海的线下教学',
  SELECT_PROVINCE_FIRST: '请先选择地区',
  SKILL_NOTE_PLACEHOLDER: '描述当前水平/证书/考级/获奖（选填）',
  SUBMITTER_PARENT: '家长',
  SUBMITTER_PREFIX: '提交者: ',
  SUBMITTER_STUDENT: '学生',
  SUCCESS_DEMAND_DELETED: '需求已删除',
  SUCCESS_DEMAND_SUBMITTED: '需求已提交！',
  SUCCESS_DEMAND_UPDATED: '需求已更新！',
  TAG_MATCH: '匹配度 ',
  TAG_MATCH_HINT: ' · 点击展开明细',
  TAG_MATCH_TITLE: '点击查看匹配度明细',
  TEACHING_GOALS_HINT: '（最多 {max} 个）',
  VALIDATE_ADDRESS_REQUIRED: '请选择所在区与镇/街道',
  VALIDATE_BUDGET_RANGE: '预算区间有误：最低价不能高于最高价',
  VALIDATE_CONTACT_REQUIRED: '请填写家长与学生联系方式',
  VALIDATE_SELECT_DEMAND: '请先选择一条需求',
  VALIDATE_SELECT_GRADE: '请选择学生年级',
  VALIDATE_SELECT_PROVINCE: '请选择省份',
  VALIDATE_SELECT_SUBJECT: '请至少选择一个科目',
  DEMAND_DELETED_TOAST: '需求已删除',
  INTENT_RESOLVED_TOAST: '已同意，可在「我的会话」中开始对话',
  PAGE_BROWSE_DEMANDS: '需求大厅',
  PAGE_BROWSE_DEMANDS_DESC: '浏览学生需求并提交意向',
  PAGE_MY_DEMANDS: '我的需求',
  PAGE_MY_DEMANDS_DESC: '发布与管理家教需求',
};
