/**
 * onboard feature user-facing text (copied verbatim from root constants.js UI).
 */

export const TEXT = {
  CHAT_ROLE_STUDENT: '学生',
  CHAT_ROLE_TEACHER: '教师',
  FUNDS_NOTE_SHORT: '平台不参与费用结算，课费请与对方站外直接结算。',
  ONBOARD_CONFIRM: '知道了',
  ONBOARD_CONFIRM_BROWSE: '知道了，进客户端逛逛',
  ONBOARD_INTRO: '学生和家教老师直接对接，零佣金、不收费；三步就能开始使用。',
  ONBOARD_POLICY: ['学生：发布需求 → 浏览教师 → 匹配后站内沟通', '教师：浏览需求 → 提交试课意向 → 匹配后站内沟通', '匹配成功后在「我的会话」沟通上课细节，到「我的合同」正式签约', '平台不向老师或学生收取中介费，课费由双方自行结算'],
  ONBOARD_TITLE: '欢迎来到经途·伴学信息门户',
  TOUR_ARIA_LABEL: '新手引导',
  TOUR_DEMO_CHAT_EMPTY: '示例会话：还没有消息，可以试试下方的输入框和 + 号。',
  TOUR_DEMO_CHAT_NAME_STUDENT: '示例教师',
  TOUR_DEMO_CHAT_NAME_TEACHER: '示例学生',
  TOUR_DEMO_CHAT_PREVIEW: '示例会话：这里展示聊天窗口，还没有消息。',
  TOUR_DEMO_CONTRACT_CONFIRM: '确认合同',
  TOUR_DEMO_CONTRACT_HINT: '这里展示合同卡片：对方、科目、报价与状态都在这里，操作按钮在下方。',
  TOUR_DEMO_CONTRACT_MODIFY: '修改合同',
  TOUR_DEMO_CONTRACT_TITLE: '示例合同',
  TOUR_DEMO_CONTRACT_VIEW: '查看合同',
  TOUR_SKIP_GLOBAL: '跳过引导',
  TOUR_STEP_ABOUT: '关于平台：平台理念、基本用法、安全隐私与反馈通道。点击进入。',
  TOUR_STEP_ABOUT_FEEDBACK: '反馈通道：遇到问题或建议，点这里告诉我们。',
  TOUR_STEP_ABOUT_FLOW: '学生签约完整流程：发布需求 → 双向匹配 → 站内沟通 → 确认意向 → 正式签约。',
  TOUR_STEP_ABOUT_SECURITY: '安全与隐私：联系方式签约后才展示，详细住址不收集，敏感资料加密存储。',
  TOUR_STEP_ABOUT_WHO: '我们是谁：一句话介绍平台定位。',
  TOUR_STEP_ACCOUNT_SETTINGS: '设置：账户设置与外观设置都在这里。点击进入。',
  TOUR_STEP_ADMIN_AWARDS: '奖项审核：核对教师上传的奖状证明，通过后展示在教师主页；驳回时填理由通知教师。',
  TOUR_STEP_ADMIN_CONTENT: '内容审核：全站内容统一提取与一键处罚（删除/封禁），处罚会自动通知作者。',
  TOUR_STEP_ADMIN_END: '以上是管理端核心工作台。封禁、处罚、广播等危险操作都需要密码二次确认。',
  TOUR_STEP_ADMIN_STATS: '统计页：平台运营数据总览。',
  TOUR_STEP_ADMIN_TODO: '待办事项：待审核的评价、奖项与未处理反馈、投诉都汇总在这，点一下直达处理页。',
  TOUR_STEP_BROWSE_DEMANDS: '需求大厅：学生发布的家教需求都在这，按匹配度排好序。点击进入。',
  TOUR_STEP_BROWSE_TEACHERS: '教师广场：平台上的全部教师都在这，按匹配度从高到低排。点击进入。',
  TOUR_STEP_BROWSE_TEACHERS_PEER: '教师同行：看看其他老师怎么介绍自己、怎么定价，可以用来调整自己的档案。',
  TOUR_STEP_CHAT_MESSAGES: '这里是聊天记录，消息会自动同步；聊天内容用于平台留档，联系方式此时仍互相不可见。',
  TOUR_STEP_CHAT_PLUS: '点这个 + 号，唤出功能栏；下面的每一项都介绍一下。',
  TOUR_STEP_CHAT_PLUS_DRAFT: '「起草合同」：签约确认后，在这里起草正式合同条款发给对方。',
  TOUR_STEP_CHAT_PLUS_FILE: '「文件」：教案、资料 PDF 也能发——选文件后随消息发送。',
  TOUR_STEP_CHAT_PLUS_IMAGE: '「图片」：把截图、错题照片直接发进会话，点开可看大图。',
  TOUR_STEP_CHAT_PLUS_SIGNING: '「发起签约」：谈妥了就在这里发起签约意向，对方确认后进入合同流程。',
  TOUR_STEP_CHAT_SEND: '底部输入框打字，点「发送」；也支持图片和文件。',
  TOUR_STEP_CHSI_GATE: '先完成学信网验证：输入学信网在线验证报告上的验证码，核验通过后即可填写详细资料并开始接单。',
  TOUR_STEP_CONTRACTS_LIST: '合同列表：每张卡片对应一份合同，带状态标签（待确认 / 签署中 / 已签）。',
  TOUR_STEP_CONTRACT_ACTIONS: '底部操作：确认签约、修改合同、查看合同。签好后联系方式才互相可见。',
  TOUR_STEP_CONTRACT_CARD: '一张合同卡：看对方、科目、报价、关联需求编号。',
  TOUR_STEP_CONV_ITEM: '左侧是会话列表，每个会话对应一位师生。点一个打开聊天窗。',
  TOUR_STEP_DEMAND_CARD: '一条需求卡：期望时间、预算区间、授课方式都在上面，先看看合不合适。',
  TOUR_STEP_DEMAND_DETAIL: '这是需求详情：学习目标、上课安排和学生信息都在这里，提交意向前先完整看一遍。',
  TOUR_STEP_DEMAND_DETAIL_CLOSE: '点击关闭详情，回到需求列表。',
  TOUR_STEP_DEMAND_ID_TAG: '需求编号 #0001：沟通时用它指代这条需求，对方一看就知道是哪条。',
  TOUR_STEP_DEMAND_INTENT_BTN: '「提交试课意向」按钮：觉得合适就点它，等学生确认后自动开启会话。',
  TOUR_STEP_DEMAND_LIST: '这里就是需求列表。每张卡写着发起人、科目、年级、预算和上课方式，先看这几项判断是否合适。',
  TOUR_STEP_DEMAND_WIZARD: '发布需求是分步表单，跟着顶部进度条逐页填写；每页填完会自动进入下一页，随时可以返回修改。',
  TOUR_STEP_EDIT_PROFILE: '个人资料：完善你的档案，学生据此了解你、信任你。点击进入。',
  TOUR_STEP_FILTER_SUBJECT: '选科目、报价等条件，列表会即时筛选；清空条件就看全部。',
  TOUR_STEP_FILTER_TOGGLE: '「筛选」按钮：按科目、报价上限、最低评分过滤教师。',
  TOUR_STEP_GUEST_LOGIN: '到这里就逛完啦：点下方个人信息栏登录或注册，登录后就能使用全部功能。',
  TOUR_STEP_INTENT_TOGGLE: '展开「教师意向」：谁想来教，同意或拒绝都在这处理。',
  TOUR_STEP_MY_CHATS: '我的会话：匹配成功后的沟通窗口，双方的联系方式此时互相不可见。点击进入。',
  TOUR_STEP_MY_CONTRACTS: '我的合同：谈妥上课细节后，在这走正式签约，保障双方权益。点击进入。',
  TOUR_STEP_MY_DEMANDS: '我的需求：你发布的家教需求都在这管理。点击进入。',
  TOUR_STEP_MY_DEMANDS_LIST: '需求列表：每条显示科目、预算、状态；待处理的教师意向有红点提醒。',
  TOUR_STEP_NEW_DEMAND_BTN: '点「新建需求」打开发布表单。',
  TOUR_STEP_NEW_DEMAND_MODAL: '表单共 8 步：省份 → 授课方式 → 学生信息 → 科目 → 成绩情况 → 教师偏好 → 预算时间 → 联系方式。顶部进度条随页推进，随时可返回修改。',
  TOUR_STEP_NOTIFICATIONS: '通知信息：试课意向、需求推送、合同进展都汇总在这。点击进入。',
  TOUR_STEP_NOTIF_BLOCK: '右上角「屏蔽系统通知」：不想看系统广播点一下，再点恢复。',
  TOUR_STEP_NOTIF_ITEM: '一条通知：展示内容与时间；红点代表未读。',
  TOUR_STEP_NOTIF_LIST: '通知列表：每条通知写着处理进展，点击未读通知即可标为已读。',
  TOUR_STEP_POSTS_CREATE: '「发布帖子」按钮：分享一份教学资料，帮到更多同行。',
  TOUR_STEP_POSTS_LIST: '资料列表：按最新 / 最热排序，浏览同行分享的帖子。',
  TOUR_STEP_POSTS_MODAL: '发布窗口：填标题和正文，支持 Markdown 和插入图片。点击关闭。',
  TOUR_STEP_POSTS_SEARCH: '搜索框：输入关键词，快速找你想看的资料。',
  TOUR_STEP_POSTS_SORT: '排序：最新优先 / 最热优先，随你切换。',
  TOUR_STEP_PROFILE_AWARDS: '荣誉奖项：上传奖状证明，管理员审核通过后会展示在你的教师主页。',
  TOUR_STEP_PROFILE_CLOSE: '点右上角 ✕ 关闭资料栏，回到列表。',
  TOUR_STEP_PROFILE_FORM: '资料表单：省份、年级、学校、毕业年份等基本信息都在这填。',
  TOUR_STEP_PROFILE_PRICE: '报价区间：填最低和最高课时费，学生按这个区间判断。',
  TOUR_STEP_PROFILE_SUBJECTS: '擅长科目：勾选你教的科目，可多选。',
  TOUR_STEP_PROFILE_SUBMIT: '填完点「保存」，资料就更新了。越完整越容易被选中。',
  TOUR_STEP_PUSH_MODAL: '选一条你的需求发送过去，老师确认后自动开启会话。点击关闭。',
  TOUR_STEP_RESOURCE_SHARE: '资料共享：同行分享教学资料的地方。点击进入。',
  TOUR_STEP_SETTINGS_ACCOUNT: '账户设置区：头像、用户名、角色；可以上传头像。',
  TOUR_STEP_SETTINGS_LOGOUT: '页底「退出登录」，注销账户也在这里。',
  TOUR_STEP_SETTINGS_LOGOUT_MODAL: '退出前会再次确认；注销账户入口也在设置页底部，操作不可恢复。',
  TOUR_STEP_SETTINGS_THEME: '界面配色：亮色、暗色或跟随系统自动切换。',
  TOUR_STEP_SETTINGS_UI_SCALE: 'UI 大小：拖动滑块整体调大调小界面文字和按钮。',
  TOUR_STEP_TEACHERS_LIST: '教师列表：每张卡片显示地区、学校、年级、报价区间、可授课时间。',
  TOUR_STEP_TEACHER_PUSH_BTN: '「发送需求」按钮：把你的需求直接发给这位老师。',
  TOUR_STEP_TEACHER_USERNAME: '点老师的名片卡片（整卡可点），打开右侧资料栏看成绩、评价和联系方式规则。',
  TOUR_STEP_USER_BAR: '个人信息栏：点头像查看自己的信息；退出登录在「设置」页，想重温新手引导去「关于平台」页。',
  USAGE_GUIDE_BTN: '详细用法介绍',
  USAGE_GUIDE_SECTIONS: '',
  USAGE_GUIDE_TITLE: '详细用法介绍',
  BTN_START: '开始',
  ONBOARD_GUEST_HINT: '游客可先浏览公开内容',
  ONBOARD_GUIDE: '使用引导',
  ONBOARD_TOUR_START: '开始引导',
};
