/**
 * complaints feature user-facing text/data (copied verbatim from root constants.js UI).
 */

export const TEXT = {
  ADMIN_COMPLAINT_EMPTY: '还没有投诉记录，新投诉会出现在这里。',
  BTN_CANCEL: '取消',
  BTN_COMPLAINT_RESOLVE: '标记已处理',
  BTN_SEND: '发送',
  CHAT_ATTACH_IMAGE: '图片',
  CHAT_FILE_FALLBACK: '文件',
  CHAT_FILE_TOO_LARGE: '文件太大（上限 500KB，图片会自动压缩）',
  COMPLAINT_ATTACH_ADD: '添加附件',
  COMPLAINT_ATTACH_FAIL: '附件加载失败',
  COMPLAINT_ATTACH_LABEL: '上传附件（选填，最多 4 个，图片可上传 4 张以下）',
  COMPLAINT_ATTACH_TOO_MANY: '附件最多 4 个',
  COMPLAINT_ATTACH_UPLOADING: '请等待附件上传完成',
  COMPLAINT_CHANGE_TARGET: '更换',
  COMPLAINT_DETAIL_LABEL: '补充描述',
  COMPLAINT_DETAIL_PLACEHOLDER: '补充具体问题、发生时间等（选填，支持轻量 Markdown）',
  COMPLAINT_MODAL_TITLE: '提交投诉',
  COMPLAINT_REASONS: ['虚假信息或欺诈', '侮辱谩骂或骚扰', '侵犯隐私', '违法违规内容', '恶意营销或广告', '其他'],
  COMPLAINT_REASON_LABEL: '投诉理由',
  COMPLAINT_REASON_PLACEHOLDER: '请选择理由',
  COMPLAINT_REASON_REQUIRED: '请选择投诉理由',
  COMPLAINT_RECENT_LABEL: '最近联系的人',
  COMPLAINT_REPORTER_LABEL: '投诉人',
  COMPLAINT_RESOLVED_TOAST: '已标记处理并通知投诉人',
  COMPLAINT_SEARCH_EMPTY: '未找到匹配对象，可输入 id 精确搜索',
  COMPLAINT_SEARCH_PLACEHOLDER: '输入 id 或昵称搜索',
  COMPLAINT_SEARCH_POST_PLACEHOLDER: '输入帖子 id 或标题搜索',
  COMPLAINT_SELECTED_PREFIX: '已选择：',
  COMPLAINT_SENT_TOAST: '投诉已提交，我们会尽快核实处理',
  COMPLAINT_STATUS_OPEN: '处理中',
  COMPLAINT_STATUS_RESOLVED: '已处理',
  COMPLAINT_TAB_POST: '投诉帖子',
  COMPLAINT_TAB_STUDENT: '投诉学生',
  COMPLAINT_TAB_TEACHER: '投诉教师',
  COMPLAINT_TARGET_REQUIRED: '请选择要投诉的对象',
  PAGE_ADMIN_COMPLAINT: '投诉处理',
  PAGE_ADMIN_COMPLAINT_DESC: '查看并处理用户提交的投诉（对象 / 理由 / 详情）',
};
