/**
 * admin feature user-facing text (copied verbatim from root constants.js UI).
 */

export const TEXT = {
  ADMIN_AWARD_APPROVE: '通过',
  ADMIN_AWARD_APPROVE_CONFIRM: '确定通过该奖项审核吗？通过后将展示在教师主页。',
  ADMIN_AWARD_NONE: '当前没有待审核的奖项，新提交会出现在这里。',
  ADMIN_AWARD_PROOF_VIEW: '查看奖状',
  ADMIN_AWARD_REJECT: '驳回',
  ADMIN_AWARD_REJECT_CONFIRM: '确定驳回该奖项吗？理由将通知教师。',
  ADMIN_AWARD_REJECT_HINT: '驳回理由（必填，将通知教师）',
  ADMIN_AWARD_REJECT_PLACEHOLDER: '如：奖状模糊、无法辨认颁发机构',
  ADMIN_AWARD_TEACHER_LABEL: '教师',
  ADMIN_CONTENT_EMPTY: '当前筛选条件下没有内容。',
  ADMIN_CONTENT_PENALTY_BAN: '封禁作者',
  ADMIN_CONTENT_PENALTY_DELETE: '删除',
  ADMIN_CONTENT_PENALTY_HINT: '处罚后将自动通知作者，附上原因、规则与触发内容摘要。',
  ADMIN_CONTENT_PENALTY_REASON: '处罚原因（必填）',
  ADMIN_CONTENT_PENALTY_RULE: '触犯规则',
  ADMIN_CONTENT_PENALTY_TITLE: '处罚{type} #{id}',
  ADMIN_CONTENT_TYPE_COMPLAINT: '投诉',
  ADMIN_CONTENT_TYPE_CONTRACT: '合同',
  ADMIN_CONTENT_TYPE_DEMAND: '需求',
  ADMIN_CONTENT_TYPE_FEEDBACK: '反馈',
  ADMIN_CONTENT_TYPE_MESSAGE: '聊天',
  ADMIN_CONTENT_TYPE_POST: '帖子',
  ADMIN_CONTENT_TYPE_REVIEW: '评价',
  ADMIN_CONTENT_TYPE_SIGNING: '签约请求',
  ADMIN_CONTENT_TYPE_TEACHER: '教师档案',
  ADMIN_CONTENT_TYPE_UPLOAD: '附件',
  ADMIN_CONTRACTS_EMPTY: '还没有合同记录。',
  ADMIN_CONTRACT_DRAFTER_PREFIX: '起草 ',
  ADMIN_CONTRACT_REMOVED_TOAST: '合同已移除',
  ADMIN_DASH_24H: '24 小时请求',
  ADMIN_DASH_AVG: '平均耗时',
  ADMIN_DASH_AVG_FMT: '{n} ms',
  ADMIN_DASH_EMPTY: '指标采样刚开始，稍后就有数据。',
  ADMIN_DASH_ERRORS: '服务端异常',
  ADMIN_DASH_LIMITED: '限流命中',
  ADMIN_DASH_SLOW: '慢请求',
  ADMIN_DASH_STATUS: '状态码分布',
  ADMIN_DASH_TOP_PATHS: '高频接口（近 24 小时）',
  ADMIN_DEMANDS: '需求数',
  ADMIN_FEEDBACK_EMPTY: '还没有用户反馈，新的问题和建议会出现在这里。',
  ADMIN_INVITES_USED: '已用邀请码',
  ADMIN_PENALTY_CONFIRM: '将{action}该内容并通知作者，确认继续？',
  ADMIN_PENALTY_DONE: '已处理',
  ADMIN_PENALTY_REASON_PLACEHOLDER: '如：含详细门牌号，违反平台隐私红线',
  ADMIN_PENALTY_RULE_PLACEHOLDER: '如：地址门控 / 内容安全',
  ADMIN_POSTS_EMPTY: '还没有教师发布资料，新帖子会出现在这里。',
  ADMIN_PROFILES: '教师档案',
  ADMIN_RECENT_DEMANDS: '最近需求',
  ADMIN_RECENT_USERS: '最近注册用户',
  ADMIN_REVIEWS_APPROVED: '已通过评价',
  ADMIN_REVIEWS_PENDING: '待审评价',
  ADMIN_STUDENTS: '学生',
  ADMIN_TEACHERS: '教师',
  ADMIN_TODO_AWARDS: '待审核奖项',
  ADMIN_TODO_COMPLAINTS: '未处理投诉',
  ADMIN_TODO_FEEDBACKS: '未处理反馈',
  ADMIN_TODO_REVIEWS: '待审核评价',
  ADMIN_TODO_TITLE: '待办事项',
  ADMIN_TODO_VERIFICATIONS: '待核验申请',
  ADMIN_TOTAL_USERS: '总用户',
  ADMISSION_GATE_TITLE: '验证录取通知书',
  AWARD_REJECTED_NOTE_PREFIX: '驳回理由：',
  AWARD_STATUS_APPROVED: '已通过',
  AWARD_STATUS_PENDING: '待审核',
  AWARD_STATUS_REJECTED: '已驳回',
  BAN: '封禁',
  BTN_APPROVE: '通过',
  BTN_CANCEL: '取消',
  BTN_CLOSE: '关闭',
  BTN_DELETE_REVIEW: '删除评价',
  BTN_FEEDBACK: '用户反馈',
  BTN_GENERATE_INVITE: '生成邀请码',
  BTN_LOAD_MORE: '加载更多',
  BTN_MARK_RESOLVED: '标记已处理',
  BTN_REJECT: '拒绝',
  BTN_REMOVE: '移除',
  BTN_REMOVE_CONTRACT: '移除合同',
  BTN_VIEW: '查看',
  BTN_VIEW_CONTRACT: '查看合同',
  BTN_VIEW_DETAIL: '查看详情 / 评价',
  CHSI_INFO_LEVEL: '层次',
  CHSI_INFO_MAJOR: '专业',
  CHSI_INFO_SCHOOL: '院校全称',
  CHSI_INFO_STATUS: '在读状态',
  CHSI_INFO_YEAR: '入学年份',
  CONFIRM_ADMIN_REMOVE_CONTRACT: '移除后合同彻底删除（操作留档保留）。确定移除该合同吗？',
  CONFIRM_BAN: '封禁后该账户将无法登录。确定要封禁吗？',
  CONFIRM_UNBAN: '确定要解除该账户的封禁吗？',
  CONTRACT_DIFF_HINT: '本次修改的改动处已高亮：绿色=新增，红色删除线=移除；法律条款未改动。',
  CONTRACT_VIEW_DIFF_TITLE: '查看合同 · 本次改动',
  DEACTIVATED_USER_PREFIX: '已注销用户',
  DEMAND_COUNT_SUFFIX: ' 条需求',
  EMPTY_NO_DEMANDS: '还没有学生发布需求。教师可以先完善档案，新需求会按匹配度推荐给你。',
  EMPTY_NO_REVIEWS: '还没有人写下评价。与该教师完成签约后，学生可以分享真实的上课体验。',
  EMPTY_NO_USERS: '当前筛选条件下没有用户。调整筛选条件后再看看。',
  ERROR_GENERATE_INVITE: '生成失败: ',
  ERROR_LOAD_PREFIX: '加载失败: ',
  FEEDBACK_RESOLVED_TOAST: '已标记处理并通知提出者',
  FEEDBACK_STATUS_OPEN: '未处理',
  FEEDBACK_STATUS_RESOLVED: '已处理',
  INVITE_MANAGER_ACTIVE: '未使用',
  INVITE_MANAGER_CODE: '邀请码',
  INVITE_MANAGER_CREATED: '创建时间',
  INVITE_MANAGER_EMPTY: '还没有邀请码，点击「生成邀请码」创建',
  INVITE_MANAGER_REVOKE: '作废',
  INVITE_MANAGER_REVOKED: '邀请码已作废',
  INVITE_MANAGER_STATUS: '状态',
  INVITE_MANAGER_TITLE: '邀请码管理',
  INVITE_MANAGER_USED: '已使用',
  INVITE_MANAGER_USED_BY: '使用者',
  INVITE_NO_EXPIRY: '无有效期 · 一人使用即失效',
  LOADING: '加载中...',
  ONBOARD_CONFIRM: '知道了',
  PAGE_ADMIN_TRAFFIC_DESC: '站点流量与平均延迟',
  POST_DELETED: '帖子已删除',
  POST_DELETE_CONFIRM: '删除后不可恢复，点赞数据一并清空。确认删除这篇帖子？',
  POST_LIKE_ARIA: '点赞',
  PRICE_UNIT: '元/h',
  RATING_SCORE_SUFFIX: ' 分',
  REGISTERED_AT_PREFIX: '注册于 ',
  SUCCESS_BANNED: '已封禁该账户',
  SUCCESS_COPIED: '已复制',
  SUCCESS_UNBANNED: '已解封该账户',
  TAG_BANNED: '已封禁',
  TRAFFIC_HINT: '口径：仅统计写操作与失败请求（读/轮询流量不入留档）；平均延迟 = 服务端处理耗时',
  TRAFFIC_LATENCY_TITLE: '平均延迟',
  TRAFFIC_MS_UNIT: ' ms',
  TRAFFIC_RANGE_24H: '24小时',
  TRAFFIC_RANGE_30D: '近30天',
  TRAFFIC_RANGE_7D: '近7天',
  TRAFFIC_SAMPLE_FMT: '样本 {n} 桶',
  TRAFFIC_TITLE: '站点总流量',
  TRAFFIC_TOTAL_FMT: '合计 {n} 次',
  UNBAN: '解封',
  UNVERIFY: '撤认证',
  UNVERIFY_CONFIRM: '确认撤销该教师的学籍认证吗？',
  UNVERIFY_DONE: '已撤销学籍认证',
  VERIFIED_BADGE: '✓ 已认证',
  VERIFY_CONFIRM: '确认通过该教师的学籍认证吗？认证徽章将展示在教师主页。',
  VERIFY_DONE: '已通过学籍认证',
  VERIFY_TEACHER: '认证',
  VERIF_ADMISSION_NO_CODE: '录取通知书核验（无验证码）',
  VERIF_ADMISSION_TAG: '录取通知书',
  VERIF_ADMISSION_VIEW_IMG: '查看通知书原图',
  VERIF_APPROVED: '已通过',
  VERIF_APPROVED_OK: '核验已通过，学籍信息已填入教师档案并通知',
  VERIF_APPROVE_BTN: '核验通过',
  VERIF_APPROVE_REQUIRED: '院校与层次为必填项',
  VERIF_EMPTY: '没有核验记录',
  VERIF_FORM_HINT: '去学信网核验页（xlcx.chsi.com.cn 或学信网小程序扫码）查证这个验证码对应的报告，按报告内容填写院校、层次等信息后通过。',
  VERIF_LEVEL_PLACEHOLDER: '本科 / 硕士',
  VERIF_PENDING: '待核验',
  VERIF_REJECTED: '已拒绝',
  VERIF_REJECTED_OK: '已拒绝该核验申请并通知教师',
  VERIF_REJECT_BTN: '拒绝',
  VERIF_REVOKED_OK: '已撤销该教师核验资格并通知',
  VERIF_REVOKE_BTN: '撤销核验',
  VERIF_SCHOOL_PLACEHOLDER: '如：上海财经大学',
  VERIF_STATUS_PLACEHOLDER: '在籍 / 已毕业',
  VERIF_YEAR_PLACEHOLDER: '如 2024',
  ADMIN_ADMISSION_IMAGE: '录取通知书',
  ADMIN_AWARD_PROOF: '奖状证明',
  ADMIN_BAN: '封禁用户',
  ADMIN_BAN_CONFIRM: '确认封禁？',
  ADMIN_DELETE_CONFIRM: '确认删除？',
  ADMIN_DONE: '操作成功',
  ADMIN_INVITE: '邀请码管理',
  ADMIN_PENALTY: '内容处罚',
  ADMIN_POST_VIEW: '帖子详情',
  ADMIN_REASON: '处罚原因',
  ADMIN_REASON_REQUIRED: '请填写处罚原因',
  ADMIN_UNBAN_CONFIRM: '确认解封？',
  BTN_CONFIRM: '确定',
  BTN_DELETE: '删除',
  PAGE_ADMIN_STATS: '统计',
  PAGE_ADMIN_STATS_DESC: '平台运行数据总览',
};
