/**
 * chat feature user-facing text/data (copied verbatim from root constants.js UI).
 */

export const TEXT = {
  BTN_CANCEL: '取消',
  BTN_SIGNING_CONFIRM: '确认签约',
  BTN_SIGNING_REJECT: '拒绝',
  CHAT_ATTACH_FAIL: '附件加载失败',
  CHAT_ATTACH_FILE: '文件',
  CHAT_ATTACH_IMAGE: '图片',
  CHAT_ATTACH_REMOVED: '附件已被发送方移除',
  CHAT_BACK_TO_LIST: '会话列表',
  CHAT_BTN_DRAFT_CONTRACT: '起草合同',
  CHAT_BTN_SEND: '发送',
  CHAT_CLOSED_TIP: '会话已结束，不能再发消息。如需继续沟通，请重新发起会话或走合同流程。',
  CHAT_CONTRACT_BUBBLE_MINE: '你向对方发送了一份合同草案，可前往「我的合同」查看进度',
  CHAT_CONTRACT_BUBBLE_OTHER: '对方向你发送了一份合同草案，请前往「我的合同」查看并确认',
  CHAT_CONV_NOT_FOUND: '未找到与该学生的会话',
  CHAT_DOWNLOAD: '下载',
  CHAT_DROP_HINT: '松开加入发送',
  CHAT_EMPTY_NO_CONVS: '还没有会话。学生同意教师试课意向、或教师确认学生推送后，会话会自动建立。',
  CHAT_EMPTY_NO_MESSAGES: '还没有消息，先打个招呼吧',
  CHAT_FILE_FALLBACK: '文件',
  CHAT_FILE_TOO_LARGE: '文件太大（上限 500KB，图片会自动压缩）',
  CHAT_INPUT_PLACEHOLDER: '输入消息',
  CHAT_PLACEHOLDER_SUB: '同意试课意向后自动建立会话，消息会自动同步',
  CHAT_PLACEHOLDER_TITLE: '选择左侧会话，开始沟通',
  CHAT_PLUS_ARIA: '附件与合同',
  CHAT_PREVIEW_CONTRACT: '[合同草案]',
  CHAT_PREVIEW_FILE: '[文件]',
  CHAT_PREVIEW_IMAGE: '[图片]',
  CHAT_PREVIEW_ME_PREFIX: '我：',
  CHAT_PREVIEW_SIGNING_REQ: '[签约请求]',
  CHAT_PREVIEW_SIGNING_RESP: '[签约回应]',
  CHAT_SIGNING_METHOD: '方式',
  CHAT_SIGNING_MINE_TITLE: '你向对方发送了签约请求',
  CHAT_SIGNING_PRICE: '报价',
  CHAT_SIGNING_REQUEST_TITLE: '对方向你发送了签约请求',
  CHAT_SIGNING_SCHEDULE: '时间',
  CHAT_SIGN_TIP: '双方已确认签约，建议在「我的合同」里起草正式合同。\n平台不代收代付，课费请与对方协商后站外结算。',
  CHAT_STAGE_WAIT: '请等待文件处理完成再发送',
  CHAT_TITLE: '会话',
  CHAT_UNKNOWN_USER: '未知用户',
  CONFIRM_SIGNING_ACCEPT: '接受签约？需求将锁定为已成交，其他教师的试课意向会被自动拒绝。请输入账户密码完成最终确认。',
  ERROR_LOAD_PREFIX: '加载失败: ',
  FUNDS_NOTE_SHORT: '平台不参与费用结算，课费请与对方站外直接结算。',
  NETWORK_ERROR: '网络连接失败，请检查网络后重试',
  PRICE_UNIT: '元/h',
  PROFILE_PANEL_TITLE: '个人信息',
  ROLE_STUDENT: '学生',
  ROLE_TEACHER: '教师',
  SIGNING_CONFIRMED: '对方已确认签约请求',
  SIGNING_METHOD_OFFLINE: '线下授课',
  SIGNING_METHOD_ONLINE: '线上授课',
  SIGNING_MODAL_TITLE: '发起签约',
  SIGNING_MY_CONFIRMED: '你已确认签约请求',
  SIGNING_MY_REJECTED: '你已拒绝此次签约请求',
  SIGNING_REJECTED: '对方已拒绝此次签约请求',
  SIGNING_REJECTED_TEXT: '已拒绝此次签约请求',
  PAGE_MY_CHATS: '我的会话',
  PAGE_MY_CHATS_DESC: '与匹配的师生在线沟通',
};
